$path = "c:\Users\16704\Desktop\tarot\popup.js"
$lines = Get-Content $path -Encoding UTF8
$out = @()
$inserted = $false
$i = 0
while ($i -lt $lines.Count) {
    $line = $lines[$i]
    if (-not $inserted -and $line -match '// ==+\s*初始化\s*==+') {
        # Insert decision spread methods before this line
        $out += '    // ============ 抉择牌阵 ============'
        $out += '    showDecisionPage() {'
        $out += '      const inputA = document.getElementById(''decision-input-a'");'
        $out += '      const inputB = document.getElementById('"decision-input-b'");'
        $out += '      const resultDiv = document.getElementById('"decision-result'");'
        $out += '      const compDiv = document.getElementById('"decision-comprehensive'");'
        $out += '      const funDiv = document.getElementById('"decision-fun-options'");'
        $out += '      const rpsResult = document.getElementById('"decision-rps-result'");'
        $out += '      const diceResult = document.getElementById('"decision-dice-result'");'
        $out += '      const redoBtn = document.getElementById('"decision-redo-btn'");'
        $out += '      if (inputA) inputA.value = '""';'
        $out += '      if (inputB) inputB.value = '""';'
        $out += '      if (resultDiv) resultDiv.classList.add('"hidden'");'
        $out += '      if (compDiv) compDiv.classList.add('"hidden'");'
        $out += '      if (funDiv) funDiv.classList.add('"hidden'");'
        $out += '      if (rpsResult) rpsResult.classList.add('"hidden'");'
        $out += '      if (diceResult) diceResult.classList.add('"hidden'");'
        $out += '      if (redoBtn) redoBtn.classList.add('"hidden'");'
        $out += '      this.showPage('"decision-page'");'
        $out += '    }'
        $out += ''
        $out += '    decisionDraw() {'
        $out += '      const inputA = document.getElementById('"decision-input-a'");'
        $out += '      const inputB = document.getElementById('"decision-input-b'");'
        $out += '      const labelA = document.getElementById('"decision-label-a'");'
        $out += '      const labelB = document.getElementById('"decision-label-b'");'
        $out += '      const slotA = document.getElementById('"decision-card-slot-a'");'
        $out += '      const slotB = document.getElementById('"decision-card-slot-b'");'
        $out += '      const readingA = document.getElementById('"decision-reading-a'");'
        $out += '      const readingB = document.getElementById('"decision-reading-b'");'
        $out += '      const compDiv = document.getElementById('"decision-comprehensive'");'
        $out += '      const compReading = document.getElementById('"decision-comprehensive-reading'");'
        $out += '      const recommendText = document.getElementById('"decision-recommend-text'");'
        $out += '      const funDiv = document.getElementById('"decision-fun-options'");'
        $out += '      const resultDiv = document.getElementById('"decision-result'");'
        $out += '      const redoBtn = document.getElementById('"decision-redo-btn'");'
        $out += '      const textA = inputA ? inputA.value.trim() : '""';'
        $out += '      const textB = inputB ? inputB.value.trim() : '""';'
        $out += '      if (!textA || !textB) { alert(this.currentLang === '"en'" ? '"Please enter both choices'" : '"请输入两个抉择'"); return; }'
        $out += '      const cards = this.getDeckData();'
        $out += '      const idxA = Math.floor(Math.random() * cards.length);'
        $out += '      const idxB = Math.floor(Math.random() * cards.length);'
        $out += '      const isRevA = Math.random() < 0.5;'
        $out += '      const isRevB = Math.random() < 0.5;'
        $out += '      this._decisionCards = [ { card: cards[idxA], isReversed: isRevA, text: textA }, { card: cards[idxB], isReversed: isRevB, text: textB } ];'
        $out += '      if (labelA) labelA.textContent = textA;'
        $out += '      if (labelB) labelB.textContent = textB;'
        $out += '      if (slotA) slotA.innerHTML = this.createCardElement(cards[idxA], isRevA, 0, '"decision'").outerHTML;'
        $out += '      if (slotB) slotB.innerHTML = this.createCardElement(cards[idxB], isRevB, 0, '"decision'").outerHTML;'
        $out += '      if (readingA) readingA.innerHTML = ''<div style=""font-weight:700;color:var(--color-gold);margin-bottom:6px;""'' + (this.currentLang==='"'en'"'?'"'Choice A''':'"'抉择一''') + ''</div><div>'' + this.getMeaningText(this._decisionCards[0].card, this._decisionCards[0].isReversed) + ''</div>'';'
        $out += '      if (readingB) readingB.innerHTML = ''<div style=""font-weight:700;color:var(--color-gold);margin-bottom:6px;""'' + (this.currentLang==='"'en'"'?'"'Choice B''':'"'抉择二''') + ''</div><div>'' + this.getMeaningText(this._decisionCards[1].card, this._decisionCards[1].isReversed) + ''</div>'';'
        $out += '      if (compDiv) compDiv.classList.remove('"hidden'");'
        $out += '      if (funDiv) funDiv.classList.remove('"hidden'");'
        $out += '      if (resultDiv) resultDiv.classList.remove('"hidden'");'
        $out += '      if (redoBtn) redoBtn.classList.remove('"hidden'");'
        $out += '      const scoreA = this._decisionGetScore(this._decisionCards[0].card, this._decisionCards[0].isReversed);'
        $out += '      const scoreB = this._decisionGetScore(this._decisionCards[1].card, this._decisionCards[1].isReversed);'
        $out += '      const recommended = scoreA >= scoreB ? 0 : 1;'
        $out += '      if (recommendText) recommendText.textContent = recommended === 0 ? textA : textB;'
        $out += '      if (compReading) {'
        $out += '        let html = ''"";'
        $out += '        if (this.currentLang === ''en'') {'
        $out += '          html += ''<div style=""margin-bottom:10px;""><span style=""color:var(--color-gold);font-weight:700;"">Choice A ('' + textA + ''</span> drew <span style=""color:var(--color-gold-light);""'' + deckManager.getCardName(this._decisionCards[0].card) + ''</span>. '' + this._decisionCardAdvice(textA, this._decisionCards[0].card, this._decisionCards[0].isReversed, ''en'') + ''</div>'';'
        $out += '          html += ''<div style=""margin-bottom:10px;""><span style=""color:var(--color-gold);font-weight:700;"">Choice B ('' + textB + ''</span> drew <span style=""color:var(--color-gold-light);""'' + deckManager.getCardName(this._decisionCards[1].card) + ''</span>. '' + this._decisionCardAdvice(textB, this._decisionCards[1].card, this._decisionCards[1].isReversed, ''en'') + ''</div>'';'
        $out += '          html += ''<div style=""margin-top:10px;padding-top:8px;border-top:1px solid rgba(255,215,0,0.2);""><span style=""color:var(--color-gold);font-weight:700;"">Recommendation:</span> '' + (recommended === 0 ? (''Favor '' + textA + '' because the card energy is more positive.'') : (''Favor '' + textB + '' because the card energy is more positive.'')) + ''</div>'';'
        $out += '        } else {'
        $out += '          html += ''<div style=""margin-bottom:10px;""><span style=""color:var(--color-gold);font-weight:700;"">抉择一（'' + textA + ''）</span> 抽到 <span style=""color:var(--color-gold-light);""'' + deckManager.getCardName(this._decisionCards[0].card) + ''</span>。'' + this._decisionCardAdvice(textA, this._decisionCards[0].card, this._decisionCards[0].isReversed, ''zh'') + ''</div>'';'
        $out += '          html += ''<div style=""margin-bottom:10px;""><span style=""color:var(--color-gold);font-weight:700;"">抉择二（'' + textB + ''）</span> 抽到 <span style=""color:var(--color-gold-light);""'' + deckManager.getCardName(this._decisionCards[1].card) + ''</span>。'' + this._decisionCardAdvice(textB, this._decisionCards[1].card, this._decisionCards[1].isReversed, ''zh'') + ''</div>'';'
        $out += '          html += ''<div style=""margin-top:10px;padding-top:8px;border-top:1px solid rgba(255,215,0,0.2);""><span style=""color:var(--color-gold);font-weight:700;"">综合建议：</span> '' + (recommended === 0 ? (''建议优先选择「'' + textA + ''」，牌面能量更积极。'') : (''建议优先选择「'' + textB + ''」，牌面能量更积极。'')) + ''</div>'';'
        $out += '        }'
        $out += '        compReading.innerHTML = html;'
        $out += '      }'
        $out += '    }'
        $out += ''
        $out += '    _decisionGetScore(card, isReversed) {'
        $out += '      const num = card.id || 0;'
        $out += '      return isReversed ? -num : num;'
        $out += '    }'
        $out += ''
        $out += '    _decisionCardAdvice(choiceText, card, isReversed, lang) {'
        $out += '      const name = deckManager.getCardName(card);'
        $out += '      if (lang === ''en'') {'
        $out += '        return (isReversed ? (''The reversed '' + name + '' suggests inner reflection is needed before proceeding with '' + choiceText + ''.'') : (''The upright '' + name + '' suggests positive energy for '' + choiceText + ''.''));'
        $out += '      }'
        $out += '      return (isReversed ? (name + ''（逆位）暗示在做出「'' + choiceText + ''」决定前需要内省和调整。'') : (name + ''（正位）暗示「'' + choiceText + ''」充满积极能量，值得尝试。''));'
        $out += '    }'
        $out += ''
        $out += '    playRPS(userChoice) {'
        $out += '      const choices = [''\u270A'', ''\u270B'', ''\u270C''];'
        $out += '      const computerChoice = Math.floor(Math.random() * 3);'
        $out += '      const beats = { 0: 2, 1: 0, 2: 1 };'
        $out += '      const userWins = beats[userChoice] === computerChoice;'
        $out += '      const isTie = userChoice === computerChoice;'
        $out += '      const resultDiv = document.getElementById('"decision-rps-result'");'
        $out += '      if (!resultDiv) return;'
        $out += '      let html = ''"";'
        $out += '      html += ''<div>'' + (this.currentLang==='"'en'" ? ''You chose: '' : ''你出了：'') + choices[userChoice] + ''</div>'';'
        $out += '      html += ''<div>'' + (this.currentLang==='"'en'" ? ''Computer chose: '' : ''电脑出了：'') + choices[computerChoice] + ''</div>'';'
        $out += '      if (isTie) {'
        $out += '        html += ''<div class=""rps-winner"">'' + (this.currentLang==='"'en'" ? ''Tie! No winner.'' : ''平局！不分胜负。'') + ''</div>'';'
        $out += '      } else if (userWins) {'
        $out += '        const winChoice = this._decisionCards && this._decisionCards[0] ? this._decisionCards[0].text : (this.currentLang==='"'en'" ? ''Choice A'' : ''抉择一'');'
        $out += '        html += ''<div class=""rps-winner"">'' + (this.currentLang==='"'en'" ? ''You win! '' : ''你赢了！'') + winChoice + (this.currentLang==='"'en'" ? '' is recommended!'' : ''被推荐！'') + ''</div>'';'
        $out += '      } else {'
        $out += '        const winChoice = this._decisionCards && this._decisionCards[1] ? this._decisionCards[1].text : (this.currentLang==='"'en'" ? ''Choice B'' : ''抉择二'');'
        $out += '        html += ''<div class=""rps-winner"">'' + (this.currentLang==='"'en'" ? ''Computer wins! '' : ''电脑赢了！'') + winChoice + (this.currentLang==='"'en'" ? '' is recommended!'' : ''被推荐！'') + ''</div>'';'
        $out += '      }'
        $out += '      resultDiv.innerHTML = html;'
        $out += '      resultDiv.classList.remove('"hidden'");'
        $out += '    }'
        $out += ''
        $out += '    playDice(userHighLow) {'
        $out += '      const dice = Math.floor(Math.random() * 6) + 1;'
        $out += '      const isHigh = dice >= 4;'
        $out += '      const userWins = (userHighLow && isHigh) || (!userHighLow && !isHigh);'
        $out += '      const diceEmojis = [''\u2680'', ''\u2681'', ''\u2682'', ''\u2683'', ''\u2684'', ''\u2685''];'
        $out += '      const resultDiv = document.getElementById('"decision-dice-result'");'
        $out += '      if (!resultDiv) return;'
        $out += '      let html = ''"";'
        $out += '      html += ''<div class=""dice-emoji"">'' + diceEmojis[dice-1] + ''</div>'';'
        $out += '      html += ''<div>'' + (this.currentLang==='"'en'" ? ''Dice: '' : ''骰子点数：'') + dice + ''</div>'';'
        $out += '      if (userWins) {'
        $out += '        const winChoice = this._decisionCards && this._decisionCards[0] ? this._decisionCards[0].text : (this.currentLang==='"'en'" ? ''Choice A'' : ''抉择一'');'
        $out += '        html += ''<div class=""dice-outcome"">'' + (this.currentLang==='"'en'" ? ''You win! '' : ''你赢了！'') + winChoice + (this.currentLang==='"'en'" ? '' is recommended!'' : ''被推荐！'') + ''</div>'';'
        $out += '      } else {'
        $out += '        const winChoice = this._decisionCards && this._decisionCards[1] ? this._decisionCards[1].text : (this.currentLang==='"'en'" ? ''Choice B'' : ''抉择二'');'
        $out += '        html += ''<div class=""dice-outcome"">'' + (this.currentLang==='"'en'" ? ''You lose! '' : ''你输了！'') + winChoice + (this.currentLang==='"'en'" ? '' is recommended!'' : ''被推荐！'') + ''</div>'';'
        $out += '      }'
        $out += '      resultDiv.innerHTML = html;'
        $out += '      resultDiv.classList.remove('"hidden'");'
        $out += '    }'
        $inserted = $true
    }
    $out += $line
    $i++
}
Set-Content $path -Value $out -Encoding UTF8
Write-Host "Done. Inserted: $inserted"
