/**
 * 塔罗牌扩展 - 常量定义
 * 包含牌阵配置、国际化字典、运势配置等
 */

// ============ 基础常量 ============
const SUPPORTED_LANGS = ['zh', 'en'];

const DECK_NAMES = {
  hp: '魔法主题',
  rider: '伟特塔罗',
  marseille: '马赛塔罗',
  thoth: '托特塔罗',
  angel: '天使塔罗'
};

// ============ 牌阵配置 ============
const SPREADS = {
  single: {
    name: '单牌占卜',
    nameEn: 'Single Card',
    positions: ['今日指引'],
    positionsEn: ['Daily Guidance'],
    positionMeanings: ['一张牌概括当前能量状态，适合快速提问或每日指引。正位通常表示顺利，逆位提示需要注意的方向。'],
    positionMeaningsEn: ['One card summarizes the current energy state. Good for quick questions or daily guidance. Upright suggests smoothness; reversed indicates areas to watch.'],
    category: 'simple', difficulty: 'easy', recommended: true, loadingText: '正在抽取今日指引...',
    loadingTextEn: 'Drawing your daily guidance...',
    usage: '适合每日抽一张牌作为当日指引，或针对一个具体问题寻求答案。',
    usageEn: 'Suitable for drawing one card daily as guidance, or for a specific question.'
  },
  three: {
    name: '三牌占卜',
    nameEn: 'Three Card Spread',
    positions: ['过去', '现在', '未来'],
    positionsEn: ['Past', 'Present', 'Future'],
    positionMeanings: [
      '过去：影响当前情况的历史因素或已发生的事件。',
      '现在：当前的核心状况、你的状态和正在发生的事。',
      '未来：基于当前趋势可能的发展方向，并非注定不变。'
    ],
    positionMeaningsEn: [
      'Past: Historical factors or events that influence the current situation.',
      'Present: The core situation, your state, and what is happening now.',
      'Future: Possible development direction based on current trends; not set in stone.'
    ],
    category: 'simple', difficulty: 'easy', recommended: true, loadingText: '正在展开三张牌...',
    loadingTextEn: 'Laying out three cards...',
    usage: '最经典的牌阵，适合大多数问题，时间线清晰，解读直观。',
    usageEn: 'The most classic spread, suitable for most questions. Clear timeline, intuitive reading.'
  },
  celtic: {
    name: '凯尔特十字',
    nameEn: 'Celtic Cross',
    positions: ['当前情况', '挑战/障碍', '过去基础', '近期过去', '可能未来', '近期未来', '你的态度', '外部影响', '希望与恐惧', '最终结果'],
    positionsEn: ['Current Situation', 'Challenge', 'Past', 'Future', 'Above', 'Below', 'Advice', 'External', 'Hopes/Fears', 'Outcome'],
    positionMeanings: [
      '当前情况：你目前所处的境况和核心问题。',
      '挑战/障碍：当前面临的主要困难或需要克服的挑战。',
      '过去基础：形成当前状况的过去原因和根基。',
      '近期过去：最近发生并仍在影响你的事情。',
      '可能未来：未来可能发展的方向（不一定发生）。',
      '近期未来：短期内即将发生的事。',
      '你的态度：你内心对这个问题的真实态度和感受。',
      '外部影响：来自外界的人、事、物对问题的影响。',
      '希望与恐惧：你内心深处的期望和担忧。',
      '最终结果：综合所有因素后最可能的结果。'
    ],
    positionMeaningsEn: [
      'Current Situation: The situation you are currently in and the core issue.',
      'Challenge: The main difficulty or challenge you are currently facing.',
      'Past: Past reasons and foundations that formed the current situation.',
      'Future: Recent past events that still influence you.',
      'Above: Possible future development direction (not guaranteed to happen).',
      'Below: Things that will happen in the near future.',
      'Advice: Your true attitude and feelings toward this issue.',
      'External: Influence from external people, events, or things on the issue.',
      'Hopes/Fears: Expectations and worries deep in your heart.',
      'Outcome: The most likely result after integrating all factors.'
    ],
    category: 'advanced', difficulty: 'hard', recommended: false, loadingText: '正在展开凯尔特十字...',
    loadingTextEn: 'Unfolding the Celtic Cross...',
    usage: '适合重要且复杂的问题，需要全面深入分析时使用。建议有一定塔罗基础后再尝试。',
    usageEn: 'Suitable for important and complex questions requiring comprehensive analysis. Recommended after gaining some Tarot foundation.'
  },
  relation: {
    name: '关系牌阵',
    nameEn: 'Relationship Spread',
    positions: ['你', '对方', '你的态度', '对方的态度', '当前关系', '发展方向'],
    positionsEn: ['You', 'Partner', 'Your Attitude', 'Their Attitude', 'Current Relationship', 'Direction'],
    positionMeanings: [
      '你：你在这段关系中的状态、能量和角色。',
      '对方：对方在这段关系中的状态、能量和角色。',
      '你的态度：你对这段关系的真实感受和态度。',
      '对方的态度：对方对这段关系的真实感受和态度。',
      '当前关系：你们之间目前的关系状态和互动模式。',
      '发展方向：这段关系未来的可能走向。'
    ],
    positionMeaningsEn: [
      'You: Your state, energy, and role in this relationship.',
      'Partner: The other person\'s state, energy, and role in this relationship.',
      'Your Attitude: Your true feelings and attitude toward this relationship.',
      'Their Attitude: The other person\'s true feelings and attitude toward this relationship.',
      'Current Relationship: The current relationship status and interaction pattern between you.',
      'Direction: The possible future direction of this relationship.'
    ],
    category: 'relationship', difficulty: 'medium', recommended: true, loadingText: '正在解读关系牌阵...',
    loadingTextEn: 'Reading the relationship spread...',
    usage: '适合分析任何人际关系，包括爱情、友情、亲子关系、职场关系等。',
    usageEn: 'Suitable for analyzing any interpersonal relationship, including romance, friendship, parenting, workplace relationships, etc.'
  },
  choice: {
    name: '二选一牌阵',
    nameEn: 'Choice Spread',
    positions: ['选项A', '选项B', 'A的可能结果', 'B的可能结果', '建议/提醒'],
    positionsEn: ['Option A', 'Option B', 'Outcome A', 'Outcome B', 'Advice'],
    positionMeanings: [
      '选项A：第一个选项的现状和本质。',
      '选项B：第二个选项的现状和本质。',
      'A的可能结果：如果选择A，可能带来的结果。',
      'B的可能结果：如果选择B，可能带来的结果。',
      '建议/提醒：塔罗对你的建议，以及需要特别注意的事项。'
    ],
    positionMeaningsEn: [
      'Option A: The current status and nature of the first option.',
      'Option B: The current status and nature of the second option.',
      'Outcome A: The possible result if you choose A.',
      'Outcome B: The possible result if you choose B.',
      'Advice: The Tarot\'s advice for you, and points to pay special attention to.'
    ],
    category: 'decision', difficulty: 'medium', recommended: false, loadingText: '正在分析两个选项...',
    loadingTextEn: 'Analyzing the two options...',
    usage: '当你在两个选项中犹豫不决时使用，帮助看清每个选项的利弊和可能结果。',
    usageEn: 'Use when you are hesitating between two options. Helps clarify the pros and cons and possible outcomes of each option.'
  },
  five: {
    name: '五张牌阵',
    nameEn: 'Five Card Spread',
    positions: ['问题核心', '面临的障碍', '潜意识/隐藏因素', '建议的行动', '可能的结果'],
    positionsEn: ['Problem', 'Obstacle', 'Subconscious', 'Suggested Action', 'Possible Outcome'],
    positionMeanings: [
      '问题核心：问题的本质和最关键的因素。',
      '面临的障碍：阻碍问题解决的主要困难和挑战。',
      '潜意识/隐藏因素：你自己可能未察觉的动机、情感或隐藏的影响因素。',
      '建议的行动：塔罗建议你采取的行动方向。',
      '可能的结果：如果按照建议行动，可能得到的结果。'
    ],
    positionMeaningsEn: [
      'Problem: The essence of the problem and the most critical factor.',
      'Obstacle: The main difficulty or challenge that hinders problem-solving.',
      'Subconscious: Motivations, emotions, or hidden influencing factors you may not be aware of.',
      'Suggested Action: The action direction the Tarot suggests you take.',
      'Possible Outcome: The possible result if you act on the suggestion.'
    ],
    category: 'general', difficulty: 'medium', recommended: false, loadingText: '正在展开五张牌阵...',
    loadingTextEn: 'Unfolding the five-card spread...',
    usage: '适合分析任何类型的问题，从问题核心到解决方案，层层递进。',
    usageEn: 'Suitable for analyzing any type of problem, from the core issue to the solution, layer by layer.'
  },
  horseshoe: {
    name: '马蹄铁牌阵',
    nameEn: 'Horseshoe Spread',
    positions: ['过去的影响', '现在的情况', '隐藏的因素', '面临的挑战', '外部影响', '希望与恐惧', '最终结果'],
    positionsEn: ['Past Influence', 'Current', 'Hidden Factor', 'Challenge', 'External', 'Hopes/Fears', 'Outcome'],
    positionMeanings: [
      '过去的影响：过去事件对当前情况的持续影响。',
      '现在的情况：当前问题的实际状况。',
      '隐藏的因素：未被发现或未被重视的重要因素。',
      '面临的挑战：需要面对和克服的困难。',
      '外部影响：环境、他人或不可控因素对问题的影响。',
      '希望与恐惧：内心深处的期望与担忧，可能影响决策。',
      '最终结果：综合所有因素后，最有可能发生的结果。'
    ],
    positionMeaningsEn: [
      'Past Influence: The lasting impact of past events on the current situation.',
      'Current: The actual status of the current problem.',
      'Hidden Factor: Important factors that have not been discovered or valued.',
      'Challenge: Difficulties that need to be faced and overcome.',
      'External: Influence of environment, others, or uncontrollable factors on the problem.',
      'Hopes/Fears: Deep expectations and worries that may affect decision-making.',
      'Outcome: The most likely result after integrating all factors.'
    ],
    category: 'general', difficulty: 'medium', recommended: false, loadingText: '正在展开马蹄铁牌阵...',
    loadingTextEn: 'Unfolding the Horseshoe spread...',
    usage: '适合全面了解一个情况的各个层面，时间跨度从过去到未来。',
    usageEn: 'Suitable for comprehensively understanding all aspects of a situation, spanning from past to future.'
  },
  career: {
    name: '事业牌阵',
    nameEn: 'Career Spread',
    positions: ['当前状况', '面临的挑战', '你的优势', '建议的行动', '未来发展'],
    positionsEn: ['Current', 'Challenge', 'Strengths', 'Action', 'Future'],
    positionMeanings: [
      '当前状况：你在事业/学业方面的现状。',
      '面临的挑战：工作中遇到的困难或需要克服的障碍。',
      '你的优势：你拥有的能力、资源或有利条件。',
      '建议的行动：塔罗建议你在事业/学业上采取的行动。',
      '未来发展：基于当前情况，事业/学业的可能发展方向。'
    ],
    positionMeaningsEn: [
      'Current: Your current status in career/studies.',
      'Challenge: Difficulties encountered at work or obstacles to overcome.',
      'Strengths: Your abilities, resources, or favorable conditions.',
      'Action: Actions the Tarot suggests you take in career/studies.',
      'Future: Possible development direction of career/studies based on the current situation.'
    ],
    category: 'career', difficulty: 'medium', recommended: false, loadingText: '正在展开事业牌阵...',
    loadingTextEn: 'Unfolding the Career spread...',
    usage: '适合分析工作、学业、职业发展相关的问题，帮助做出更明智的职业决策。',
    usageEn: 'Suitable for analyzing work, study, and career development related questions. Helps make wiser career decisions.'
  },
  timeflow: {
    name: '时间之流',
    nameEn: 'Time Flow Spread',
    positions: ['过去', '现在', '未来', '深层原因', '可能的结果'],
    positionsEn: ['Past', 'Present', 'Future', 'Root Cause', 'Possible Outcome'],
    positionMeanings: [
      '过去：影响当前情况的历史因素和已发生的事件。',
      '现在：当前的核心状况和你的真实状态。',
      '未来：基于当前趋势最可能的发展方向。',
      '深层原因：潜藏在问题背后的根本动因。',
      '可能的结果：综合所有因素后最终可能呈现的状态。'
    ],
    positionMeaningsEn: [
      'Past: Historical factors and events that influenced the current situation.',
      'Present: The core situation and your true state at present.',
      'Future: The most likely development direction based on current trends.',
      'Root Cause: The root cause hidden behind the problem.',
      'Possible Outcome: The state that may eventually appear after integrating all factors.'
    ],
    category: 'general', difficulty: 'medium', recommended: false, loadingText: '正在展开时间之流...',
    loadingTextEn: 'Unfolding the Time Flow spread...',
    usage: '在时间维度上全面分析问题，适合想要看清事情来龙去脉的情况。',
    usageEn: 'Comprehensively analyze problems across the time dimension. Suitable for situations where you want to see the whole story.'
  },
  action: {
    name: '问题行动结果',
    nameEn: 'Problem-Action-Result',
    positions: ['问题核心', '建议行动', '可能结果'],
    positionsEn: ['Problem', 'Suggested Action', 'Possible Outcome'],
    positionMeanings: [
      '问题核心：你最关心的核心问题或担忧。',
      '建议行动：塔罗建议你采取的具体行动方向。',
      '可能结果：如果按照建议行动，最可能得到的结果。'
    ],
    positionMeaningsEn: [
      'Problem: The core problem or worry you care about most.',
      'Suggested Action: The specific action direction the Tarot suggests you take.',
      'Possible Outcome: The most likely result if you act on the suggestion.'
    ],
    category: 'decision', difficulty: 'easy', recommended: true, loadingText: '正在展开问题行动结果...',
    loadingTextEn: 'Analyzing Problem-Action-Result...',
    usage: '简洁明了的三位牌阵，适合快速决策和明确行动方向。',
    usageEn: 'A concise three-card spread, suitable for quick decision-making and clarifying action directions.'
  },
  mind: {
    name: '心灵牌阵',
    nameEn: 'Mind Spread',
    positions: ['意识', '潜意识', '理想', '现实', '建议'],
    positionsEn: ['Conscious', 'Subconscious', 'Ideal', 'Reality', 'Advice'],
    positionMeanings: [
      '意识：你清醒时对自己和问题的认知。',
      '潜意识：内心深处隐藏的动机、恐惧或渴望。',
      '理想：你内心真正渴望达到的状态或结果。',
      '现实：客观现实和实际的限制条件。',
      '建议：综合意识与潜意识、理想与现实后的最佳建议。'
    ],
    positionMeaningsEn: [
      'Conscious: Your awareness of yourself and the problem when awake.',
      'Subconscious: Hidden motivations, fears, or desires deep in your heart.',
      'Ideal: The state or result you truly desire deep in your heart.',
      'Reality: Objective reality and actual limiting conditions.',
      'Advice: The best advice after integrating conscious and subconscious, ideal and reality.'
    ],
    category: 'general', difficulty: 'medium', recommended: false, loadingText: '正在展开心灵牌阵...',
    loadingTextEn: 'Exploring the Mind spread...',
    usage: '适合自我探索和内心成长类问题，帮助看清内心真实想法。',
    usageEn: 'Suitable for self-exploration and inner growth questions. Helps clarify your true inner thoughts.'
  },
  // ============ 新增情感关系牌阵 ============
  love: {
    name: '恋人牌阵',
    nameEn: 'Love Spread',
    positions: ['你', '对方', '你们的关系', '面临的挑战', '周围的影响', '关系的未来', '建议'],
    positionsEn: ['You', 'Partner', 'Your Relationship', 'Challenges', 'External Influence', 'Relationship Future', 'Advice'],
    positionMeanings: [
      '你：你在这段感情中的状态、感受和行为模式。',
      '对方：对方在感情中的真实状态和对你的感受。',
      '你们的关系：这段关系的本质和当前的互动模式。',
      '面临的挑战：这段感情中需要面对和解决的问题。',
      '周围的影响：来自外界（朋友、家人、环境）对这段关系的影响。',
      '关系的未来：基于当前状态，这段关系可能的发展方向。',
      '建议：塔罗对这段感情的建议和指引。'
    ],
    positionMeaningsEn: [
      'You: Your state, feelings, and behavior pattern in this relationship.',
      'Partner: The other person\'s true state in the relationship and feelings toward you.',
      'Your Relationship: The nature of this relationship and the current interaction pattern.',
      'Challenges: Problems that need to be faced and resolved in this relationship.',
      'External Influence: Influence from the outside (friends, family, environment) on this relationship.',
      'Relationship Future: Possible development direction of this relationship based on the current state.',
      'Advice: The Tarot\'s advice and guidance for this relationship.'
    ],
    category: 'relationship', difficulty: 'medium', recommended: true, loadingText: '正在解读恋人牌阵...',
    loadingTextEn: 'Reading the Love spread...',
    usage: '适合正在恋爱或暧昧中的人，全面分析两人关系的各个层面。',
    usageEn: 'Suitable for people who are in love or in an ambiguous stage. Comprehensively analyzes all aspects of the two-person relationship.'
  },
  broken: {
    name: '复合牌阵',
    nameEn: 'Reunion Spread',
    positions: ['问题根源', '对方的想法', '你的状态', '障碍', '复合的可能性', '建议'],
    positionsEn: ['Root Cause', 'Their Thoughts', 'Your State', 'Obstacles', 'Reunion Possibility', 'Advice'],
    positionMeanings: [
      '问题根源：导致分手或关系破裂的核心原因。',
      '对方的想法：对方目前对你的真实想法和感受。',
      '你的状态：你在这段关系中的真实状态和需要成长的地方。',
      '障碍：复合道路上需要克服的困难和阻碍。',
      '复合的可能性：基于双方状态，复合的可能性有多大。',
      '建议：塔罗对你是否应该复合、以及如何行动的建议。'
    ],
    positionMeaningsEn: [
      'Root Cause: The core reason that led to the breakup or relationship rupture.',
      'Their Thoughts: The other person\'s true thoughts and feelings about you at present.',
      'Your State: Your true state in this relationship and areas where you need to grow.',
      'Obstacles: Difficulties and barriers that need to be overcome on the road to getting back together.',
      'Reunion Possibility: How likely is a reunion based on both parties\' status.',
      'Advice: The Tarot\'s advice on whether you should get back together and how to act.'
    ],
    category: 'relationship', difficulty: 'medium', recommended: false, loadingText: '正在解读复合牌阵...',
    loadingTextEn: 'Reading the Reunion spread...',
    usage: '适合分手后想了解是否还有复合可能，或想看清分手原因时使用。',
    usageEn: 'Suitable for use after a breakup when you want to know if there is still a possibility of getting back together, or want to see the reason for the breakup.'
  },
  // ============ 新增决策分析牌阵 ============
  yesno: {
    name: '是否牌阵',
    nameEn: 'Yes/No Spread',
    positions: ['支持因素', '反对因素', '综合建议'],
    positionsEn: ['Supporting Factors', 'Opposing Factors', 'Comprehensive Advice'],
    positionMeanings: [
      '支持因素：支持你做这件事的理由和有利条件。',
      '反对因素：反对你做这件事的理由和需要注意的风险。',
      '综合建议：综合两方面因素后，塔罗给出的建议（正位偏向"是"，逆位偏向"否"）。'
    ],
    positionMeaningsEn: [
      'Supporting Factors: Reasons and favorable conditions that support you doing this.',
      'Opposing Factors: Reasons against doing this and risks that need attention.',
      'Comprehensive Advice: The Tarot\'s advice after integrating both factors (upright leans toward "yes", reversed leans toward "no").'
    ],
    category: 'decision', difficulty: 'easy', recommended: false, loadingText: '正在解读是否牌阵...',
    loadingTextEn: 'Analyzing Yes/No spread...',
    usage: '当你对一个决定犹豫不决，只想得到一个"是"或"否"的指引时使用。',
    usageEn: 'Use when you are hesitating about a decision and just want a "yes" or "no" guidance.'
  },
  // ============ 新增事业学业牌阵 ============
  jobchange: {
    name: '换工作牌阵',
    nameEn: 'Job Change Spread',
    positions: ['现状', '想离职的原因', '新机会的本质', '风险与挑战', '建议'],
    positionsEn: ['Current Situation', 'Reason for Leaving', 'Nature of New Opportunity', 'Risks & Challenges', 'Advice'],
    positionMeanings: [
      '现状：你目前的工作状态和感受。',
      '想离职的原因：促使你想离开当前工作的核心因素。',
      '新机会的本质：新工作或新机会的真实情况。',
      '风险与挑战：换工作可能面临的困难和挑战。',
      '建议：塔罗对你是否应该换工作、以及如何选择的建议。'
    ],
    positionMeaningsEn: [
      'Current Situation: Your current work status and feelings.',
      'Reason for Leaving: The core factor that prompts you to want to leave your current job.',
      'Nature of New Opportunity: The true situation of the new job or new opportunity.',
      'Risks & Challenges: Difficulties and challenges you may face when changing jobs.',
      'Advice: The Tarot\'s advice on whether you should change jobs and how to choose.'
    ],
    category: 'career', difficulty: 'medium', recommended: false, loadingText: '正在解读换工作牌阵...',
    loadingTextEn: 'Analyzing Job Change spread...',
    usage: '适合正在考虑换工作、转行或跳槽的人，帮助做出更明智的职业决策。',
    usageEn: 'Suitable for people who are considering changing jobs, switching careers, or job hopping. Helps make wiser career decisions.'
  },
  // ============ 新增自我成长牌阵 ============
  shadow: {
    name: '阴影牌阵',
    nameEn: 'Shadow Spread',
    positions: ['意识自我', '阴影自我', '需要释放的', '成长方向', '建议'],
    positionsEn: ['Conscious Self', 'Shadow Self', 'What to Release', 'Growth Direction', 'Advice'],
    positionMeanings: [
      '意识自我：你平时展现给外界的自我形象。',
      '阴影自我：你不愿面对或否认的性格面向，可能正是你需要整合的部分。',
      '需要释放的：阻碍你成长的旧模式、执念或创伤。',
      '成长方向：你接下来应该专注的成长方向。',
      '建议：塔罗对你自我整合和成长的建议。'
    ],
    positionMeaningsEn: [
      'Conscious Self: The self-image you usually present to the outside world.',
      'Shadow Self: The personality aspects you are unwilling to face or deny, which may be exactly the parts you need to integrate.',
      'What to Release: Old patterns, obsessions, or traumas that hinder your growth.',
      'Growth Direction: The growth direction you should focus on next.',
      'Advice: The Tarot\'s advice for your self-integration and growth.'
    ],
    category: 'self', difficulty: 'medium', recommended: false, loadingText: '正在展开阴影牌阵...',
    loadingTextEn: 'Unfolding the Shadow spread...',
    usage: '适合想要深入了解自己、进行心理成长或整合阴影面的人。',
    usageEn: 'Suitable for people who want to deeply understand themselves, engage in psychological growth, or integrate their shadow side.'
  },
  year: {
    name: '年运牌阵',
    nameEn: 'Yearly Spread',
    positions: ['整体运势', '事业/学业', '感情/人际关系', '财富/物质', '健康/身心', '需要注意的', '年度建议'],
    positionsEn: ['Overall Fortune', 'Career/Study', 'Love/Relationships', 'Wealth/Material', 'Health/Wellness', 'Things to Note', 'Annual Advice'],
    positionMeanings: [
      '整体运势：这一年的整体能量和主题。',
      '事业/学业：这一年事业或学业方面的发展。',
      '感情/人际关系：这一年感情和人际方面的情况。',
      '财富/物质：这一年财务和物质生活方面的状况。',
      '健康/身心：这一年健康和身心状态需要注意的地方。',
      '需要注意的：这一年需要特别留意的人、事、物。',
      '年度建议：塔罗对这一年整体行动的建议。'
    ],
    positionMeaningsEn: [
      'Overall Fortune: The overall energy and theme of this year.',
      'Career/Study: Developments in career or studies this year.',
      'Love/Relationships: Situation in love and interpersonal relationships this year.',
      'Wealth/Material: Financial and material life status this year.',
      'Health/Wellness: Areas of health and physical/mental state that need attention this year.',
      'Things to Note: People, events, or things that need special attention this year.',
      'Annual Advice: The Tarot\'s advice for overall actions this year.'
    ],
    category: 'self', difficulty: 'hard', recommended: false, loadingText: '正在展开年运牌阵...',
    loadingTextEn: 'Unfolding the Yearly spread...',
    usage: '适合新年或生日时抽取，了解一整年的运势走向和各领域的发展。',
    usageEn: 'Suitable for drawing at New Year or birthday to understand the fortune trend and development in various fields for the whole year.'
  },
  // ============ 新增决策分析牌阵 ============
  proscons: {
    name: '利弊分析',
    nameEn: 'Pros & Cons Spread',
    positions: ['利（支持的理由）', '弊（反对的理由）', '隐藏的因素', '建议'],
    positionsEn: ['Pros (Supporting Reasons)', 'Cons (Opposing Reasons)', 'Hidden Factor', 'Advice'],
    positionMeanings: [
      '利（支持的理由）：支持你做这件事的理由和有利条件。',
      '弊（反对的理由）：反对你做这件事的理由和需要注意的风险。',
      '隐藏的因素：未被考虑的隐藏因素或潜在影响。',
      '建议：综合各方面因素后，塔罗给出的建议（正位偏向支持，逆位偏向谨慎）。'
    ],
    positionMeaningsEn: [
      'Pros: Reasons and favorable conditions that support you doing this.',
      'Cons: Reasons against doing this and risks that need attention.',
      'Hidden Factor: Hidden factors or potential influences not yet considered.',
      'Advice: The Tarot\'s advice after integrating all factors (upright leans toward support, reversed leans toward caution).'
    ],
    category: 'decision', difficulty: 'easy', recommended: false, loadingText: '正在分析利弊...',
    loadingTextEn: 'Analyzing pros and cons...',
    usage: '适合需要对某件事做简单的利弊分析时使用，比是否牌阵更细致，比二选一牌阵更聚焦单一问题。',
    usageEn: 'Suitable for when you need to do a simple pros and cons analysis of something. More detailed than the Yes/No spread, more focused on a single issue than the Choice spread.'
  },
  // ============ 新增自我成长牌阵 ============
  lifepurpose: {
    name: '人生使命牌阵',
    nameEn: 'Life Purpose Spread',
    positions: ['你的核心天赋', '你的人生课题', '过去的制约/限制', '当前的机会', '需要释放的信念', '你的使命方向', '可能的阻碍', '建议'],
    positionsEn: ['Your Core Talent', 'Your Life Lesson', 'Past Conditioning', 'Current Opportunity', 'Beliefs to Release', 'Your Mission Direction', 'Possible Obstacles', 'Advice'],
    positionMeanings: [
      '你的核心天赋：你天生具备的天赋、才能或独特优势。',
      '你的人生课题：你此生需要学习的核心课题或需要克服的挑战。',
      '过去的制约/限制：来自过去（童年、成长环境、过往经历）的限制性信念或模式。',
      '当前的机会：此刻出现的、与你的使命相关的机会或召唤。',
      '需要释放的信念：阻碍你走向使命的旧有信念、恐惧或执念。',
      '你的使命方向：你的人生方向和使命所在，塔罗给出的指引。',
      '可能的阻碍：在实现使命道路上可能遇到的内在或外在阻碍。',
      '建议：塔罗对你如何走向人生使命、活出真实自我的建议。'
    ],
    positionMeaningsEn: [
      'Your Core Talent: The natural talents, abilities, or unique advantages you possess.',
      'Your Life Lesson: The core lesson you need to learn in this life or the challenge you need to overcome.',
      'Past Conditioning: Limiting beliefs or patterns from the past (childhood, upbringing, past experiences).',
      'Current Opportunity: Opportunities or calls appearing now that are related to your mission.',
      'Beliefs to Release: Old beliefs, fears, or obsessions that hinder you from moving toward your mission.',
      'Your Mission Direction: Your life direction and mission, the guidance given by the Tarot.',
      'Possible Obstacles: Inner or outer obstacles you may encounter on the path to fulfilling your mission.',
      'Advice: The Tarot\'s advice on how to move toward your life purpose and live as your true self.'
    ],
    category: 'self', difficulty: 'hard', recommended: false, loadingText: '正在展开人生使命牌阵...',
    loadingTextEn: 'Unfolding the Life Purpose spread...',
    usage: '适合在人生转折点、迷茫期或想要寻找人生意义和方向时使用，帮助探索天命与使命。',
    usageEn: 'Suitable for use at life turning points, confused periods, or when wanting to find the meaning and direction of life. Helps explore destiny and mission.'
  }
};

// ============ 运势相关常量 ============
const FORTUNE_CATEGORIES = ['事业', '财运', '感情', '健康', '学习', '社交'];

const FORTUNE_LEVELS = [
  { text: '大吉', score: 95, color: '#FFD700', desc: '今日运势极佳，万事顺遂，适合推进重要计划。' },
  { text: '吉', score: 80, color: '#4CAF50', desc: '今日运势良好，积极行动会有不错的收获。' },
  { text: '中吉', score: 70, color: '#2196F3', desc: '今日运势平稳，按部就班即可，宜守不宜攻。' },
  { text: '小吉', score: 60, color: '#9C27B0', desc: '今日运势尚可，小事顺利但大事需谨慎。' },
  { text: '平', score: 50, color: '#607D8B', desc: '今日运势平淡，适合休整和规划，不宜冒进。' },
  { text: '小凶', score: 40, color: '#FF9800', desc: '今日需谨慎行事，避免重要决策和大额支出。' },
  { text: '凶', score: 25, color: '#F44336', desc: '今日运势低迷，宜静不宜动，注意安全和健康。' }
];

const LUCKY_COLORS = [
  { name: '金色', hex: '#FFD700' },
  { name: '紫色', hex: '#9C27B0' },
  { name: '蓝色', hex: '#2196F3' },
  { name: '绿色', hex: '#4CAF50' },
  { name: '红色', hex: '#F44336' },
  { name: '橙色', hex: '#FF9800' },
  { name: '青色', hex: '#00BCD4' },
  { name: '粉色', hex: '#E91E63' },
  { name: '白色', hex: '#FFFFFF' },
  { name: '银色', hex: '#9E9E9E' }
];

const LUCKY_ADVICE = {
  '大吉': ['宜：签约、表白、投资、出行', '忌：无所事事、浪费机会'],
  '吉': ['宜：学习、社交、购物、运动', '忌：冲动决策、与人争执'],
  '中吉': ['宜：整理、规划、沟通、休息', '忌：冒险投资、重大变动'],
  '小吉': ['宜：阅读、散步、做家务、听音乐', '忌：熬夜、过量饮食'],
  '平': ['宜：冥想、复盘、维护关系、储蓄', '忌：借贷、跳槽、远行'],
  '小凶': ['宜：独处、学习、做计划', '忌：签约、手术、争吵'],
  '凶': ['宜：静养、念佛、整理旧物', '忌：投资、远行、重大决定']
};

// 大阿尔卡那专属图标（id 0~21 对应 22 张牌）
const MAJOR_ARCANA_ICONS = [
  '🃏', '🎩', '📖', '🌹', '👑', '✝️', '💕', '🏇', '💪', '🔍',
  '🎡', '⚖️', '🔄', '💀', '🍶', '😈', '⚡', '⭐', '🌕', '☀️',
  '🎺', '🌐'
];

// ============ 国际化字典 ============
const I18N = {
  zh: {
    welcome_title: '魔法塔罗牌',
    welcome_subtitle: '探索魔法世界的命运指引',
    label_deck: '选择牌组：',
    deck_magic: '魔法主题',
    deck_rider: '伟特塔罗',
    deck_marseille: '马赛塔罗',
    deck_thoth: '托特塔罗',
    deck_angel: '天使塔罗',
    label_lang: '语言：',
    inst_start: '选择牌阵开始你的魔法之旅',
    inst_click: '点击卡牌查看正/逆位解读',
    inst_reshuffle: '随时可以重新洗牌占卜',
    btn_history: '查看历史记录',
    btn_favorites: '收藏夹',
    btn_daily_fortune: '今日运势',
    fortune_panel_title: '✨ 今日运势',
    fortune_loading: '正在解读今日运势...',
    cat_beginner: '⭐ 新手推荐',
    cat_relationship: '💕 情感关系',
    cat_decision: '💡 决策分析',
    cat_general: '🔮 通用深入',
    cat_career: '💼 事业学业',
    badge_recommended: '★ 推荐',
    spread_single_name: '单牌阵',
    spread_single_desc: '1张牌 · 每日指引 / 快速决策',
    spread_three_name: '三牌阵',
    spread_three_desc: '3张牌 · 过去·现在·未来',
    spread_celtic_name: '凯尔特十字',
    spread_celtic_desc: '10张牌 · 全面深入解读',
    spread_relation_name: '关系牌阵',
    spread_relation_desc: '6张牌 · 人际关系 / 感情',
    spread_choice_name: '二选一牌阵',
    spread_choice_desc: '5张牌 · 面临两个选择时',
    spread_five_name: '五张牌阵',
    spread_five_desc: '5张牌 · 通用问题深入分析',
    spread_horseshoe_name: '马蹄铁牌阵',
    spread_horseshoe_desc: '7张牌 · 全面生活指引',
    spread_career_name: '事业牌阵',
    spread_career_desc: '5张牌 · 工作/学业决策',
    spread_timeflow_name: '时间之流',
    spread_timeflow_desc: '5张牌 · 时间维度全面分析',
    spread_action_name: '问题行动结果',
    spread_action_desc: '3张牌 · 快速决策与行动指引',
    spread_mind_name: '心灵牌阵',
    spread_mind_desc: '5张牌 · 自我探索与内心成长',
    placeholder_click_card: '点击上方卡牌查看详细解读',
    comprehensive_reading: '综合解读',
    btn_expand: '展开',
    btn_collapse: '收起',
    btn_back: '返回',
    btn_reshuffle: '重新占卜',
    btn_share: '分享结果',
    btn_copy_result: '复制结果',
    history_title: '历史记录',
    history_hint: '查看过往的占卜记录',
    history_detail_title: '占卜详情',
    btn_back_to_list: '返回列表',
    btn_clear_history: '清空记录',
    history_empty: '暂无历史记录',
    fav_empty: '暂无收藏，点击卡牌预览中的 ☆ 可收藏喜欢的卡牌。',
    alert_copy_success: '占卜结果已复制到剪贴板！',
    alert_copy_fail: '复制失败，请手动复制结果',
    alert_draw_error: '抽牌出错: ',
    fav_title: '收藏夹',
    fav_hint: '你收藏的卡牌',
    loading_shuffle: '正在洗牌...',
    single_tip: '适合每日快速占卜，一张牌给出今日指引方向。',
    three_tip: '最经典的牌阵，分别解读过去的影响、现在的状态和未来的发展。',
    celtic_tip: '最全面的牌阵，适合重要问题深入解读，共10张牌覆盖问题各个层面。',
    relation_tip: '专门用于人际关系和感情问题，帮你理解双方状态与关系走向。',
    choice_tip: '当你在两个选项中犹豫不决时使用，帮助看清每个选项的可能结果。',
    five_tip: '通用深入分析牌阵，从问题核心到最终结果，层层递进。',
    horseshoe_tip: '马蹄铁形牌阵，覆盖过去到未来的完整时间线，适合全面了解局势。',
    career_tip: '专注事业与学业决策，从当前状况到未来发展，给出实用建议。',
    timeflow_tip: '从时间维度全面分析问题，看清事情的来龙去脉与可能走向。',
    action_tip: '简洁明了的三位牌阵，快速明确问题核心与最佳行动方向。',
    mind_tip: '适合自我探索与内心成长，帮助看清意识与潜意识、理想与现实。',
    fortune_overall: '★ 综合运势',
    fortune_dimensions: '➡ 各维度评分',
    fortune_lucky_info: '💫 幸运信息',
    fortune_lucky_color: '幸运颜色',
    fortune_lucky_number: '幸运数字',
    fortune_lucky_direction: '幸运方位',
    fortune_dos_donts: '☯ 今日宜忌',
    fortune_tips: '💬 温馨提示',
    fortune_score_unit: '分',
    fortune_suitable: '宜：',
    fortune_avoid: '忌：',
    btn_number_gen: '命运数字',
    numgen_title: '命运数字生成器',
    numgen_hint: '让塔罗命运指引为你挑选幸运数字',
    numgen_min: '最小值',
    numgen_max: '最大值',
    numgen_generate: '生成命运数字',
    numgen_regenerate: '重新生成',
    numgen_your_number: '你的命运数字',
    numgen_reading_title: '✨ 塔罗命运指引',
    numgen_error_min: '最小值不能大于最大值',
    numgen_error_range: '请输入有效范围（最大值 - 最小值 ≥ 1）',
    numgen_copy: '复制数字',
    numgen_copy_all: '复制全部',
    numgen_quantity: '生成数量',
    numgen_numbers_label: '你的命运数字',
    numgen_history_title: '历史记录',
    numgen_clear_history: '清空历史',
    numgen_preset_lottery: '六合彩(1-49)',
    numgen_error_quantity: '生成数量不能超过取值范围大小',
    btn_dilemma: '选择困难症',
    dilemma_title: '选择困难症',
    dilemma_hint: '输入两个选项，用猜拳、摇骰子或塔罗帮你做决定',
    dilemma_label_a: '🅰 选项 A',
    dilemma_label_b: '🅱 选项 B',
    dilemma_choose_method: '选择决定方式',
    dilemma_rps: '猜拳决胜',
    dilemma_dice: '摇骰子',
    dilemma_tarot: '塔罗抽牌',
    dilemma_rps_title: '✊ 猜拳决胜',
    dilemma_dice_title: '🎲 摇骰子',
    dilemma_dice_high: '大（4-6）',
    dilemma_dice_low: '小（1-3）',
    dilemma_tarot_reading: '✨ 塔罗命运解读',
    dilemma_redo: '再来一次',
    dilemma_enter_both: '请输入两个选项',
    dilemma_you_chose: '你出了：',
    dilemma_computer_chose: '电脑出了：',
    dilemma_winner_is: '胜出选项：',
    dilemma_dice_point: '骰子点数：',
    dilemma_computer_roll: '电脑摇出：',
    dilemma_you_bet: '你押：',
    dilemma_dice_result_high: '大（4-6）',
    dilemma_dice_result_low: '小（1-3）',
    dilemma_winner_is: '胜出选项：',
    decision_tie: '平局，请再试一次！',
    difficulty_easy: '★☆☆',
    difficulty_medium: '★★☆',
    difficulty_hard: '★★★',
    filter_all: '全部',
    filter_advanced: '复杂',
    filter_favorites: '★ 收藏',
    spread_search_placeholder: '搜索牌阵...',
    cat_self: '🌱 自我成长',
    spread_love_name: '恋人牌阵',
    spread_love_desc: '7张牌 · 恋爱关系全面分析',
    spread_broken_name: '复合牌阵',
    spread_broken_desc: '6张牌 · 分手原因与复合可能',
    spread_yesno_name: '是否牌阵',
    spread_yesno_desc: '3张牌 · 是/否决策指引',
    spread_jobchange_name: '换工作牌阵',
    spread_jobchange_desc: '5张牌 · 跳槽/转行决策',
    spread_shadow_name: '阴影牌阵',
    spread_shadow_desc: '5张牌 · 自我整合与成长',
    spread_year_name: '年运牌阵',
    spread_year_desc: '7张牌 · 全年运势指引',
    love_tip: '适合正在恋爱或暧昧中的人，全面分析两人关系的各个层面。',
    broken_tip: '适合分手后想了解是否还有复合可能，或想看清分手原因时使用。',
    yesno_tip: '当你对一个决定犹豫不决，只想得到一个"是"或"否"的指引时使用。',
    jobchange_tip: '适合正在考虑换工作、转行或跳槽的人，帮助做出更明智的职业决策。',
    shadow_tip: '适合想要深入了解自己、进行心理成长或整合阴影面的人。',
    year_tip: '适合新年或生日时抽取，了解一整年的运势走向和各领域的发展。',
    spread_proscons_name: '利弊分析',
    spread_proscons_desc: '4张牌 · 支持与反对因素分析',
    spread_lifepurpose_name: '人生使命',
    spread_lifepurpose_desc: '8张牌 · 探索天命与人生方向',
    proscons_tip: '适合需要对某件事做简单的利弊分析时使用，比是否牌阵更细致。',
    lifepurpose_tip: '适合在人生转折点、迷茫期或想要寻找人生意义和方向时使用，帮助探索天命与使命。',
    // 牌意
    btn_custom_meaning: '自定义牌意',
    cards_count_label: '张牌',
    // 综合解读标题
    theme_title: '★ 整体主题',
    relation_title: '⚙ 牌面关系分析',
    trend_title: '➡ 运势走向',
    advice_title: '⚡ 行动建议',
    // 整体主题
    theme_intro: '本次{0}抽取了 {1} 张牌，其中正位 {2} 张，逆位 {3} 张。',
    theme_has_majors: '大阿卡那牌出现了 {0} 张（{1}），预示本次问题涉及重要的生命课题或深层转变，值得认真对待。',
    theme_no_majors: '本次抽到的均为小阿卡那牌，问题更偏向日常生活层面的具体事务。',
    theme_dominant: '牌面中「{0}」元素最为突出，',
    theme_wands: '整体能量偏向行动、热情与创造力，是一个需要主动出击的时期。',
    theme_cups: '整体能量偏向情感、直觉与人际关系，需要更多关注内心感受。',
    theme_swords: '整体能量偏向思维、沟通与挑战，需要理性分析和清晰判断。',
    theme_pentacles: '整体能量偏向物质、事业与实际成果，需要脚踏实地的行动。',
    theme_mostly_reversed: '逆位牌占多数，提示当前局面可能存在阻碍、内在抗拒或需要调整方向；建议以更灵活的态度面对变化。',
    theme_mostly_upright: '正位牌占多数，整体能量通畅，当前方向基本正确，保持信心继续推进即可。',
    // 牌面关系分析
    relation_three_past: '过去（{0} {1}）为现在（{2} {3}）埋下了伏笔，而现在的能量将延续至未来（{4} {5}）。',
    relation_three_past_rev_now_up: '逆位的过去牌显示旧有模式正在被化解，现在是一个重新出发的契机。',
    relation_three_past_up_now_rev: '过去的顺利积累未能延续到现在，需要审视哪里出现了偏差。',
    relation_three_now_rev_future_up: '现在的困难是暂时的，未来有逆转向上的趋势，请坚持下去。',
    relation_you: '你（{0} {1}）与对方（{2} {3}）之间存在着明显的能量互动。',
    relation_same_rev: '双方的牌位状态相似，说明你们对这段关系的认知较为一致，但双方都可能带着某些内在抗拒或困惑。',
    relation_same_up: '双方的牌位状态相似，说明你们对这段关系的认知较为一致，这是一段相对和谐、互相理解的关系。',
    relation_diff: '你们的牌位状态不同，可能存在认知差异或不同步的情况，需要更多沟通。',
    relation_choice: '选项A（{0} {1}）与选项B（{2} {3}）呈现出不同的能量走向。建议牌（{4} {5}）为你的决策提供了重要指引，请仔细体悟这张牌的启示。',
    relation_celtic: '十字中心的两张牌——当前情况（{0}）与挑战（{1}）——构成了问题的核心张力。过去的能量（{2}）仍在影响着现在，而最终结果牌（{3}）指明了这段旅程可能的归宿。',
    relation_suite_continue: '「{0}」与「{1}」同为{2}牌组，能量有延续性；',
    relation_rev_to_up: '从「{0}」的逆位转向「{1}」的正位，说明局势正在好转；',
    relation_up_to_rev: '从「{0}」的正位走向「{1}」的逆位，需要警惕潜在风险；',
    relation_smooth: '各张牌位之间的能量流转较为平稳，没有明显的冲突或突变，整体呈现出渐进式的发展轨迹。',
    // 运势走向
    trend_good: '牌面显示整体走势向好——前半段逆位较多，暗示起步或有阻碍；后半段正位增多，预示局面将逐步打开，坚持将有所收获。',
    trend_warning: '需要留意的走势——前半段相对顺利，但后半段逆位增多，提示后续可能出现变数或挑战，宜未雨绸缪、保持警觉。',
    trend_stable: '牌面显示能量相对平稳，没有剧烈的好转或恶化。这是一个沉淀和积累的时期，适合稳扎稳打，不宜冒进也不宜消极。',
    trend_major_turn: '「{0}」的出现预示着重大转折即将到来，请做好迎接变化的心理准备。',
    // 行动建议
    advice_intro: '综合牌面指引，当前最值得采取的态度是：',
    advice_upright: '积极践行「{0}」的正位能量——{1} 在具体行动上，',
    advice_wands: '请主动出击，不要等待机会来找你。',
    advice_cups: '请倾听内心的声音，跟随直觉做出选择。',
    advice_swords: '请理性分析局势，用清晰的思维指导行动。',
    advice_pentacles: '请专注实际步骤，一步一个脚印地推进计划。',
    advice_major: '请思考这张牌所传达的核心讯息，并将其融入你的决策中。',
    advice_reversed: '「{0}」逆位提醒你，{1} 建议先处理内在阻碍，再重新出发。',
    advice_many_reversed: '牌面逆位较多，建议给自己更多耐心和宽容，不要强求立竿见影的结果，允许事物按照自己的节奏展开。'
  },
  en: {
    welcome_title: 'Magic Tarot',
    welcome_subtitle: 'Explore the magical guidance of fate',
    label_deck: 'Deck:',
    deck_magic: 'Magic Theme',
    deck_rider: 'Rider-Waite',
    deck_marseille: 'Marseille',
    deck_thoth: 'Thoth',
    deck_angel: 'Angel',
    label_lang: 'Language:',
    inst_start: 'Choose a spread to begin your magical journey',
    inst_click: 'Tap cards to view upright / reversed meaning',
    inst_reshuffle: 'Reshuffle anytime for a new reading',
    btn_history: 'View History',
    btn_favorites: 'Favorites',
    btn_daily_fortune: 'Daily Fortune',
    fortune_panel_title: '✨ Daily Fortune',
    fortune_loading: 'Reading today\'s fortune...',
    cat_beginner: '⭐ Beginner Recommended',
    cat_relationship: '💕 Love & Relationship',
    cat_decision: '💡 Decision Analysis',
    cat_general: '🔮 General In-depth',
    cat_career: '💼 Career & Study',
    badge_recommended: '★ Recommended',
    spread_single_name: 'Single Card',
    spread_single_desc: '1 card · Daily guidance / Quick decision',
    spread_three_name: 'Three Cards',
    spread_three_desc: '3 cards · Past · Present · Future',
    spread_celtic_name: 'Celtic Cross',
    spread_celtic_desc: '10 cards · Comprehensive in-depth reading',
    spread_relation_name: 'Relationship',
    spread_relation_desc: '6 cards · Interpersonal / Love',
    spread_choice_name: 'Choice Spread',
    spread_choice_desc: '5 cards · When facing two options',
    spread_five_name: 'Five Cards',
    spread_five_desc: '5 cards · General in-depth analysis',
    spread_horseshoe_name: 'Horseshoe',
    spread_horseshoe_desc: '7 cards · Comprehensive life guidance',
    spread_career_name: 'Career Spread',
    spread_career_desc: '5 cards · Work / Study decisions',
    spread_timeflow_name: 'Time Flow',
    spread_timeflow_desc: '5 cards · Past to future analysis',
    spread_action_name: 'Problem-Action-Result',
    spread_action_desc: '3 cards · Quick decision & action guide',
    spread_mind_name: 'Mind Spread',
    spread_mind_desc: '5 cards · Self-exploration & inner growth',
    placeholder_click_card: 'Tap a card above to see detailed meaning',
    comprehensive_reading: 'Comprehensive Reading',
    btn_expand: 'Expand',
    btn_collapse: 'Collapse',
    btn_back: 'Back',
    btn_reshuffle: 'Redraw',
    btn_share: 'Share Result',
    btn_copy_result: 'Copy Result',
    history_title: 'History',
    history_hint: 'View past readings',
    history_detail_title: 'Reading Detail',
    btn_back_to_list: 'Back to List',
    btn_clear_history: 'Clear History',
    history_empty: 'No history yet',
    fav_empty: 'No favorites yet. Click ☆ in card preview to favorite a card.',
    alert_copy_success: 'Reading result copied to clipboard!',
    alert_copy_fail: 'Copy failed, please copy manually.',
    alert_draw_error: 'Card drawing error: ',
    fav_title: 'Favorites',
    fav_hint: 'Your favorite cards',
    loading_shuffle: 'Shuffling...',
    single_tip: 'Quick daily guidance. One card shows your direction for today.',
    three_tip: 'Classic three-card spread: past influence, current state, and future development.',
    celtic_tip: 'Most comprehensive spread with 10 cards covering all aspects of a situation.',
    relation_tip: 'Designed for relationships and emotions. Understand both sides and where the relationship is heading.',
    choice_tip: 'Use when hesitating between two options. Shows possible outcomes for each choice.',
    five_tip: 'General in-depth spread. From core issue to final outcome, layer by layer.',
    horseshoe_tip: 'Horseshoe-shaped spread covering the full timeline from past to future. Great for a complete overview.',
    career_tip: 'Focused on career and study decisions. From current status to future development, with practical advice.',
    timeflow_tip: 'Analyze the problem through time dimensions. See the past, present and future clearly.',
    action_tip: 'Simple three-card spread. Quickly clarify the core issue and best action direction.',
    mind_tip: 'For self-exploration and inner growth. Helps see consciousness, subconscious, ideal and reality.',
    fortune_overall: '★ Overall Fortune',
    fortune_dimensions: '➡ Dimension Scores',
    fortune_lucky_info: '💫 Lucky Info',
    fortune_lucky_color: 'Lucky Color',
    fortune_lucky_number: 'Lucky Number',
    fortune_lucky_direction: 'Lucky Direction',
    fortune_dos_donts: '☯ Dos & Don\'ts',
    fortune_tips: '💬 Daily Tip',
    fortune_score_unit: 'pts',
    fortune_suitable: 'Do: ',
    fortune_avoid: 'Avoid: ',
    btn_number_gen: 'Fate Number',
    numgen_title: 'Fate Number Generator',
    numgen_hint: 'Let tarot fate guide you to your lucky number',
    numgen_min: 'Min',
    numgen_max: 'Max',
    numgen_generate: 'Generate Fate Number',
    numgen_regenerate: 'Regenerate',
    numgen_your_number: 'Your Fate Number',
    numgen_reading_title: '✨ Tarot Fate Guidance',
    numgen_error_min: 'Min cannot be greater than max',
    numgen_error_range: 'Please enter a valid range (max - min ≥ 1)',
    numgen_copy: 'Copy Number',
    numgen_copy_all: 'Copy All',
    numgen_quantity: 'Quantity',
    numgen_numbers_label: 'Your Fate Numbers',
    numgen_error_quantity: 'Quantity cannot exceed the range size',
    btn_dilemma: 'Decision Helper',
    dilemma_title: 'Decision Helper',
    dilemma_hint: 'Enter two options, let Rock-Paper-Scissors, Dice, or Tarot help you decide',
    dilemma_label_a: 'Option A',
    dilemma_label_b: 'Option B',
    dilemma_choose_method: 'Choose a method',
    dilemma_rps: 'Rock Paper Scissors',
    dilemma_dice: 'Roll Dice',
    dilemma_tarot: 'Tarot Draw',
    dilemma_rps_title: '✊ Rock Paper Scissors',
    dilemma_dice_title: '🎲 Roll Dice',
    dilemma_dice_high: 'High (4-6)',
    dilemma_dice_low: 'Low (1-3)',
    dilemma_tarot_reading: '✨ Tarot Fate Reading',
    dilemma_redo: 'Try Again',
    dilemma_enter_both: 'Please enter both options',
    dilemma_you_chose: 'You chose: ',
    dilemma_computer_chose: 'Computer chose: ',
    dilemma_winner_is: 'Winner: ',
    dilemma_dice_point: 'Dice roll: ',
    dilemma_computer_roll: 'Computer rolled: ',
    dilemma_you_bet: 'You bet: ',
    dilemma_dice_result_high: 'High (4-6)',
    dilemma_dice_result_low: 'Low (1-3)',
    dilemma_winner_is: 'Winner: ',
    decision_tie: 'It\'s a tie, try again!',
    difficulty_easy: '★☆☆',
    difficulty_medium: '★★☆',
    difficulty_hard: '★★★',
    filter_all: 'All',
    filter_advanced: 'Complex',
    filter_favorites: '★ Favorites',
    spread_search_placeholder: 'Search spreads...',
    cat_self: '🌱 Self Growth',
    spread_love_name: 'Love Spread',
    spread_love_desc: '7 cards · Comprehensive relationship analysis',
    spread_broken_name: 'Reunion Spread',
    spread_broken_desc: '6 cards · Breakup reasons & reunion chance',
    spread_yesno_name: 'Yes/No Spread',
    spread_yesno_desc: '3 cards · Yes/No decision guidance',
    spread_jobchange_name: 'Job Change Spread',
    spread_jobchange_desc: '5 cards · Job hopping / Career change',
    spread_shadow_name: 'Shadow Spread',
    spread_shadow_desc: '5 cards · Self-integration & growth',
    spread_year_name: 'Yearly Spread',
    spread_year_desc: '7 cards · Yearly fortune guidance',
    love_tip: 'For those in love or flirting, comprehensively analyzes all aspects of the relationship.',
    broken_tip: 'Use when you want to know if there is a chance to get back together, or to understand the reason for the breakup.',
    yesno_tip: 'When you are hesitant about a decision and just want a "yes" or "no" guidance.',
    jobchange_tip: 'For those considering job change, career switch, or job hopping, helps make wiser career decisions.',
    shadow_tip: 'For those who want to understand themselves deeply, do psychological growth or integrate shadow self.',
    year_tip: 'Draw at New Year or birthday to understand the year\'s fortune trend and development in all areas.',
    spread_proscons_name: 'Pros & Cons',
    spread_proscons_desc: '4 cards · Analyze pros and cons',
    spread_lifepurpose_name: 'Life Purpose',
    spread_lifepurpose_desc: '8 cards · Explore destiny & life direction',
    proscons_tip: 'Suitable for when you need to do a simple pros and cons analysis of something. More detailed than the Yes/No spread.',
    lifepurpose_tip: 'For life turning points, confused periods, or when wanting to find the meaning and direction of life. Helps explore destiny and mission.',
    // Card meaning
    btn_custom_meaning: 'Custom Meaning',
    cards_count_label: 'cards',
    // Comprehensive reading titles
    theme_title: '★ Overall Theme',
    relation_title: '⚙ Card Relationships',
    trend_title: '➡ Trend',
    advice_title: '⚡ Advice',
    // Overall theme
    theme_intro: 'In this {0} reading, {1} cards were drawn, with {2} upright and {3} reversed.',
    theme_has_majors: 'Major Arcana cards appeared ({0} cards: {1}). This indicates the question involves important life themes or deep transformations, which deserve serious attention.',
    theme_no_majors: 'All cards drawn are from the Minor Arcana, suggesting the question is more about daily life matters.',
    theme_dominant: 'The element of {0} is most prominent, ',
    theme_wands: 'indicating that overall energy leans toward action, passion and creativity. This is a time to take initiative.',
    theme_cups: 'indicating that overall energy leans toward emotions, intuition and relationships. More attention to inner feelings is needed.',
    theme_swords: 'indicating that overall energy leans toward thinking, communication and challenges. Rational analysis and clear judgment are needed.',
    theme_pentacles: 'indicating that overall energy leans toward material matters, career and practical results. Down-to-earth actions are required.',
    theme_mostly_reversed: 'Reversed cards are in the majority, suggesting that there may be obstacles, inner resistance or a need to adjust direction in the current situation; a more flexible attitude toward change is recommended.',
    theme_mostly_upright: 'Upright cards are in the majority, indicating that overall energy flows smoothly. The current direction is basically correct, just keep confidence and continue moving forward.',
    // Card relationships
    relation_three_past: 'The past ({0} {1}) sets the stage for the present ({2} {3}), and the present energy will continue into the future ({4} {5}).',
    relation_three_past_rev_now_up: 'The reversed past card shows old patterns are being resolved; now is a time for a fresh start.',
    relation_three_past_up_now_rev: 'The smooth accumulation from the past has not continued into the present. Review where deviations occurred.',
    relation_three_now_rev_future_up: 'Current difficulties are temporary; the future shows an upward trend. Please persevere.',
    relation_you: 'You ({0} {1}) and the other person ({2} {3}) have a clear energy interaction.',
    relation_same_rev: 'Both cards are in similar positions, indicating you share a relatively consistent understanding of this relationship, yet both may carry some inner resistance or confusion.',
    relation_same_up: 'Both cards are in similar positions, indicating you share a relatively consistent understanding of this relationship. This is a relatively harmonious and mutually understanding relationship.',
    relation_diff: 'Your card positions differ, which may indicate cognitive differences or being out of sync. More communication is needed.',
    relation_choice: 'Option A ({0} {1}) and Option B ({2} {3}) show different energy directions. The advice card ({4} {5}) provides important guidance for your decision; please reflect carefully on its message.',
    relation_celtic: 'The two cards at the center of the cross — Current Situation ({0}) and Challenge ({1}) — form the core tension of the issue. The energy of the past ({2}) still influences the present, while the final outcome card ({3}) points to the possible destination of this journey.',
    relation_suite_continue: '"{0}" and "{1}" are both from the {2} suit, showing energy continuity; ',
    relation_rev_to_up: 'From reversed "{0}" to upright "{1}", the situation is improving; ',
    relation_up_to_rev: 'From upright "{0}" to reversed "{1}", be alert to potential risks; ',
    relation_smooth: 'The energy flow between card positions is relatively stable, with no obvious conflicts or sudden changes, showing a gradual development trajectory.',
    // Trend
    trend_good: 'The spread shows an overall positive trend — more reversals in the first half suggest obstacles at the start; more upright cards in the second half indicate the situation will gradually open up. Persistence will bring rewards.',
    trend_warning: 'A trend to watch — the first half goes relatively smoothly, but more reversals in the second half suggest possible changes or challenges ahead. Prepare in advance and stay alert.',
    trend_stable: 'The spread shows relatively stable energy without dramatic improvement or deterioration. This is a period of accumulation and settling. Stay steady, neither rush nor be passive.',
    trend_major_turn: 'The appearance of "{0}" indicates a major turning point is coming. Be mentally prepared to embrace change.',
    // Advice
    advice_intro: 'Based on the overall spread guidance, the most worthwhile attitude to adopt now is: ',
    advice_upright: 'Actively embrace the upright energy of "{0}" — {1} In concrete actions, ',
    advice_wands: 'take the initiative and do not wait for opportunities to come to you.',
    advice_cups: 'listen to your inner voice and follow your intuition when making choices.',
    advice_swords: 'analyze the situation rationally and let clear thinking guide your actions.',
    advice_pentacles: 'focus on practical steps and advance your plan one step at a time.',
    advice_major: 'reflect on the core message this card conveys and integrate it into your decision-making.',
    advice_reversed: 'The reversed "{0}" reminds you that {1} It is suggested to resolve inner obstacles first before starting anew.',
    advice_many_reversed: 'With many reversed cards in the spread, it is recommended to give yourself more patience and tolerance. Do not demand immediate results; allow things to unfold at their own pace.'
  }
};
