/**
 * 塔罗牌扩展 - 常量定义
 * 包含牌阵配置、国际化字典、运势配置等
 */

// ============ 基础常量 ============
const SUPPORTED_LANGS = ['zh', 'en'];

const DECK_NAMES = {
  hp: '魔法主题',
  rider: '伟特塔罗',
  marseille: '马赛塔罗',
  thoth: '托特塔罗',
  angel: '天使塔罗',
  healing: '治愈塔罗',
  osho: '奥修禅卡'
};

// ============ 牌阵配置 ============
const SPREADS = {
  single: {
    name: '单牌占卜',
    nameEn: 'Single Card',
    positions: ['今日指引'],
    positionsEn: ['Daily Guidance'],
    positionMeanings: ['一张牌概括当前能量状态，适合快速提问或每日指引。正位通常表示顺利，逆位提示需要注意的方向。'],
    positionMeaningsEn: ['One card summarizes the current energy state. Good for quick questions or daily guidance. Upright suggests smoothness; reversed indicates areas to watch.'],
    category: 'simple', difficulty: 'easy', recommended: true, loadingText: '正在抽取今日指引...',
    loadingTextEn: 'Drawing your daily guidance...',
    usage: '适合每日抽一张牌作为当日指引，或针对一个具体问题寻求答案。',
    usageEn: 'Suitable for drawing one card daily as guidance, or for a specific question.'
  },
  three: {
    name: '三牌占卜',
    nameEn: 'Three Card Spread',
    positions: ['过去', '现在', '未来'],
    positionsEn: ['Past', 'Present', 'Future'],
    positionMeanings: [
      '过去：影响当前情况的历史因素或已发生的事件。',
      '现在：当前的核心状况、你的状态和正在发生的事。',
      '未来：基于当前趋势可能的发展方向，并非注定不变。'
    ],
    positionMeaningsEn: [
      'Past: Historical factors or events that influence the current situation.',
      'Present: The core situation, your state, and what is happening now.',
      'Future: Possible development direction based on current trends; not set in stone.'
    ],
    category: 'simple', difficulty: 'easy', recommended: true, loadingText: '正在展开三张牌...',
    loadingTextEn: 'Laying out three cards...',
    usage: '最经典的牌阵，适合大多数问题，时间线清晰，解读直观。',
    usageEn: 'The most classic spread, suitable for most questions. Clear timeline, intuitive reading.'
  },
  celtic: {
    name: '凯尔特十字',
    nameEn: 'Celtic Cross',
    positions: ['当前情况', '挑战/障碍', '过去基础', '近期过去', '可能未来', '近期未来', '你的态度', '外部影响', '希望与恐惧', '最终结果'],
    positionsEn: ['Current Situation', 'Challenge', 'Past', 'Future', 'Above', 'Below', 'Advice', 'External', 'Hopes/Fears', 'Outcome'],
    positionMeanings: [
      '当前情况：你目前所处的境况和核心问题。',
      '挑战/障碍：当前面临的主要困难或需要克服的挑战。',
      '过去基础：形成当前状况的过去原因和根基。',
      '近期过去：最近发生并仍在影响你的事情。',
      '可能未来：未来可能发展的方向（不一定发生）。',
      '近期未来：短期内即将发生的事。',
      '你的态度：你内心对这个问题的真实态度和感受。',
      '外部影响：来自外界的人、事、物对问题的影响。',
      '希望与恐惧：你内心深处的期望和担忧。',
      '最终结果：综合所有因素后最可能的结果。'
    ],
    positionMeaningsEn: [
      'Current Situation: The situation you are currently in and the core issue.',
      'Challenge: The main difficulty or challenge you are currently facing.',
      'Past: Past reasons and foundations that formed the current situation.',
      'Future: Recent past events that still influence you.',
      'Above: Possible future development direction (not guaranteed to happen).',
      'Below: Things that will happen in the near future.',
      'Advice: Your true attitude and feelings toward this issue.',
      'External: Influence from external people, events, or things on the issue.',
      'Hopes/Fears: Expectations and worries deep in your heart.',
      'Outcome: The most likely result after integrating all factors.'
    ],
    category: 'advanced', difficulty: 'hard', recommended: false, loadingText: '正在展开凯尔特十字...',
    loadingTextEn: 'Unfolding the Celtic Cross...',
    usage: '适合重要且复杂的问题，需要全面深入分析时使用。建议有一定塔罗基础后再尝试。',
    usageEn: 'Suitable for important and complex questions requiring comprehensive analysis. Recommended after gaining some Tarot foundation.'
  },
  relation: {
    name: '关系牌阵',
    nameEn: 'Relationship Spread',
    positions: ['你', '对方', '你的态度', '对方的态度', '当前关系', '发展方向'],
    positionsEn: ['You', 'Partner', 'Your Attitude', 'Their Attitude', 'Current Relationship', 'Direction'],
    positionMeanings: [
      '你：你在这段关系中的状态、能量和角色。',
      '对方：对方在这段关系中的状态、能量和角色。',
      '你的态度：你对这段关系的真实感受和态度。',
      '对方的态度：对方对这段关系的真实感受和态度。',
      '当前关系：你们之间目前的关系状态和互动模式。',
      '发展方向：这段关系未来的可能走向。'
    ],
    positionMeaningsEn: [
      'You: Your state, energy, and role in this relationship.',
      'Partner: The other person\'s state, energy, and role in this relationship.',
      'Your Attitude: Your true feelings and attitude toward this relationship.',
      'Their Attitude: The other person\'s true feelings and attitude toward this relationship.',
      'Current Relationship: The current relationship status and interaction pattern between you.',
      'Direction: The possible future direction of this relationship.'
    ],
    category: 'relationship', difficulty: 'medium', recommended: true, loadingText: '正在解读关系牌阵...',
    loadingTextEn: 'Reading the relationship spread...',
    usage: '适合分析任何人际关系，包括爱情、友情、亲子关系、职场关系等。',
    usageEn: 'Suitable for analyzing any interpersonal relationship, including romance, friendship, parenting, workplace relationships, etc.'
  },
  choice: {
    name: '二选一牌阵',
    nameEn: 'Choice Spread',
    positions: ['选项A', '选项B', 'A的可能结果', 'B的可能结果', '建议/提醒'],
    positionsEn: ['Option A', 'Option B', 'Outcome A', 'Outcome B', 'Advice'],
    positionMeanings: [
      '选项A：第一个选项的现状和本质。',
      '选项B：第二个选项的现状和本质。',
      'A的可能结果：如果选择A，可能带来的结果。',
      'B的可能结果：如果选择B，可能带来的结果。',
      '建议/提醒：塔罗对你的建议，以及需要特别注意的事项。'
    ],
    positionMeaningsEn: [
      'Option A: The current status and nature of the first option.',
      'Option B: The current status and nature of the second option.',
      'Outcome A: The possible result if you choose A.',
      'Outcome B: The possible result if you choose B.',
      'Advice: The Tarot\'s advice for you, and points to pay special attention to.'
    ],
    category: 'decision', difficulty: 'medium', recommended: false, loadingText: '正在分析两个选项...',
    loadingTextEn: 'Analyzing the two options...',
    usage: '当你在两个选项中犹豫不决时使用，帮助看清每个选项的利弊和可能结果。',
    usageEn: 'Use when you are hesitating between two options. Helps clarify the pros and cons and possible outcomes of each option.'
  },
  five: {
    name: '五张牌阵',
    nameEn: 'Five Card Spread',
    positions: ['问题核心', '面临的障碍', '潜意识/隐藏因素', '建议的行动', '可能的结果'],
    positionsEn: ['Problem', 'Obstacle', 'Subconscious', 'Suggested Action', 'Possible Outcome'],
    positionMeanings: [
      '问题核心：问题的本质和最关键的因素。',
      '面临的障碍：阻碍问题解决的主要困难和挑战。',
      '潜意识/隐藏因素：你自己可能未察觉的动机、情感或隐藏的影响因素。',
      '建议的行动：塔罗建议你采取的行动方向。',
      '可能的结果：如果按照建议行动，可能得到的结果。'
    ],
    positionMeaningsEn: [
      'Problem: The essence of the problem and the most critical factor.',
      'Obstacle: The main difficulty or challenge that hinders problem-solving.',
      'Subconscious: Motivations, emotions, or hidden influencing factors you may not be aware of.',
      'Suggested Action: The action direction the Tarot suggests you take.',
      'Possible Outcome: The possible result if you act on the suggestion.'
    ],
    category: 'decision', difficulty: 'medium', recommended: false, loadingText: '正在展开五张牌阵...',
    loadingTextEn: 'Unfolding the five-card spread...',
    usage: '适合分析任何类型的问题，从问题核心到解决方案，层层递进。',
    usageEn: 'Suitable for analyzing any type of problem, from the core issue to the solution, layer by layer.'
  },
  horseshoe: {
    name: '马蹄铁牌阵',
    nameEn: 'Horseshoe Spread',
    positions: ['过去的影响', '现在的情况', '隐藏的因素', '面临的挑战', '外部影响', '希望与恐惧', '最终结果'],
    positionsEn: ['Past Influence', 'Current', 'Hidden Factor', 'Challenge', 'External', 'Hopes/Fears', 'Outcome'],
    positionMeanings: [
      '过去的影响：过去事件对当前情况的持续影响。',
      '现在的情况：当前问题的实际状况。',
      '隐藏的因素：未被发现或未被重视的重要因素。',
      '面临的挑战：需要面对和克服的困难。',
      '外部影响：环境、他人或不可控因素对问题的影响。',
      '希望与恐惧：内心深处的期望与担忧，可能影响决策。',
      '最终结果：综合所有因素后，最有可能发生的结果。'
    ],
    positionMeaningsEn: [
      'Past Influence: The lasting impact of past events on the current situation.',
      'Current: The actual status of the current problem.',
      'Hidden Factor: Important factors that have not been discovered or valued.',
      'Challenge: Difficulties that need to be faced and overcome.',
      'External: Influence of environment, others, or uncontrollable factors on the problem.',
      'Hopes/Fears: Deep expectations and worries that may affect decision-making.',
      'Outcome: The most likely result after integrating all factors.'
    ],
    category: 'advanced', difficulty: 'medium', recommended: false, loadingText: '正在展开马蹄铁牌阵...',
    loadingTextEn: 'Unfolding the Horseshoe spread...',
    usage: '适合全面了解一个情况的各个层面，时间跨度从过去到未来。',
    usageEn: 'Suitable for comprehensively understanding all aspects of a situation, spanning from past to future.'
  },
  career: {
    name: '事业牌阵',
    nameEn: 'Career Spread',
    positions: ['当前状况', '面临的挑战', '你的优势', '建议的行动', '未来发展'],
    positionsEn: ['Current', 'Challenge', 'Strengths', 'Action', 'Future'],
    positionMeanings: [
      '当前状况：你在事业/学业方面的现状。',
      '面临的挑战：工作中遇到的困难或需要克服的障碍。',
      '你的优势：你拥有的能力、资源或有利条件。',
      '建议的行动：塔罗建议你在事业/学业上采取的行动。',
      '未来发展：基于当前情况，事业/学业的可能发展方向。'
    ],
    positionMeaningsEn: [
      'Current: Your current status in career/studies.',
      'Challenge: Difficulties encountered at work or obstacles to overcome.',
      'Strengths: Your abilities, resources, or favorable conditions.',
      'Action: Actions the Tarot suggests you take in career/studies.',
      'Future: Possible development direction of career/studies based on the current situation.'
    ],
    category: 'career', difficulty: 'medium', recommended: false, loadingText: '正在展开事业牌阵...',
    loadingTextEn: 'Unfolding the Career spread...',
    usage: '适合分析工作、学业、职业发展相关的问题，帮助做出更明智的职业决策。',
    usageEn: 'Suitable for analyzing work, study, and career development related questions. Helps make wiser career decisions.'
  },
  timeflow: {
    name: '时间之流',
    nameEn: 'Time Flow Spread',
    positions: ['过去', '现在', '未来', '深层原因', '可能的结果'],
    positionsEn: ['Past', 'Present', 'Future', 'Root Cause', 'Possible Outcome'],
    positionMeanings: [
      '过去：影响当前情况的历史因素和已发生的事件。',
      '现在：当前的核心状况和你的真实状态。',
      '未来：基于当前趋势最可能的发展方向。',
      '深层原因：潜藏在问题背后的根本动因。',
      '可能的结果：综合所有因素后最终可能呈现的状态。'
    ],
    positionMeaningsEn: [
      'Past: Historical factors and events that influenced the current situation.',
      'Present: The core situation and your true state at present.',
      'Future: The most likely development direction based on current trends.',
      'Root Cause: The root cause hidden behind the problem.',
      'Possible Outcome: The state that may eventually appear after integrating all factors.'
    ],
    category: 'fortune', difficulty: 'medium', recommended: false, loadingText: '正在展开时间之流...',
    loadingTextEn: 'Unfolding the Time Flow spread...',
    usage: '在时间维度上全面分析问题，适合想要看清事情来龙去脉的情况。',
    usageEn: 'Comprehensively analyze problems across the time dimension. Suitable for situations where you want to see the whole story.'
  },
  action: {
    name: '问题行动结果',
    nameEn: 'Problem-Action-Result',
    positions: ['问题核心', '建议行动', '可能结果'],
    positionsEn: ['Problem', 'Suggested Action', 'Possible Outcome'],
    positionMeanings: [
      '问题核心：你最关心的核心问题或担忧。',
      '建议行动：塔罗建议你采取的具体行动方向。',
      '可能结果：如果按照建议行动，最可能得到的结果。'
    ],
    positionMeaningsEn: [
      'Problem: The core problem or worry you care about most.',
      'Suggested Action: The specific action direction the Tarot suggests you take.',
      'Possible Outcome: The most likely result if you act on the suggestion.'
    ],
    category: 'simple', difficulty: 'easy', recommended: true, loadingText: '正在展开问题行动结果...',
    loadingTextEn: 'Analyzing Problem-Action-Result...',
    usage: '简洁明了的三位牌阵，适合快速决策和明确行动方向。',
    usageEn: 'A concise three-card spread, suitable for quick decision-making and clarifying action directions.'
  },
  mind: {
    name: '心灵牌阵',
    nameEn: 'Mind Spread',
    positions: ['意识', '潜意识', '理想', '现实', '建议'],
    positionsEn: ['Conscious', 'Subconscious', 'Ideal', 'Reality', 'Advice'],
    positionMeanings: [
      '意识：你清醒时对自己和问题的认知。',
      '潜意识：内心深处隐藏的动机、恐惧或渴望。',
      '理想：你内心真正渴望达到的状态或结果。',
      '现实：客观现实和实际的限制条件。',
      '建议：综合意识与潜意识、理想与现实后的最佳建议。'
    ],
    positionMeaningsEn: [
      'Conscious: Your awareness of yourself and the problem when awake.',
      'Subconscious: Hidden motivations, fears, or desires deep in your heart.',
      'Ideal: The state or result you truly desire deep in your heart.',
      'Reality: Objective reality and actual limiting conditions.',
      'Advice: The best advice after integrating conscious and subconscious, ideal and reality.'
    ],
    category: 'self', difficulty: 'medium', recommended: false, loadingText: '正在展开心灵牌阵...',
    loadingTextEn: 'Exploring the Mind spread...',
    usage: '适合自我探索和内心成长类问题，帮助看清内心真实想法。',
    usageEn: 'Suitable for self-exploration and inner growth questions. Helps clarify your true inner thoughts.'
  },
  // ============ 新增情感关系牌阵 ============
  love: {
    name: '恋人牌阵',
    nameEn: 'Love Spread',
    positions: ['你', '对方', '你们的关系', '面临的挑战', '周围的影响', '关系的未来', '建议'],
    positionsEn: ['You', 'Partner', 'Your Relationship', 'Challenges', 'External Influence', 'Relationship Future', 'Advice'],
    positionMeanings: [
      '你：你在这段感情中的状态、感受和行为模式。',
      '对方：对方在感情中的真实状态和对你的感受。',
      '你们的关系：这段关系的本质和当前的互动模式。',
      '面临的挑战：这段感情中需要面对和解决的问题。',
      '周围的影响：来自外界（朋友、家人、环境）对这段关系的影响。',
      '关系的未来：基于当前状态，这段关系可能的发展方向。',
      '建议：塔罗对这段感情的建议和指引。'
    ],
    positionMeaningsEn: [
      'You: Your state, feelings, and behavior pattern in this relationship.',
      'Partner: The other person\'s true state in the relationship and feelings toward you.',
      'Your Relationship: The nature of this relationship and the current interaction pattern.',
      'Challenges: Problems that need to be faced and resolved in this relationship.',
      'External Influence: Influence from the outside (friends, family, environment) on this relationship.',
      'Relationship Future: Possible development direction of this relationship based on the current state.',
      'Advice: The Tarot\'s advice and guidance for this relationship.'
    ],
    category: 'relationship', difficulty: 'medium', recommended: true, loadingText: '正在解读恋人牌阵...',
    loadingTextEn: 'Reading the Love spread...',
    usage: '适合正在恋爱或暧昧中的人，全面分析两人关系的各个层面。',
    usageEn: 'Suitable for people who are in love or in an ambiguous stage. Comprehensively analyzes all aspects of the two-person relationship.'
  },
  broken: {
    name: '复合牌阵',
    nameEn: 'Reunion Spread',
    positions: ['问题根源', '对方的想法', '你的状态', '障碍', '复合的可能性', '建议'],
    positionsEn: ['Root Cause', 'Their Thoughts', 'Your State', 'Obstacles', 'Reunion Possibility', 'Advice'],
    positionMeanings: [
      '问题根源：导致分手或关系破裂的核心原因。',
      '对方的想法：对方目前对你的真实想法和感受。',
      '你的状态：你在这段关系中的真实状态和需要成长的地方。',
      '障碍：复合道路上需要克服的困难和阻碍。',
      '复合的可能性：基于双方状态，复合的可能性有多大。',
      '建议：塔罗对你是否应该复合、以及如何行动的建议。'
    ],
    positionMeaningsEn: [
      'Root Cause: The core reason that led to the breakup or relationship rupture.',
      'Their Thoughts: The other person\'s true thoughts and feelings about you at present.',
      'Your State: Your true state in this relationship and areas where you need to grow.',
      'Obstacles: Difficulties and barriers that need to be overcome on the road to getting back together.',
      'Reunion Possibility: How likely is a reunion based on both parties\' status.',
      'Advice: The Tarot\'s advice on whether you should get back together and how to act.'
    ],
    category: 'relationship', difficulty: 'medium', recommended: false, loadingText: '正在解读复合牌阵...',
    loadingTextEn: 'Reading the Reunion spread...',
    usage: '适合分手后想了解是否还有复合可能，或想看清分手原因时使用。',
    usageEn: 'Suitable for use after a breakup when you want to know if there is still a possibility of getting back together, or want to see the reason for the breakup.'
  },
  // ============ 新增决策分析牌阵 ============
  yesno: {
    name: '是否牌阵',
    nameEn: 'Yes/No Spread',
    positions: ['支持因素', '反对因素', '综合建议'],
    positionsEn: ['Supporting Factors', 'Opposing Factors', 'Comprehensive Advice'],
    positionMeanings: [
      '支持因素：支持你做这件事的理由和有利条件。',
      '反对因素：反对你做这件事的理由和需要注意的风险。',
      '综合建议：综合两方面因素后，塔罗给出的建议（正位偏向"是"，逆位偏向"否"）。'
    ],
    positionMeaningsEn: [
      'Supporting Factors: Reasons and favorable conditions that support you doing this.',
      'Opposing Factors: Reasons against doing this and risks that need attention.',
      'Comprehensive Advice: The Tarot\'s advice after integrating both factors (upright leans toward "yes", reversed leans toward "no").'
    ],
    category: 'simple', difficulty: 'easy', recommended: false, loadingText: '正在解读是否牌阵...',
    loadingTextEn: 'Analyzing Yes/No spread...',
    usage: '当你对一个决定犹豫不决，只想得到一个"是"或"否"的指引时使用。',
    usageEn: 'Use when you are hesitating about a decision and just want a "yes" or "no" guidance.'
  },
  // ============ 新增事业学业牌阵 ============
  jobchange: {
    name: '换工作牌阵',
    nameEn: 'Job Change Spread',
    positions: ['现状', '想离职的原因', '新机会的本质', '风险与挑战', '建议'],
    positionsEn: ['Current Situation', 'Reason for Leaving', 'Nature of New Opportunity', 'Risks & Challenges', 'Advice'],
    positionMeanings: [
      '现状：你目前的工作状态和感受。',
      '想离职的原因：促使你想离开当前工作的核心因素。',
      '新机会的本质：新工作或新机会的真实情况。',
      '风险与挑战：换工作可能面临的困难和挑战。',
      '建议：塔罗对你是否应该换工作、以及如何选择的建议。'
    ],
    positionMeaningsEn: [
      'Current Situation: Your current work status and feelings.',
      'Reason for Leaving: The core factor that prompts you to want to leave your current job.',
      'Nature of New Opportunity: The true situation of the new job or new opportunity.',
      'Risks & Challenges: Difficulties and challenges you may face when changing jobs.',
      'Advice: The Tarot\'s advice on whether you should change jobs and how to choose.'
    ],
    category: 'career', difficulty: 'medium', recommended: false, loadingText: '正在解读换工作牌阵...',
    loadingTextEn: 'Analyzing Job Change spread...',
    usage: '适合正在考虑换工作、转行或跳槽的人，帮助做出更明智的职业决策。',
    usageEn: 'Suitable for people who are considering changing jobs, switching careers, or job hopping. Helps make wiser career decisions.'
  },
  // ============ 新增自我成长牌阵 ============
  shadow: {
    name: '阴影牌阵',
    nameEn: 'Shadow Spread',
    positions: ['意识自我', '阴影自我', '需要释放的', '成长方向', '建议'],
    positionsEn: ['Conscious Self', 'Shadow Self', 'What to Release', 'Growth Direction', 'Advice'],
    positionMeanings: [
      '意识自我：你平时展现给外界的自我形象。',
      '阴影自我：你不愿面对或否认的性格面向，可能正是你需要整合的部分。',
      '需要释放的：阻碍你成长的旧模式、执念或创伤。',
      '成长方向：你接下来应该专注的成长方向。',
      '建议：塔罗对你自我整合和成长的建议。'
    ],
    positionMeaningsEn: [
      'Conscious Self: The self-image you usually present to the outside world.',
      'Shadow Self: The personality aspects you are unwilling to face or deny, which may be exactly the parts you need to integrate.',
      'What to Release: Old patterns, obsessions, or traumas that hinder your growth.',
      'Growth Direction: The growth direction you should focus on next.',
      'Advice: The Tarot\'s advice for your self-integration and growth.'
    ],
    category: 'self', difficulty: 'medium', recommended: false, loadingText: '正在展开阴影牌阵...',
    loadingTextEn: 'Unfolding the Shadow spread...',
    usage: '适合想要深入了解自己、进行心理成长或整合阴影面的人。',
    usageEn: 'Suitable for people who want to deeply understand themselves, engage in psychological growth, or integrate their shadow side.'
  },
  year: {
    name: '年运牌阵',
    nameEn: 'Yearly Spread',
    positions: ['整体运势', '事业/学业', '感情/人际关系', '财富/物质', '健康/身心', '需要注意的', '年度建议'],
    positionsEn: ['Overall Fortune', 'Career/Study', 'Love/Relationships', 'Wealth/Material', 'Health/Wellness', 'Things to Note', 'Annual Advice'],
    positionMeanings: [
      '整体运势：这一年的整体能量和主题。',
      '事业/学业：这一年事业或学业方面的发展。',
      '感情/人际关系：这一年感情和人际方面的情况。',
      '财富/物质：这一年财务和物质生活方面的状况。',
      '健康/身心：这一年健康和身心状态需要注意的地方。',
      '需要注意的：这一年需要特别留意的人、事、物。',
      '年度建议：塔罗对这一年整体行动的建议。'
    ],
    positionMeaningsEn: [
      'Overall Fortune: The overall energy and theme of this year.',
      'Career/Study: Developments in career or studies this year.',
      'Love/Relationships: Situation in love and interpersonal relationships this year.',
      'Wealth/Material: Financial and material life status this year.',
      'Health/Wellness: Areas of health and physical/mental state that need attention this year.',
      'Things to Note: People, events, or things that need special attention this year.',
      'Annual Advice: The Tarot\'s advice for overall actions this year.'
    ],
    category: 'fortune', difficulty: 'hard', recommended: false, loadingText: '正在展开年运牌阵...',
    loadingTextEn: 'Unfolding the Yearly spread...',
    usage: '适合新年或生日时抽取，了解一整年的运势走向和各领域的发展。',
    usageEn: 'Suitable for drawing at New Year or birthday to understand the fortune trend and development in various fields for the whole year.'
  },
  // ============ 新增失物寻找牌阵 ============
  lost: {
    name: '失物寻找牌阵',
    nameEn: 'Lost Item Spread',
    positions: ['失物方向/位置', '失物状态', '寻找线索', '阻碍因素', '建议/是否能找回'],
    positionsEn: ['Direction/Location', 'Item Status', 'Search Clue', 'Obstacle', 'Advice/Can It Be Found'],
    positionMeanings: [
      '失物方向/位置：根据牌的花色判断方位和场所。权杖/火元素=南方、厨房、客厅、高处、电器附近；圣杯/水元素=西方、浴室、水源附近、低处、冰箱里；宝剑/风元素=东方、书房、办公室、窗户边、书籍文件附近；星币/土元素=北方、玄关、储物间、地面附近、口袋或包里。宫廷牌可能表示物品在某人那里。数字牌提示具体位置（如3=三楼/第三个房间）。',
      '失物状态：物品当前的状态和可见性。正位牌表示物品状态完好、未被移动、相对容易找到；逆位牌表示可能被损坏、被遮挡、已移位或掉落。数字牌暗示物品在某个容器、抽屉或袋子里；宫廷牌则表示物品在某人手中、口袋里或被借走。',
      '寻找线索：帮助定位物品的关键信息。大阿卡纳提示与重要事件、常去地点或近期活动有关；小阿卡纳指向具体房间或物品附近。注意牌面数字，可能对应楼层、房间号或时间线索（几小时前/几天前遗失）。出现「力量」「战车」等行动牌，建议立即主动寻找。',
      '阻碍因素：阻碍你找到物品的原因。逆位牌表示你忽略了最明显的地方，或记忆出现偏差；宝剑牌表示被其他物品遮挡、位置被移动或信息混乱；圣杯牌表示情绪紧张、心不在焉导致记忆模糊；星币牌表示被杂物覆盖、放在了不常去的地方或忘记放入何处。',
      '建议/是否能找回：塔罗给出的行动建议和找回可能性。正位牌偏向能找回，按牌面提示的方向和场所仔细寻找，不要放弃；逆位牌偏向难以找回，可能已被他人拿走、丢弃或遗失在外。若为大阿卡纳，说明物品对你有重要意义，值得坚持寻找；若为数字牌，按提示的具体位置逐一排查。'
    ],
    positionMeaningsEn: [
      'Direction/Location: Determine direction and place by suit. Wands/Fire = South, kitchen, living room, high places, near appliances; Cups/Water = West, bathroom, near water sources, low places, inside fridge; Swords/Air = East, study, office, near windows, near books/files; Pentacles/Earth = North, entrance, storage room, near the floor, in pockets or bags. Court cards may indicate the item is with someone.',
      'Item Status: The current status and visibility of the item. Upright cards mean the item is intact, unmoved, and relatively easy to find; reversed cards mean it may be damaged, obscured, shifted, or fallen. Number cards suggest the item is inside a container, drawer, or bag; Court cards indicate the item is in someone\'s hand, pocket, or has been borrowed.',
      'Search Clue: Key information to help locate the item. Major Arcana points to important events, frequently visited places, or recent activities; Minor Arcana points to specific rooms or near certain objects. Pay attention to card numbers — they may correspond to floor numbers, room numbers, or time clues (lost how many hours/days ago). If action cards like "Strength" or "Chariot" appear, search immediately and proactively.',
      'Obstacle: Reasons preventing you from finding the item. Reversed cards mean you\'re overlooking the most obvious place or your memory is inaccurate; Sword cards mean the item is blocked by other objects, has been moved, or information is confused; Cup cards mean emotional stress or absent-mindedness is blurring your memory; Pentacle cards mean the item is covered by clutter, placed in an unusual spot, or you forgot where it was put.',
      'Advice/Can It Be Found: The Tarot\'s action advice and the likelihood of recovery. Upright cards lean toward recoverable — search carefully in the direction and place indicated by the cards, don\'t give up; reversed cards lean toward difficult to recover — it may have been taken by someone else, discarded, or lost outside. If a Major Arcana appears, the item has important significance to you and is worth persistent searching; if a number card appears, check each specific location as indicated.'
    ],
    category: 'life', difficulty: 'easy', recommended: false, loadingText: '正在寻找失物...',
    loadingTextEn: 'Searching for your lost item...',
    usage: '适合物品遗失后使用，帮助定位失物位置、获取寻找线索和判断是否还能找回。',
    usageEn: 'Suitable for use after losing an item. Helps locate the lost item, get search clues, and determine if it can still be found.'
  },
  // ============ 新增决策分析牌阵 ============
  proscons: {
    name: '利弊分析',
    nameEn: 'Pros & Cons Spread',
    positions: ['利（支持的理由）', '弊（反对的理由）', '隐藏的因素', '建议'],
    positionsEn: ['Pros (Supporting Reasons)', 'Cons (Opposing Reasons)', 'Hidden Factor', 'Advice'],
    positionMeanings: [
      '利（支持的理由）：支持你做这件事的理由和有利条件。',
      '弊（反对的理由）：反对你做这件事的理由和需要注意的风险。',
      '隐藏的因素：未被考虑的隐藏因素或潜在影响。',
      '建议：综合各方面因素后，塔罗给出的建议（正位偏向支持，逆位偏向谨慎）。'
    ],
    positionMeaningsEn: [
      'Pros: Reasons and favorable conditions that support you doing this.',
      'Cons: Reasons against doing this and risks that need attention.',
      'Hidden Factor: Hidden factors or potential influences not yet considered.',
      'Advice: The Tarot\'s advice after integrating all factors (upright leans toward support, reversed leans toward caution).'
    ],
    category: 'decision', difficulty: 'easy', recommended: false, loadingText: '正在分析利弊...',
    loadingTextEn: 'Analyzing pros and cons...',
    usage: '适合需要对某件事做简单的利弊分析时使用，比是否牌阵更细致，比二选一牌阵更聚焦单一问题。',
    usageEn: 'Suitable for when you need to do a simple pros and cons analysis of something. More detailed than the Yes/No spread, more focused on a single issue than the Choice spread.'
  },
  // ============ 新增决策树牌阵 ============
  decisiontree: {
    name: '决策树牌阵',
    nameEn: 'Decision Tree Spread',
    positions: ['🌱 决策之根', '🌿 选择A的枝干（短期）', '🌳 选择A的果实（长期）', '🌿 选择B的枝干（短期）', '🌳 选择B的果实（长期）', '💡 园丁的建议'],
    positionsEn: ['🌱 Root', '🌿 Branch A (Short)', '🌳 Fruit A (Long)', '🌿 Branch B (Short)', '🌳 Fruit B (Long)', '💡 Gardener\'s Advice'],
    positionMeanings: [
      '🌱 决策之根：想象你面前有两颗种子（选择A和选择B），你打算种下哪一颗？这个位置揭示你内心真正的渴望和担忧。就像树根决定了树的方向，你的初心是什么？',
      '🌿 选择A的枝干（短期）：如果种下种子A，前1-3个月树苗会长什么样？这个阶段你能看到嫩芽破土、枝干伸展——可能是快速见效的喜悦，也可能是风雨摧折的挑战。',
      '🌳 选择A的果实（长期）：1年后，种子A会长成什么样的大树？会结出甜美的果实，还是酸涩的野果？短期看起来好看的树苗，长期可能长歪；短期看起来弱小的树苗，长期可能长成参天大树。',
      '🌿 选择B的枝干（短期）：如果种下种子B，前1-3个月又是怎样的光景？和A的嫩芽对比，哪个看起来更绿、更有生命力？',
      '🌳 选择B的果实（长期）：1年后再回头看，种子B长成的大树会让你在树荫下微笑，还是后悔没选另一条路？不要只看眼前的种子，要想象它长成大树的样子。',
      '💡 园丁的建议：塔罗就像一位经验丰富的园丁，看过无数棵树的生长。它会告诉你：哪颗种子更适合你的土壤？哪棵树更值得你花时间灌溉？记住：最好的选择不一定是最快开花的，而是让你愿意长期浇水、看着它长大的那颗。'
    ],
    positionMeaningsEn: [
      '🌱 Root: Imagine there are two seeds in front of you (Choice A and Choice B), which one are you going to plant? This position reveals your true desires and worries. Just like the root determines the tree\'s direction, what is your original intention?',
      '🌿 Branch A (Short): If you plant seed A, what will the sapling look like in the first 1-3 months? At this stage you can see sprouts breaking through the soil and branches stretching — could be the joy of quick results, or the challenge of wind and rain.',
      '🌳 Fruit A (Long): After 6 months to 1 year, what kind of big tree will seed A grow into? Will it bear sweet fruit, or sour wild fruit? A sapling that looks good short-term might grow crooked long-term; a sapling that looks weak short-term might grow into a towering tree long-term.',
      '🌿 Branch B (Short): If you plant seed B, what will the first 1-3 months look like? Comparing with A\'s sprouts, which one looks greener and more vibrant?',
      '🌳 Fruit B (Long): Looking back after a year, will the big tree grown from seed B make you smile in its shade, or regret not choosing another path? Don\'t just look at the seed in front of you, imagine what it will look like when it grows into a big tree.',
      '💡 Gardener\'s Advice: Tarot is like an experienced gardener who has seen countless trees grow. It will tell you: Which seed is more suitable for your soil? Which tree is more worth your time watering? Remember: The best choice isn\'t necessarily the one that blooms fastest, but the one you\'re willing to water long-term and watch grow big.'
    ],
    category: 'decision', difficulty: 'medium', recommended: true, loadingText: '正在展开决策树牌阵...',
    loadingTextEn: 'Unfolding the Decision Tree spread...',
    usage: '当你纠结于两个重要选择时，这个牌阵帮你看清每个选择的「短期后果」和「长期影响」，避免短视或过度焦虑未来。适合换工作、搬家、投资、分手等人生重大决策。',
    usageEn: 'When you\'re torn between two important choices, this spread helps you see the "short-term consequences" and "long-term impacts" of each choice, avoiding short-sightedness or over-worrying about the future. Suitable for major life decisions like job change, moving, investment, breakup, etc.'
  },
  // ============ 新增旅行牌阵 ============
  travel: {
    name: '旅行牌阵',
    nameEn: 'Travel Spread',
    positions: ['旅行整体能量', '目的地/出行方向', '需要注意的事项', '旅途中的收获', '建议'],
    positionsEn: ['Overall Travel Energy', 'Destination/Direction', 'Things to Note', 'Gains & Experiences', 'Advice'],
    positionMeanings: [
      '旅行整体能量：这次旅行的整体氛围和能量状态，是顺利愉快还是波折较多。',
      '目的地/出行方向：目的地的能量特质，或出行方向是否合适，是否有更好的选择。',
      '需要注意的事项：旅途中需要特别留意的人、事、物，可能的风险或麻烦。',
      '旅途中的收获：这次旅行能带给你的收获、体验、感悟或意外惊喜。',
      '建议：塔罗对这次旅行的具体建议，包括出行时机、准备事项、心态调整等。'
    ],
    positionMeaningsEn: [
      'Overall Travel Energy: The overall atmosphere and energy of this trip, whether it will be smooth and pleasant or full of twists and turns.',
      'Destination/Direction: The energy qualities of the destination, or whether the travel direction is suitable, if there is a better choice.',
      'Things to Note: People, events, or things that need special attention during the trip, possible risks or troubles.',
      'Gains & Experiences: The gains, experiences, insights, or unexpected surprises this trip can bring you.',
      'Advice: The Tarot\'s specific advice for this trip, including travel timing, preparation, mindset adjustment, etc.'
    ],
    category: 'life', difficulty: 'easy', recommended: true, loadingText: '正在展开旅行牌阵...',
    loadingTextEn: 'Unfolding the Travel spread...',
    usage: '适合出行前占卜，了解旅行整体状况、注意事项和旅途收获，帮助做出更明智的出行决策。',
    usageEn: 'Suitable for divination before traveling. Understand the overall travel situation, things to note, and travel gains, helping to make wiser travel decisions.'
  },
  // ============ 新增自我成长牌阵 ============
  lifepurpose: {
    name: '人生使命牌阵',
    nameEn: 'Life Purpose Spread',
    positions: ['你的核心天赋', '你的人生课题', '过去的制约/限制', '当前的机会', '需要释放的信念', '你的使命方向', '可能的阻碍', '建议'],
    positionsEn: ['Your Core Talent', 'Your Life Lesson', 'Past Conditioning', 'Current Opportunity', 'Beliefs to Release', 'Your Mission Direction', 'Possible Obstacles', 'Advice'],
    positionMeanings: [
      '你的核心天赋：你天生具备的天赋、才能或独特优势。',
      '你的人生课题：你此生需要学习的核心课题或需要克服的挑战。',
      '过去的制约/限制：来自过去（童年、成长环境、过往经历）的限制性信念或模式。',
      '当前的机会：此刻出现的、与你的使命相关的机会或召唤。',
      '需要释放的信念：阻碍你走向使命的旧有信念、恐惧或执念。',
      '你的使命方向：你的人生方向和使命所在，塔罗给出的指引。',
      '可能的阻碍：在实现使命道路上可能遇到的内在或外在阻碍。',
      '建议：塔罗对你如何走向人生使命、活出真实自我的建议。'
    ],
    positionMeaningsEn: [
      'Your Core Talent: The natural talents, abilities, or unique advantages you possess.',
      'Your Life Lesson: The core lesson you need to learn in this life or the challenge you need to overcome.',
      'Past Conditioning: Limiting beliefs or patterns from the past (childhood, upbringing, past experiences).',
      'Current Opportunity: Opportunities or calls appearing now that are related to your mission.',
      'Beliefs to Release: Old beliefs, fears, or obsessions that hinder you from moving toward your mission.',
      'Your Mission Direction: Your life direction and mission, the guidance given by the Tarot.',
      'Possible Obstacles: Inner or outer obstacles you may encounter on the path to fulfilling your mission.',
      'Advice: The Tarot\'s advice on how to move toward your life purpose and live as your true self.'
    ],
    category: 'spiritual', difficulty: 'hard', recommended: false, loadingText: '正在展开人生使命牌阵...',
    loadingTextEn: 'Unfolding the Life Purpose spread...',
    usage: '适合在人生转折点、迷茫期或想要寻找人生意义和方向时使用，帮助探索天命与使命。',
    usageEn: 'Suitable for use at life turning points, confused periods, or when wanting to find the meaning and direction of life. Helps explore destiny and mission.'
  },
  // ============ 新增学业考试牌阵 ============
  exam: {
    name: '考试牌阵',
    nameEn: 'Exam Spread',
    positions: ['考试/面试结果', '准备方向', '需要注意的地方', '潜在障碍', '建议'],
    positionsEn: ['Exam/Interview Result', 'Preparation Direction', 'Points to Note', 'Potential Obstacles', 'Advice'],
    positionMeanings: [
      '考试/面试结果：这次考试或面试最可能的结果和表现。',
      '准备方向：你应该重点复习或准备的方向和内容。',
      '需要注意的地方：考试中容易出错或忽略的关键点。',
      '潜在障碍：可能影响发挥的隐藏因素，如紧张、身体状态等。',
      '建议：塔罗对你备考策略、心态调整或面试准备的具体建议。'
    ],
    positionMeaningsEn: [
      'Exam/Interview Result: The most likely result and performance of this exam or interview.',
      'Preparation Direction: The direction and content you should focus on reviewing or preparing.',
      'Points to Note: Key points that are easily overlooked or mistaken in the exam.',
      'Potential Obstacles: Hidden factors that may affect your performance, such as nervousness, physical condition, etc.',
      'Advice: The Tarot\'s specific advice for your preparation strategy, mindset adjustment, or interview preparation.'
    ],
    category: 'career', difficulty: 'medium', recommended: true, loadingText: '正在展开考试牌阵...',
    loadingTextEn: 'Unfolding the Exam spread...',
    usage: '适合考前占卜，了解考试结果、复习重点和需要注意的事项。也适用于面试、资格考试等场景。',
    usageEn: 'Suitable for divination before exams. Understand exam results, key review points, and things to note. Also applicable to interviews, qualification exams, etc.'
  },
  // ============ 新增办公室人际牌阵 ============
  office: {
    name: '办公室人际牌阵',
    nameEn: 'Office Interpersonal Spread',
    positions: ['你的职场形象', '同事对你的看法', '上司/领导对你的看法', '职场人际隐患', '改善人际的建议', '最终职场关系走向'],
    positionsEn: ['Your Workplace Image', 'Colleagues\' View of You', 'Supervisor\'s View of You', 'Interpersonal Risks', 'Advice for Improvement', 'Final Workplace Relationship Outlook'],
    positionMeanings: [
      '你的职场形象：你在办公室中展现出来的形象和给人的第一印象，以及你如何看待自己在工作中的角色。',
      '同事对你的看法：你的同事们真正怎么看待你，他们对你的真实态度和评价，以及你们之间的互动模式。',
      '上司/领导对你的看法：你的上级或领导对你的评价和期望，他们在职场中如何看待你的能力和表现。',
      '职场人际隐患：办公室人际关系中潜在的问题和矛盾，可能被忽视的人际冲突或误解。',
      '改善人际的建议：塔罗牌对于如何改善办公室人际关系、化解矛盾、提升职场人缘的具体建议。',
      '最终职场关系走向：基于当前状况，未来一段时间办公室人际关系的发展趋势和可能的结果。'
    ],
    positionMeaningsEn: [
      'Your Workplace Image: The image you project in the office and the first impression you give, and how you see your role at work.',
      'Colleagues\' View of You: How your colleagues truly see you, their real attitude and evaluation of you, and your interaction patterns.',
      'Supervisor\'s View of You: Your supervisor\'s or leader\'s evaluation and expectations of you, how they see your performance.',
      'Interpersonal Risks: Potential problems and conflicts in office relationships, interpersonal conflicts or misunderstandings that may be overlooked.',
      'Advice for Improvement: The Tarot\'s specific advice on how to improve office relationships, resolve conflicts, and enhance workplace popularity.',
      'Final Workplace Relationship Outlook: Based on the current situation, the development trend and possible outcome of office relationships in the coming period.'
    ],
    category: 'career', difficulty: 'medium', recommended: false, loadingText: '正在展开办公室人际牌阵...',
    loadingTextEn: 'Unfolding the Office Interpersonal spread...',
    usage: '适合想了解办公室人际关系、改善同事关系、了解上司看法等场景。帮助你更好地 navigate 职场人际。',
    usageEn: 'Suitable for understanding office relationships, improving colleague relationships, understanding your supervisor\'s view, etc. Helps you better navigate workplace interpersonal dynamics.'
  },
  // ============ 新增命运走向牌阵 ============
  fatewheel: {
    name: '命运之轮',
    nameEn: 'Wheel of Fortune Spread',
    positions: ['当前命运状态', '命运的转变点', '隐藏的机遇', '需要警惕的陷阱', '最终的命运走向'],
    positionsEn: ['Current Fate Status', 'Turning Point of Fate', 'Hidden Opportunities', 'Traps to Watch Out', 'Final Fate Outcome'],
    positionMeanings: [
      '当前命运状态：这件事目前的命运能量和发展阶段，当前处于顺境还是逆境。',
      '命运的转变点：即将到来的关键转折点，命运之轮即将转动的方向，何时会发生转变。',
      '隐藏的机遇：命运中隐藏的机遇和可能性，容易被忽视但能改变命运走向的关键因素。',
      '需要警惕的陷阱：命运路上需要注意的障碍和陷阱，可能因疏忽而错失良机或遭遇挫折。',
      '最终的命运走向：这件事最终的命运归宿，综合所有因素后最可能的结果，命运之轮最终停下的位置。'
    ],
    positionMeaningsEn: [
      'Current Fate Status: The current fate energy and development stage of this matter, whether you are currently in good times or bad times.',
      'Turning Point of Fate: The upcoming key turning point, the direction the Wheel of Fortune is about to turn, when the change will happen.',
      'Hidden Opportunities: Hidden opportunities and possibilities in fate, key factors that are easily overlooked but can change the direction of fate.',
      'Traps to Watch Out: Obstacles and traps to watch out for on the road of fate, may miss good opportunities or encounter setbacks due to negligence.',
      'Final Fate Outcome: The final fate outcome of this matter, the most likely result after integrating all factors, where the Wheel of Fortune finally stops.'
    ],
    category: 'fortune', difficulty: 'medium', recommended: true, loadingText: '正在转动命运之轮...',
    loadingTextEn: 'Turning the Wheel of Fortune...',
    usage: '适合询问某件事的命运走向，了解命运的转变点和隐藏机遇，帮助把握命运的方向。',
    usageEn: 'Suitable for asking about the fate trend of something, understanding the turning points and hidden opportunities of fate, helping to grasp the direction of fate.'
  },
  // ============ 新增月运牌阵 ============
  monthly: {
    name: '月运牌阵',
    nameEn: 'Monthly Fortune Spread',
    positions: ['本月主题', '事业/学业运势', '感情/人际运势', '健康/财富运势', '本月注意事项'],
    positionsEn: ['Monthly Theme', 'Career/Study', 'Love/Social', 'Health/Wealth', 'Things to Note'],
    positionMeanings: [
      '本月主题：本月的核心能量和整体运势主题，指引本月的主旋律。',
      '事业/学业运势：本月在工作、学习方面的发展状况和机遇挑战。',
      '感情/人际运势：本月感情关系、人际交往方面的运势和需要注意的地方。',
      '健康/财富运势：本月身体健康状态和财务方面的运势。',
      '本月注意事项：本月需要特别留意的人、事、物，以及塔罗的提醒和建议。'
    ],
    positionMeaningsEn: [
      'Monthly Theme: The core energy and overall fortune theme of this month.',
      'Career/Study: Development status and opportunities/challenges in work and study this month.',
      'Love/Social: Fortune in romantic relationships and interpersonal interactions this month.',
      'Health/Wealth: Physical health status and financial fortune this month.',
      'Things to Note: People/events/things to pay special attention to, and the Tarot\'s advice.'
    ],
    category: 'fortune', difficulty: 'easy', recommended: true, loadingText: '正在展开月运牌阵...',
    loadingTextEn: 'Unfolding the Monthly Fortune spread...',
    usage: '适合月初或任意时间抽取，了解未来一个月各方面的运势走向和需要注意的事项。',
    usageEn: 'Suitable for drawing at the beginning of the month or anytime to understand the fortune trends for the coming month.'
  },
  // ============ 新增灵魂旅程牌阵 ============
  souljourney: {
    name: '灵魂旅程',
    nameEn: 'Soul Journey Spread',
    positions: ['当下的灵魂状态', '需要学习的课题', '正在释放的旧模式', '当前的精神挑战', '宇宙的指引', '内在的阴影面', '高我/直觉声音', '接下来的成长方向', '综合建议'],
    positionsEn: ['Current Soul State', 'Lesson to Learn', 'Old Patterns Releasing', 'Spiritual Challenge', 'Universe Guidance', 'Inner Shadow', 'Higher Self/Intuition', 'Growth Direction', 'Comprehensive Advice'],
    positionMeanings: [
      '当下的灵魂状态：你灵魂此刻所处的阶段和能量状态，你正在经历怎样的灵魂成长。',
      '需要学习的课题：你此生或此阶段最需要学习的核心灵魂课题。',
      '正在释放的旧模式：你目前正在放下、疗愈或转化的旧有模式、信念或创伤。',
      '当前的精神挑战：你在灵性成长道路上当前面临的最大挑战。',
      '宇宙的指引：宇宙/源头/高维能量想通过这个情况传达给你的讯息。',
      '内在的阴影面：你灵魂深处尚未整合、需要看见和接纳的阴影部分。',
      '高我/直觉声音：你的高我或内在智慧想让你听见的声音和指引。',
      '接下来的成长方向：基于当前状态，你灵魂接下来最适宜的成长方向。',
      '综合建议：塔罗对你灵魂旅程的整体建议，以及当下最需要做的事。'
    ],
    positionMeaningsEn: [
      'Current Soul State: The stage and energy state your soul is currently in, and what soul growth you are experiencing.',
      'Lesson to Learn: The core soul lesson you need to learn most in this lifetime or this phase.',
      'Old Patterns Releasing: The old patterns, beliefs, or traumas you are currently letting go of, healing, or transforming.',
      'Spiritual Challenge: The biggest challenge you are currently facing on your spiritual growth path.',
      'Universe Guidance: The message the Universe/Source/higher dimensional energy wants to convey to you through this situation.',
      'Inner Shadow: The shadow aspects deep in your soul that have not yet been integrated and need to be seen and accepted.',
      'Higher Self/Intuition: The voice and guidance your higher self or inner wisdom wants you to hear.',
      'Growth Direction: Based on your current state, the most suitable direction for your soul\'s next growth.',
      'Comprehensive Advice: The Tarot\'s overall advice for your soul journey and what you most need to do right now.'
    ],
    category: 'spiritual', difficulty: 'hard', recommended: false, loadingText: '正在展开灵魂旅程...',
    loadingTextEn: 'Unfolding the Soul Journey spread...',
    usage: '适合在灵性成长、内心探索、人生转折点时使用，帮助连接高我、看清灵魂课题与成长方向。',
    usageEn: 'Suitable for use during spiritual growth, inner exploration, or life turning points. Helps connect with higher self and clarify soul lessons and growth direction.'
  },
  // ============ 新增梦境解读牌阵 ============
  dream: {
    name: '梦境解读牌阵',
    nameEn: 'Dream Interpretation Spread',
    positions: ['梦境主题/核心意象', '隐藏的情绪', '潜意识讯息', '现实关联', '建议/行动'],
    positionsEn: ['Dream Theme/Core Image', 'Hidden Emotion', 'Subconscious Message', 'Real-life Connection', 'Advice/Action'],
    positionMeanings: [
      '梦境主题/核心意象：梦中反复出现或最令你印象深刻的画面、人物或场景，是梦境的核心线索。',
      '隐藏的情绪：这个梦境反映了你内心深处哪些未被察觉或未被表达的情绪，可能是被压抑的恐惧、渴望或焦虑。',
      '潜意识讯息：你的潜意识想通过这个梦境传达给你的重要讯息，可能是被忽略的直觉、警告或启示。',
      '现实关联：这个梦境与你现实生活中哪些人、事、物或处境有关联，梦境正在回应你生活中的什么议题。',
      '建议/行动：基于梦境的启示，塔罗建议你如何在现实生活中行动，或如何整合这个梦境带来的觉察。'
    ],
    positionMeaningsEn: [
      'Dream Theme/Core Image: The scenes, characters, or images that repeatedly appear or impress you most in the dream. They are the core clues of the dream.',
      'Hidden Emotion: What emotions does this dream reflect that are undetected or unexpressed deep in your heart? Possibly suppressed fears, desires, or anxieties.',
      'Subconscious Message: The important message your subconscious wants to convey to you through this dream. It may be an overlooked intuition, warning, or revelation.',
      'Real-life Connection: Which people, events, things, or situations in your real life are related to this dream? What issue in your life is the dream responding to?',
      'Advice/Action: Based on the dream\'s revelation, the Tarot suggests how you should act in real life, or how to integrate the awareness brought by this dream.'
    ],
    category: 'self', difficulty: 'medium', recommended: false, loadingText: '正在解读你的梦境...',
    loadingTextEn: 'Interpreting your dream...',
    usage: '适合在做了印象深刻、反复出现或令你困惑的梦之后使用，帮助理解梦境背后的潜意识讯息。',
    usageEn: 'Suitable for use after having an impressive, recurring, or confusing dream. Helps understand the subconscious message behind the dream.'
  },
  // ============ 新增星座牌阵（12宫位）============
  zodiac: {
    name: '星座牌阵',
    nameEn: 'Zodiac Spread',
    positions: ['第1宫：自我形象', '第2宫：财富资源', '第3宫：沟通学习', '第4宫：家庭根基', '第5宫：创造力', '第6宫：健康服务', '第7宫：伴侣关系', '第8宫：转化重生', '第9宫：人生哲学', '第10宫：事业声望', '第11宫：社交愿景', '第12宫：潜意识'],
    positionsEn: ['1st House: Self Image', '2nd House: Wealth & Resources', '3rd House: Communication & Learning', '4th House: Home & Foundation', '5th House: Creativity', '6th House: Health & Service', '7th House: Partnership', '8th House: Transformation', '9th House: Life Philosophy', '10th House: Career & Reputation', '11th House: Social & Vision', '12th House: Subconscious'],
    positionMeanings: [
      '第1宫：自我形象。你给外界的第一印象、外貌特征、性格特质和人生的基本态度。',
      '第2宫：财富资源。你的收入来源、赚钱能力、物质价值观和拥有的资源。',
      '第3宫：沟通学习。你的沟通方式、学习能力、兄弟姐妹关系、短途旅行和邻里关系。',
      '第4宫：家庭根基。你的家庭背景、成长环境、内心安全感来源和家族根基。',
      '第5宫：创造力。你的创造力、恋爱运势、子女缘分、娱乐方式和自我表达。',
      '第6宫：健康服务。你的健康状况、工作态度、服务精神和日常生活的秩序。',
      '第7宫：伴侣关系。你的婚姻状况、合作伙伴、一对一关系的模式和质量。',
      '第8宫：转化重生。你的性关系、他人资源、危机转化能力和深层心理课题。',
      '第9宫：人生哲学。你的宗教信仰、高等教育、长途旅行和人生哲学观。',
      '第10宫：事业声望。你的事业发展、社会声望、公众形象和人生目标。',
      '第11宫：社交愿景。你的朋友圈、社团活动、未来愿景和社会理想。',
      '第12宫：潜意识。你的潜意识模式、灵性修行、隐藏的恐惧和因果业力。'
    ],
    positionMeaningsEn: [
      '1st House: Self Image. The first impression you give to the outside world, physical appearance, personality traits, and basic attitude toward life.',
      '2nd House: Wealth & Resources. Your income source, money-making ability, material values, and resources you possess.',
      '3rd House: Communication & Learning. Your communication style, learning ability, relationship with siblings, short trips, and neighborhood relations.',
      '4th House: Home & Foundation. Your family background, growing environment, source of inner security, and family roots.',
      '5th House: Creativity. Your creativity, love fortune, affinity with children, entertainment style, and self-expression.',
      '6th House: Health & Service. Your health condition, work attitude, service spirit, and order in daily life.',
      '7th House: Partnership. Your marriage status, cooperative partners, patterns and quality of one-on-one relationships.',
      '8th House: Transformation. Your sexual relationships, other people\'s resources, crisis transformation ability, and deep psychological issues.',
      '9th House: Life Philosophy. Your religious beliefs, higher education, long-distance travel, and philosophy of life.',
      '10th House: Career & Reputation. Your career development, social reputation, public image, and life goals.',
      '11th House: Social & Vision. Your circle of friends, community activities, future vision, and social ideals.',
      '12th House: Subconscious. Your subconscious patterns, spiritual practice, hidden fears, and karmic lessons.'
    ],
    category: 'advanced', difficulty: 'hard', recommended: false, loadingText: '正在展开星座牌阵...',
    loadingTextEn: 'Unfolding the Zodiac spread...',
    usage: '对应黄道12宫位，全面分析生活各个领域。适合年度运势解读、全面了解自己或某人。需要一定塔罗基础。',
    usageEn: 'Corresponding to the 12 astrological houses, comprehensively analyzes all areas of life. Suitable for annual fortune reading, comprehensive self-understanding. Requires some Tarot foundation.'
  },
  // ============ 新增前世今生牌阵 ============
  pastlife: {
    name: '前世今生',
    nameEn: 'Past Life Spread',
    positions: ['前世身份', '未完成课题', '今生挑战', '灵魂成长方向', '建议'],
    positionsEn: ['Past Life Identity', 'Unfinished Lesson', 'Current Life Challenge', 'Soul Growth Direction', 'Advice'],
    positionMeanings: [
      '前世身份：你在前世的角色、身份或主要经历，影响今生的性格和偏好。',
      '未完成课题：前世未完成的灵魂课题，今生需要继续学习和体验。',
      '今生挑战：今生面临的主要挑战和困难，与前世因果密切相关。',
      '灵魂成长方向：你的灵魂此生想要成长和体验的方向。',
      '建议：塔罗对你灵魂成长和化解前世业力的建议。'
    ],
    positionMeaningsEn: [
      'Past Life Identity: Your role, identity, or main experience in past life, which influences your personality and preferences in this life.',
      'Unfinished Lesson: The soul lesson unfinished in past life, which needs to be continued and experienced in this life.',
      'Current Life Challenge: The main challenges and difficulties you face in this life, closely related to past life karma.',
      'Soul Growth Direction: The direction your soul wants to grow and experience in this life.',
      'Advice: The Tarot\'s advice for your soul growth and resolving past life karma.'
    ],
    category: 'spiritual', difficulty: 'hard', recommended: false, loadingText: '正在连接前世记忆...',
    loadingTextEn: 'Connecting to past life memories...',
    usage: '适合探索灵魂成长、理解今生的重复模式、寻找生命课题。需要一定灵性基础。',
    usageEn: 'Suitable for exploring soul growth, understanding recurring patterns in this life, and finding life lessons. Requires some spiritual foundation.'
  },
  // ============ 新增健康牌阵 ============
  health: {
    name: '健康牌阵',
    nameEn: 'Health Spread',
    positions: ['身体状态', '心理情绪', '根本原因', '疗愈方向', '注意事项'],
    positionsEn: ['Physical Condition', 'Mental & Emotional', 'Root Cause', 'Healing Direction', 'Precautions'],
    positionMeanings: [
      '身体状态：当前身体的整体状况，需要关注的部位或症状。',
      '心理情绪：心理状态对身体健康的影响，情绪层面的根源。',
      '根本原因：导致健康问题的深层次原因，可能是生活方式、情绪积压或环境因素。',
      '疗愈方向：改善健康状态的建议方向，包括生活习惯、心态调整等。',
      '注意事项：需要特别留意的症状、行为或健康风险，提醒及时就医。'
    ],
    positionMeaningsEn: [
      'Physical Condition: Current overall physical condition, areas or symptoms that need attention.',
      'Mental & Emotional: The impact of psychological state on physical health, emotional root causes.',
      'Root Cause: The deep-seated reason for health problems, may be lifestyle, emotional backlog, or environmental factors.',
      'Healing Direction: Suggested directions for improving health, including lifestyle habits, mindset adjustment, etc.',
      'Precautions: Symptoms, behaviors, or health risks that need special attention. Reminder to seek medical advice promptly.'
    ],
    category: 'life', difficulty: 'medium', recommended: false, loadingText: '正在展开健康牌阵...',
    loadingTextEn: 'Unfolding the Health spread...',
    usage: '关注身心健康，探寻身体与情绪的根本原因，给出疗愈方向。仅作辅助参考，不能替代专业医疗建议。',
    usageEn: 'Focus on physical and mental health, explore the root causes of body and emotions, and give healing directions. For reference only, cannot replace professional medical advice.'
  },
  // ============ 新增家庭关系牌阵 ============
  family: {
    name: '家庭关系',
    nameEn: 'Family Spread',
    positions: ['你', '父亲', '母亲', '家庭氛围', '改善建议'],
    positionsEn: ['You', 'Father', 'Mother', 'Family Atmosphere', 'Improvement Advice'],
    positionMeanings: [
      '你：你在这个家庭中的状态、角色和感受。',
      '父亲：父亲的状态、对你的影响，以及父子/父女关系的质量。',
      '母亲：母亲的状态、对你的影响，以及母子/母女关系的质量。',
      '家庭氛围：整个家庭的能量氛围、沟通模式和潜在问题。',
      '改善建议：塔罗对改善家庭关系和氛围的具体建议。'
    ],
    positionMeaningsEn: [
      'You: Your state, role, and feelings in this family.',
      'Father: Father\'s state, his influence on you, and the quality of father-child relationship.',
      'Mother: Mother\'s state, her influence on you, and the quality of mother-child relationship.',
      'Family Atmosphere: The energy atmosphere of the whole family, communication patterns, and potential problems.',
      'Improvement Advice: The Tarot\'s specific advice for improving family relationships and atmosphere.'
    ],
    category: 'relationship', difficulty: 'medium', recommended: false, loadingText: '正在展开家庭关系牌阵...',
    loadingTextEn: 'Unfolding the Family spread...',
    usage: '适合分析家庭关系、亲子关系、家庭氛围等问题，帮助改善家庭和谐。',
    usageEn: 'Suitable for analyzing family relationships, parent-child relationships, family atmosphere, etc. Helps improve family harmony.'
  },
  // ============ 新增一周运势牌阵 ============
  weekly: {
    name: '一周运势',
    nameEn: 'Weekly Fortune Spread',
    positions: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
    positionsEn: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    positionMeanings: [
      '周一：本周开始时的能量状态，工作/学业的起始运势，需要注意的事项。',
      '周二：周中前期的能量变化，可能遇到的机遇或挑战，情绪状态。',
      '周三：一周的中点，能量转折的关键日，需要特别关注的人和事。',
      '周四：周中后期的能量走向，工作/学业进展，人际互动状况。',
      '周五：临近周末的能量状态，心情与社交运势，适合安排的活动。',
      '周六：周末第一天的能量，休息与娱乐运势，家庭与社交活动。',
      '周日：周末收尾与下周准备，能量总结与调整，下周运势的预兆。'
    ],
    positionMeaningsEn: [
      'Mon: Energy state at the start of the week, work/study fortune at the beginning, things to note.',
      'Tue: Energy changes in the early mid-week, possible opportunities or challenges, emotional state.',
      'Wed: The midpoint of the week, a key day for energy shifts, people and things to pay special attention to.',
      'Thu: Energy trend in the late mid-week, work/study progress, interpersonal interaction status.',
      'Fri: Energy state approaching the weekend, mood and social fortune, suitable activities to arrange.',
      'Sat: Energy on the first day of the weekend, rest and entertainment fortune, family and social activities.',
      'Sun: Weekend wrap-up and next week preparation, energy summary and adjustment, omens for next week\'s fortune.'
    ],
    category: 'fortune', difficulty: 'medium', recommended: true, loadingText: '正在展开一周运势...',
    loadingTextEn: 'Unfolding the Weekly Fortune spread...',
    usage: '适合周日或周一抽取，了解未来一周每天的运势走向，提前做好规划与准备。',
    usageEn: 'Suitable for drawing on Sunday or Monday to understand the fortune trend for each day of the coming week, and plan ahead.'
  },
  // ============ 新增灵感创作牌阵 ============
  creative: {
    name: '灵感创作',
    nameEn: 'Creative Inspiration Spread',
    positions: ['创作瓶颈根源', '灵感方向', '需要突破的点', '创作能量状态', '建议'],
    positionsEn: ['Root of Creative Block', 'Inspiration Direction', 'Breakthrough Point', 'Creative Energy', 'Advice'],
    positionMeanings: [
      '创作瓶颈根源：导致你卡文、没有灵感或创作停滞的深层原因，可能是内在恐惧、外在压力或能量枯竭。',
      '灵感方向：宇宙/潜意识想给你的创作灵感方向，值得关注的主题、意象或路径。',
      '需要突破的点：你在创作中需要勇敢跨出去的那一步，可能是风格突破、题材拓展或表达方式的改变。',
      '创作能量状态：你当前的创作能量是否充沛，是灵感迸发期还是沉淀积累期。',
      '建议：塔罗对你创作之路的具体建议，包括如何找回灵感、突破瓶颈或调整创作节奏。'
    ],
    positionMeaningsEn: [
      'Root of Creative Block: The deep reason causing your writer\'s block, lack of inspiration, or creative stagnation. May be inner fear, external pressure, or energy depletion.',
      'Inspiration Direction: The direction of creative inspiration that the universe/subconscious wants to give you. Themes, imagery, or paths worth paying attention to.',
      'Breakthrough Point: The step you need to bravely take in your creation. May be style breakthrough, genre expansion, or change of expression.',
      'Creative Energy: Whether your current creative energy is abundant, whether this is a period of inspiration burst or accumulation and sedimentation.',
      'Advice: The Tarot\'s specific advice for your creative path, including how to regain inspiration, break through bottlenecks, or adjust creative rhythm.'
    ],
    category: 'spiritual', difficulty: 'medium', recommended: true, loadingText: '正在连接创作灵感...',
    loadingTextEn: 'Connecting to creative inspiration...',
    usage: '适合创作者卡文、寻找灵感方向、或想要突破创作瓶颈时使用。也适用于任何需要创意发想的情境。',
    usageEn: 'Suitable for creators facing writer\'s block, seeking inspiration direction, or wanting to break through creative bottlenecks. Also applicable to any situation requiring creative ideas.'
  },
  // ============ 财务投资牌阵 ============
  finance: {
    name: '财务投资',
    nameEn: 'Finance & Investment Spread',
    positions: ['当前财务状况', '投资风险', '潜在收益', '时间因素', '建议'],
    positionsEn: ['Current Finance', 'Investment Risk', 'Potential Return', 'Timing', 'Advice'],
    positionMeanings: [
      '当前财务状况：你的财务能量状态，收入/支出趋势，当前的财务安全感或焦虑感来源。',
      '投资风险：这个财务决策潜在的风险点，可能亏损的方式，需要格外留心的因素。',
      '潜在收益：这个决策可能带来的回报或收益，不仅是金钱层面，也包括机会和成长。',
      '时间因素：时机是否合适，短期/长期影响，何时能看到结果，时间轴上的注意事项。',
      '建议：塔罗对这次财务决策的具体建议，包括是否行动、如何规避风险、何时进退。'
    ],
    positionMeaningsEn: [
      'Current Finance: Your financial energy state, income/expense trends, source of financial security or anxiety.',
      'Investment Risk: Potential risks of this financial decision, ways you might lose money, factors requiring extra caution.',
      'Potential Return: Possible returns or gains from this decision, not only in monetary terms but also opportunities and growth.',
      'Timing: Whether the timing is right, short/long-term impact, when results will be seen, timeline considerations.',
      'Advice: The Tarot\'s specific advice for this financial decision, including whether to act, how to avoid risks, when to advance or retreat.'
    ],
    category: 'life', difficulty: 'medium', recommended: true, loadingText: '正在解读财务状况...',
    loadingTextEn: 'Analyzing financial situation...',
    usage: '适合投资理财决策、大额消费、买房/买车等财务决策前使用。帮助你从能量层面看清财务风险与机会。',
    usageEn: 'Suitable for investment decisions, large purchases, buying a house/car, etc. Helps you see financial risks and opportunities from an energy perspective.'
  },
  // ============ 断舍离牌阵 ============
  declutter: {
    name: '断舍离',
    nameEn: 'Declutter & Let Go Spread',
    positions: ['要舍弃的对象本质', '不舍的原因', '舍弃后的收获', '建议'],
    positionsEn: ['What to Let Go', 'Reason for Attachment', 'Gain After Letting Go', 'Advice'],
    positionMeanings: [
      '要舍弃的对象本质：你当前需要放下的人、事、物或习惯的本质，它对你当下的影响是什么。',
      '不舍的原因：你为什么难以放手，执着的深层原因，可能是恐惧、习惯、期待或自我认同的绑定。',
      '舍弃后的收获：当你真正放下之后，会获得什么——可能是自由、能量、新机会或内心的平静。',
      '建议：塔罗对你「断舍离」之路的具体建议，包括如何放手、放下的步骤、以及放下后如何重建。'
    ],
    positionMeaningsEn: [
      'What to Let Go: The essence of the person, thing, habit, or situation you need to release right now, and how it affects you.',
      'Reason for Attachment: Why you find it hard to let go. The deep reason for your attachment — may be fear, habit, expectation, or identity bond.',
      'Gain After Letting Go: What you will gain after truly letting go — may be freedom, energy, new opportunities, or inner peace.',
      'Advice: The Tarot\'s specific advice for your decluttering journey — how to let go, steps for release, and how to rebuild afterward.'
    ],
    category: 'self', difficulty: 'easy', recommended: true, loadingText: '正在清理能量场...',
    loadingTextEn: 'Clearing your energy field...',
    usage: '适合纠结是否要舍弃某人/某物/某种生活方式、想要清理能量场、或做「放下」决策时使用。',
    usageEn: 'Suitable when you are torn about letting go of someone/something/a lifestyle, want to clear your energy field, or need to make a "letting go" decision.'
  }
};

// ============ 运势相关常量 ============
const FORTUNE_CATEGORIES = ['事业', '财运', '感情', '健康', '学习', '社交'];

const FORTUNE_LEVELS = [
  { text: '大吉', score: 95, color: '#FFD700', desc: '今日运势极佳，万事顺遂，适合推进重要计划。' },
  { text: '吉', score: 80, color: '#4CAF50', desc: '今日运势良好，积极行动会有不错的收获。' },
  { text: '中吉', score: 70, color: '#2196F3', desc: '今日运势平稳，按部就班即可，宜守不宜攻。' },
  { text: '小吉', score: 60, color: '#9C27B0', desc: '今日运势尚可，小事顺利但大事需谨慎。' },
  { text: '平', score: 50, color: '#607D8B', desc: '今日运势平淡，适合休整和规划，不宜冒进。' },
  { text: '小凶', score: 40, color: '#FF9800', desc: '今日需谨慎行事，避免重要决策和大额支出。' },
  { text: '凶', score: 25, color: '#F44336', desc: '今日运势低迷，宜静不宜动，注意安全和健康。' }
];

const LUCKY_COLORS = [
  { name: '金色', hex: '#FFD700' },
  { name: '紫色', hex: '#9C27B0' },
  { name: '蓝色', hex: '#2196F3' },
  { name: '绿色', hex: '#4CAF50' },
  { name: '红色', hex: '#F44336' },
  { name: '橙色', hex: '#FF9800' },
  { name: '青色', hex: '#00BCD4' },
  { name: '粉色', hex: '#E91E63' },
  { name: '白色', hex: '#FFFFFF' },
  { name: '银色', hex: '#9E9E9E' }
];

const LUCKY_ADVICE = {
  '大吉': ['宜：签约、表白、投资、出行', '忌：无所事事、浪费机会'],
  '吉': ['宜：学习、社交、购物、运动', '忌：冲动决策、与人争执'],
  '中吉': ['宜：整理、规划、沟通、休息', '忌：冒险投资、重大变动'],
  '小吉': ['宜：阅读、散步、做家务、听音乐', '忌：熬夜、过量饮食'],
  '平': ['宜：冥想、复盘、维护关系、储蓄', '忌：借贷、跳槽、远行'],
  '小凶': ['宜：独处、学习、做计划', '忌：签约、手术、争吵'],
  '凶': ['宜：静养、念佛、整理旧物', '忌：投资、远行、重大决定']
};

// 大阿尔卡那专属图标（id 0~21 对应 22 张牌）
const MAJOR_ARCANA_ICONS = [
  '🃏', '🎩', '📖', '🌹', '👑', '✝️', '💕', '🏇', '💪', '🔍',
  '🎡', '⚖️', '🔄', '💀', '🍶', '😈', '⚡', '⭐', '🌕', '☀️',
  '🎺', '🌐'
];

// ============ 国际化字典 ============
const I18N = {
  zh: {
    welcome_title: '魔法塔罗牌',
    welcome_subtitle: '探索魔法世界的命运指引',
    label_deck: '选择牌组：',
    deck_magic: '魔法主题',
    deck_rider: '伟特塔罗',
    deck_marseille: '马赛塔罗',
    deck_thoth: '托特塔罗',
    deck_angel: '天使塔罗',
    deck_healing: '治愈塔罗',
    deck_osho: '奥修禅卡',
    label_lang: '语言：',
    inst_start: '选择牌阵开始你的魔法之旅',
    inst_click: '点击卡牌查看正/逆位解读',
    inst_reshuffle: '随时可以重新洗牌占卜',
    btn_history: '查看历史记录',
    btn_favorites: '收藏夹',
    btn_daily_fortune: '今日运势',
    fortune_panel_title: '✨ 今日运势',
    fortune_loading: '正在解读今日运势...',
    cat_simple: '入门经典',
    cat_relationship: '情感关系',
    cat_decision: '决策分析',
    cat_advanced: '深度专题',
    cat_fortune: '运势预测',
    cat_life: '生活决策',
    cat_career: '事业学业',
    cat_spiritual: '灵性成长',
    badge_recommended: '★ 推荐',
    spread_single_name: '单牌阵',
    spread_single_desc: '1张牌 · 每日指引 / 快速决策',
    spread_three_name: '三牌阵',
    spread_three_desc: '3张牌 · 过去·现在·未来',
    spread_celtic_name: '凯尔特十字',
    spread_celtic_desc: '10张牌 · 全面深入解读',
    spread_relation_name: '关系牌阵',
    spread_relation_desc: '6张牌 · 人际关系 / 感情',
    spread_choice_name: '二选一牌阵',
    spread_choice_desc: '5张牌 · 面临两个选择时',
    spread_five_name: '五张牌阵',
    spread_five_desc: '5张牌 · 通用问题深入分析',
    spread_horseshoe_name: '马蹄铁牌阵',
    spread_horseshoe_desc: '7张牌 · 全面生活指引',
    spread_career_name: '事业牌阵',
    spread_career_desc: '5张牌 · 工作/学业决策',
    spread_timeflow_name: '时间之流',
    spread_timeflow_desc: '5张牌 · 时间维度全面分析',
    spread_action_name: '问题行动结果',
    spread_action_desc: '3张牌 · 快速决策与行动指引',
    spread_mind_name: '心灵牌阵',
    spread_mind_desc: '5张牌 · 自我探索与内心成长',
    spread_fatewheel_name: '命运之轮',
    spread_fatewheel_desc: '5张牌 · 命运走向与转变',
    spread_monthly_name: '月运牌阵',
    spread_monthly_desc: '5张牌 · 本月运势指南',
    spread_souljourney_name: '灵魂旅程',
    spread_souljourney_desc: '9张牌 · 灵性成长与灵魂课题',
    spread_zodiac_name: '星座牌阵',
    spread_zodiac_desc: '12张牌 · 12宫位全面分析',
    spread_pastlife_name: '前世今生',
    spread_pastlife_desc: '5张牌 · 灵魂因果探索',
    spread_health_name: '健康牌阵',
    spread_health_desc: '5张牌 · 身心疗愈指引',
    spread_family_name: '家庭关系',
    spread_family_desc: '5张牌 · 家庭和谐分析',
    spread_weekly_name: '一周运势',
    spread_weekly_desc: '7张牌 · 本周每日运势指南',
    spread_creative_name: '灵感创作',
    spread_creative_desc: '5张牌 · 突破创作瓶颈',
    spread_finance_name: '财务投资',
    spread_finance_desc: '5张牌 · 财务决策指引',
    finance_tip: '适合投资理财决策、大额消费、买房/买车等财务决策前使用。',
    spread_lost_name: '失物寻找',
    spread_lost_desc: '5张牌 · 定位失物与寻找线索',
    lost_tip: '适合物品遗失后使用，帮助定位失物位置和判断是否还能找回。',
    spread_office_name: '办公室人际牌阵',
    spread_office_desc: '6张牌 · 职场人际关系分析',
    office_tip: '适合想了解办公室人际关系、改善同事关系、了解上司看法等场景。',
    spread_declutter_name: '断舍离',
    spread_declutter_desc: '4张牌 · 放下执念与清理',
    declutter_tip: '适合纠结是否要舍弃某人/某物/某种生活方式、想要清理能量场时使用。',
    spread_decisiontree_name: '决策树牌阵',
    spread_decisiontree_desc: '6张牌 · 短期与长期结果分析',
    decisiontree_tip: '适合面临重要决策时，全面分析不同选择的短期和长期影响，帮助你做出最明智的决定。',
    spread_dream_name: '梦境解读',
    spread_dream_desc: '5张牌 · 潜意识与梦境分析',
    dream_tip: '适合做了印象深刻、反复出现或令你困惑的梦之后使用。',
    placeholder_click_card: '点击上方卡牌查看详细解读',
    comprehensive_reading: '综合解读',
    mode_simple: '简单',
    mode_standard: '标准',
    mode_deep: '深度',
    btn_expand: '展开',
    btn_collapse: '收起',
    btn_back: '返回',
    btn_reshuffle: '重新占卜',
    btn_reinterpret: '重新解读',
    btn_share: '分享结果',
    btn_copy_result: '复制结果',
    history_title: '历史记录',
    history_hint: '查看过往的占卜记录',
    history_detail_title: '占卜详情',
    btn_back_to_list: '返回列表',
    btn_clear_history: '清空记录',
    history_empty: '暂无历史记录',
    fav_empty: '暂无收藏，点击卡牌预览中的 ☆ 可收藏喜欢的卡牌。',
    alert_copy_success: '占卜结果已复制到剪贴板！',
    alert_copy_fail: '复制失败，请手动复制结果',
    alert_draw_error: '抽牌出错: ',
    fav_title: '收藏夹',
    fav_hint: '你收藏的卡牌',
    loading_shuffle: '正在洗牌...',
    single_tip: '适合每日快速占卜，一张牌给出今日指引方向。',
    three_tip: '最经典的牌阵，分别解读过去的影响、现在的状态和未来的发展。',
    celtic_tip: '最全面的牌阵，适合重要问题深入解读，共10张牌覆盖问题各个层面。',
    relation_tip: '专门用于人际关系和感情问题，帮你理解双方状态与关系走向。',
    choice_tip: '当你在两个选项中犹豫不决时使用，帮助看清每个选项的可能结果。',
    five_tip: '通用深入分析牌阵，从问题核心到最终结果，层层递进。',
    horseshoe_tip: '马蹄铁形牌阵，覆盖过去到未来的完整时间线，适合全面了解局势。',
    career_tip: '专注事业与学业决策，从当前状况到未来发展，给出实用建议。',
    timeflow_tip: '从时间维度全面分析问题，看清事情的来龙去脉与可能走向。',
    action_tip: '简洁明了的三位牌阵，快速明确问题核心与最佳行动方向。',
    mind_tip: '适合自我探索与内心成长，帮助看清意识与潜意识、理想与现实。',
    fatewheel_tip: '适合询问某件事的命运走向，了解命运的转变点和隐藏机遇，帮助把握命运的方向。',
    monthly_tip: '适合月初或任意时间抽取，了解未来一个月各方面的运势走向和需要注意的事项。',
    souljourney_tip: '适合在灵性成长、内心探索、人生转折点时使用，帮助连接高我、看清灵魂课题与成长方向。',
    zodiac_tip: '对应黄道12宫位，全面分析生活各个领域。适合年度运势解读、全面了解自己或某人。',
    pastlife_tip: '探索前世对今生的影响，理解灵魂课题与成长方向。适合灵性探索。',
    health_tip: '关注身心健康，探寻身体与情绪的根本原因，给出疗愈方向。仅作辅助参考，不能替代专业医疗建议。',
    family_tip: '适合分析家庭关系、亲子关系、家庭氛围，帮助改善家庭和谐。',
    weekly_tip: '适合周日或周一抽取，了解未来一周每天的运势走向，提前做好规划与准备。',
    creative_tip: '适合创作者卡文、寻找灵感方向、或想要突破创作瓶颈时使用。',
    fortune_overall: '★ 综合运势',
    fortune_dimensions: '➡ 各维度评分',
    fortune_lucky_info: '💫 幸运信息',
    fortune_lucky_color: '幸运颜色',
    fortune_lucky_number: '幸运数字',
    fortune_lucky_direction: '幸运方位',
    fortune_dos_donts: '☯ 今日宜忌',
    fortune_tips: '💬 温馨提示',
    fortune_score_unit: '分',
    fortune_suitable: '宜：',
    fortune_avoid: '忌：',
    btn_number_gen: '命运数字',
    numgen_title: '命运数字生成器',
    numgen_hint: '让塔罗命运指引为你挑选幸运数字',
    numgen_min: '最小值',
    numgen_max: '最大值',
    numgen_generate: '生成命运数字',
    numgen_regenerate: '重新生成',
    numgen_your_number: '你的命运数字',
    numgen_reading_title: '✨ 塔罗命运指引',
    numgen_error_min: '最小值不能大于最大值',
    numgen_error_range: '请输入有效范围（最大值 - 最小值 ≥ 1）',
    numgen_copy: '复制数字',
    numgen_copy_all: '复制全部',
    numgen_quantity: '生成数量',
    numgen_numbers_label: '你的命运数字',
    numgen_history_title: '历史记录',
    numgen_clear_history: '清空历史',
    numgen_preset_lottery: '六合彩(1-49)',
    numgen_preset_dice: '🎲 骰子',
    numgen_preset_phone: '📱 手机尾号',
    numgen_preset_lucky: '🍀 幸运数字',
    numgen_preset_lottery2: '🎰 大乐透',
    numgen_generating: '⏳ 生成中...',
    numgen_error_quantity: '生成数量不能超过取值范围大小',
    btn_dilemma: '选择困难症',
    dilemma_title: '选择困难症',
    dilemma_hint: '输入两个选项，用猜拳、摇骰子或塔罗帮你做决定',
    dilemma_label_a: '🅰 选项 A',
    dilemma_label_b: '🅱 选项 B',
    dilemma_choose_method: '选择决定方式',
    dilemma_placeholder_a: '输入第一个选项...',
    dilemma_placeholder_b: '输入第二个选项...',
    dilemma_fate_btn: '让命运决定',
    dilemma_fate_sub: '随机用一种方式帮你做决定',
    dilemma_history_label: '历史',
    dilemma_rps: '猜拳决胜',
    dilemma_dice: '摇骰子',
    dilemma_tarot: '塔罗抽牌',
    dilemma_rps_title: '✊ 猜拳决胜',
    dilemma_dice_title: '🎲 摇骰子',
    dilemma_dice_high: '大（4-6）',
    dilemma_dice_low: '小（1-3）',
    dilemma_tarot_reading: '✨ 塔罗命运解读',
    dilemma_redo: '再来一次',
    dilemma_enter_both: '请输入两个选项',
    dilemma_you_chose: '你出了：',
    dilemma_computer_chose: '电脑出了：',
    dilemma_winner_is: '胜出选项：',
    dilemma_dice_point: '骰子点数：',
    dilemma_computer_roll: '电脑摇出：',
    dilemma_you_bet: '你押：',
    dilemma_dice_result_high: '大（4-6）',
    dilemma_dice_result_low: '小（1-3）',
    dilemma_winner_is: '胜出选项：',
    decision_tie: '平局，请再试一次！',
    difficulty_easy: '★☆☆',
    difficulty_medium: '★★☆',
    difficulty_hard: '★★★',
    filter_all: '全部',
    filter_advanced: '复杂',
    filter_favorites: '★ 收藏',
    spread_search_placeholder: '搜索牌阵...',
    cat_self: '自我成长',
    spread_love_name: '恋人牌阵',
    spread_love_desc: '7张牌 · 恋爱关系全面分析',
    spread_broken_name: '复合牌阵',
    spread_broken_desc: '6张牌 · 分手原因与复合可能',
    spread_yesno_name: '是否牌阵',
    spread_yesno_desc: '3张牌 · 是/否决策指引',
    spread_jobchange_name: '换工作牌阵',
    spread_jobchange_desc: '5张牌 · 跳槽/转行决策',
    spread_exam_name: '考试牌阵',
    spread_exam_desc: '5张牌 · 考试/面试结果预测',
    exam_tip: '适合考前或面试前占卜，了解结果、复习重点和注意事项。',
    spread_shadow_name: '阴影牌阵',
    spread_shadow_desc: '5张牌 · 自我整合与成长',
    spread_year_name: '年运牌阵',
    spread_year_desc: '7张牌 · 全年运势指引',
    love_tip: '适合正在恋爱或暧昧中的人，全面分析两人关系的各个层面。',
    broken_tip: '适合分手后想了解是否还有复合可能，或想看清分手原因时使用。',
    yesno_tip: '当你对一个决定犹豫不决，只想得到一个"是"或"否"的指引时使用。',
    jobchange_tip: '适合正在考虑换工作、转行或跳槽的人，帮助做出更明智的职业决策。',
    shadow_tip: '适合想要深入了解自己、进行心理成长或整合阴影面的人。',
    year_tip: '适合新年或生日时抽取，了解一整年的运势走向和各领域的发展。',
    spread_proscons_name: '利弊分析',
    spread_proscons_desc: '4张牌 · 支持与反对因素分析',
    spread_travel_name: '旅行牌阵',
    spread_travel_desc: '5张牌 · 出行决策与旅途指引',
    spread_lifepurpose_name: '人生使命',
    spread_lifepurpose_desc: '8张牌 · 探索天命与人生方向',
    proscons_tip: '适合需要对某件事做简单的利弊分析时使用，比是否牌阵更细致。',
    lifepurpose_tip: '适合在人生转折点、迷茫期或想要寻找人生意义和方向时使用，帮助探索天命与使命。',
    // 牌意
    btn_custom_meaning: '自定义牌意',
    cards_count_label: '张牌',
    // 综合解读标题
    theme_title: '★ 整体主题',
    relation_title: '⚙ 牌面关系分析',
    trend_title: '➡ 运势走向',
    advice_title: '⚡ 行动建议',
    // 整体主题
    theme_intro: '本次{0}抽取了 {1} 张牌，其中正位 {2} 张，逆位 {3} 张。',
    theme_has_majors: '大阿卡那牌出现了 {0} 张（{1}），预示本次问题涉及重要的生命课题或深层转变，值得认真对待。',
    theme_no_majors: '本次抽到的均为小阿卡那牌，问题更偏向日常生活层面的具体事务。',
    theme_dominant: '牌面中「{0}」元素最为突出，',
    theme_wands: '整体能量偏向行动、热情与创造力，是一个需要主动出击的时期。权杖牌组主导时，事情往往发展迅速，需要你果断决策并付诸行动。',
    theme_cups: '整体能量偏向情感、直觉与人际关系，需要更多关注内心感受。圣杯牌组主导时，情感因素对局势影响重大，建议倾听内心真实的声音。',
    theme_swords: '整体能量偏向思维、沟通与挑战，需要理性分析和清晰判断。宝剑牌组主导时，可能面临需要做出困难决定的局面，保持冷静和客观至关重要。',
    theme_pentacles: '整体能量偏向物质、事业与实际成果，需要脚踏实地的行动。星币牌组主导时，关注点在实际资源、财务状况或长期规划，适合制定具体可行的计划。',
    theme_mostly_reversed: '逆位牌占多数，提示当前局面可能存在阻碍、内在抗拒或需要调整方向；建议以更灵活的态度面对变化，审视哪些地方需要放手或转变视角。',
    theme_mostly_upright: '正位牌占多数，整体能量通畅，当前方向基本正确，保持信心继续推进即可。但也要注意不要因为顺利而忽视细节或变得过于自满。',
    theme_balanced: '正位与逆位牌数量相当，显示当前局势处于动态平衡中，既有支持的力量，也有需要留意的挑战。这种配置往往预示着需要权衡和整合不同面向。',
    // 元素互动
    theme_element_fire_water: '火元素（权杖）与水元素（圣杯）同时出现，提示需要在行动与情感之间找到平衡——既要勇于追求，也要关照内心感受。',
    theme_element_fire_air: '火元素（权杖）与风元素（宝剑）同时出现，行动力与思维能力都很强，但要注意避免想法太多导致行动分散。',
    theme_element_fire_earth: '火元素（权杖）与土元素（星币）同时出现，是很好的组合——热情有能力落地，想法可以变为现实。',
    theme_element_water_air: '水元素（圣杯）与风元素（宝剑）同时出现，情感与理性需要整合，可能因情绪波动影响判断，也可能因过度理性而忽视感受。',
    theme_element_water_earth: '水元素（圣杯）与土元素（星币）同时出现，情感与现实需要兼顾，可能在感情与物质安全之间寻求平衡。',
    theme_element_air_earth: '风元素（宝剑）与土元素（星币）同时出现，思维与实际行动需要结合，想法需要落地执行，避免只停留在计划阶段。',
    // 牌面关系分析
    relation_three_past: '过去（{0} {1}）为现在（{2} {3}）埋下了伏笔，而现在的能量将延续至未来（{4} {5}）。',
    relation_three_past_rev_now_up: '逆位的过去牌显示旧有模式正在被化解，现在是一个重新出发的契机。过去的阴影正在消散，光明即将到来。',
    relation_three_past_up_now_rev: '过去的顺利积累未能延续到现在，需要审视哪里出现了偏差。可能是忽略了某些细节，或者对形势变化准备不足。',
    relation_three_now_rev_future_up: '现在的困难是暂时的，未来有逆转向上的趋势，请坚持下去。当下的挑战是在为更好的未来铺路。',
    relation_you: '你（{0} {1}）与对方（{2} {3}）之间存在着明显的能量互动。',
    relation_same_rev: '双方的牌位状态相似，说明你们对这段关系的认知较为一致，但双方都可能带着某些内在抗拒或困惑。这种一致性反而可能让问题被忽视或压抑。',
    relation_same_up: '双方的牌位状态相似，说明你们对这段关系的认知较为一致，这是一段相对和谐、互相理解的关系。但也要注意是否因为太过相似而缺乏成长动力。',
    relation_diff: '你们的牌位状态不同，可能存在认知差异或不同步的情况，需要更多沟通。这种差异也可能是互补的机会，关键在于如何整合彼此的不同。',
    relation_choice: '选项A（{0} {1}）与选项B（{2} {3}）呈现出不同的能量走向。建议牌（{4} {5}）为你的决策提供了重要指引，请仔细体悟这张牌的启示。',
    relation_celtic: '十字中心的两张牌——当前情况（{0}）与挑战（{1}）——构成了问题的核心张力。过去的能量（{2}）仍在影响着现在，而最终结果牌（{3}）指明了这段旅程可能的归宿。',
    relation_suite_continue: '「{0}」与「{1}」同为{2}牌组，能量有延续性；',
    relation_rev_to_up: '从「{0}」的逆位转向「{1}」的正位，说明局势正在好转；',
    relation_up_to_rev: '从「{0}」的正位走向「{1}」的逆位，需要警惕潜在风险；',
    relation_smooth: '各张牌位之间的能量流转较为平稳，没有明显的冲突或突变，整体呈现出渐进式的发展轨迹。',
    relation_major_pair: '「{0}」与「{1}」都是大阿卡那牌，说明这两个位置之间的互动涉及深层的生命课题，值得深入反思。',
    relation_conflict: '「{0}」与「{1}」的能量似乎存在张力，可能需要在这两者之间找到平衡点。',
    // 运势走向
    trend_good: '牌面显示整体走势向好——前半段逆位较多，暗示起步或有阻碍；后半段正位增多，预示局面将逐步打开，坚持将有所收获。',
    trend_warning: '需要留意的走势——前半段相对顺利，但后半段逆位增多，提示后续可能出现变数或挑战，宜未雨绸缪、保持警觉。',
    trend_stable: '牌面显示能量相对平稳，没有剧烈的好转或恶化。这是一个沉淀和积累的时期，适合稳扎稳打，不宜冒进也不宜消极。',
    trend_major_turn: '「{0}」的出现预示着重大转折即将到来，请做好迎接变化的心理准备。',
    trend_improvement: '牌面显示能量逐步提升的趋势，从挑战走向突破，是一个成长和进化的过程。',
    trend_decline: '牌面显示能量逐步下降的趋势，从顺利走向挑战，需要提前做好准备，未雨绸缪。',
    // 行动建议
    advice_intro: '综合牌面指引，当前最值得采取的态度是：',
    advice_upright: '积极践行「{0}」的正位能量——{1} 在具体行动上，',
    advice_wands: '请主动出击，不要等待机会来找你。权杖牌组的行动力是你最大的优势，但要避免冲动和缺乏耐心。',
    advice_cups: '请倾听内心的声音，跟随直觉做出选择。圣杯牌组的情感智慧是你的指南针，但要避免情绪化和过度依赖他人评价。',
    advice_swords: '请理性分析局势，用清晰的思维指导行动。宝剑牌组的理性分析能力是你的强项，但要避免过于批判或冷酷无情。',
    advice_pentacles: '请专注实际步骤，一步一个脚印地推进计划。星币牌组的务实和耐心是你的基石，但要避免过于保守或抗拒变化。',
    advice_major: '请思考这张牌所传达的核心讯息，并将其融入你的决策中。大阿卡那牌带来的是灵魂层面的课题，需要你以更宏观的视角看待当前处境。',
    advice_reversed: '「{0}」逆位提醒你，{1} 建议先处理内在阻碍，再重新出发。逆位不是终点，而是需要调整方向或释放旧有模式的信号。',
    advice_many_reversed: '牌面逆位较多，建议给自己更多耐心和宽容，不要强求立竿见影的结果，允许事物按照自己的节奏展开。这也是一个向内探索、整合阴影面的好时机。',
    advice_major_present: '当前位置出现了大阿卡那牌「{0}」，这是灵魂层面的课题在当下显现。请特别关注这个位置的讯息，它往往指向你此阶段最重要的成长主题。',
    // Level 2 牌意组合解读
    combo_major_many: '本次出现了 {0} 张大阿卡那牌（{1}），说明当前问题触及灵魂层面的课题，不是一个可以轻易带过的议题。这些牌共同指向生命中需要深度转化和成长的领域。',
    combo_major_pair: '「{0}」与「{1}」同时出现，这两张大阿卡那牌形成强烈的能量共振。{2}',
    combo_light: '牌面中缺乏土元素（星币），可能意味着实际执行层面需要更多关注，想法容易停留在空想阶段。建议制定具体的行动计划。',
    combo_grounded: '牌面中土元素（星币）充足，显示你具备将想法落地的能力和资源。这是一个适合务实推进、积累成果的时期。',
    combo_air_water: '风元素（宝剑）与水元素（圣杯）同时活跃，显示理性分析与情感感受正在对话。这可能是一个需要整合头脑与心灵的时刻。',
      combo_fire_earth_block: '火元素（权杖）受到土元素（星币）的压制，热情可能被现实条件所阻碍。需要找到平衡点，既不放弃梦想，也能务实应对。',
      // 智能牌面关系分析
      relation_synergy: '牌面相生关系：{0}与{1}形成积极共振，能量相互增强。',
      relation_conflict: '牌面相克关系：{0}与{1}存在能量冲突，需要注意平衡。',
      relation_complementary: '牌面互补关系：{0}与{1}相互补充，提供全面视角。',
      relation_flow: '能量流动：从{0}到{1}，能量呈现{2}的趋势。',
      relation_tension: '牌面张力：{0}与{1}形成紧张关系，提示需要关注的内在冲突。',
      // 关系详细解释
      relation_explain_synergy: '【相生关系详解】{0}与{1}形成积极共振。{2}建议：{3}',
      relation_explain_conflict: '【相克关系详解】{0}与{1}存在能量冲突。{2}建议：{3}',
      relation_explain_complementary: '【互补关系详解】{0}与{1}相互补充。{2}建议：{3}',
      relation_explain_tension: '【张力关系详解】{0}与{1}形成紧张关系。{2}建议：{3}',
      relation_explain_flow: '【能量流动详解】从{0}到{1}，能量呈现{2}。{4}',
      // 综合解读摘要
      summary_title: '★ 综合解读摘要',
      summary_intro: '基于本次{0}牌面，核心摘要如下：',
      summary_major: '涉及{0}张重大命运牌（大阿卡那），',
      summary_mostly_reversed: '逆位牌占多数，提示需要调整和释放',
      summary_mostly_upright: '正位牌占多数，整体能量通畅',
      summary_balanced: '正逆位平衡，局势处于动态平衡中',
      // 关键词标签
      keyword_tags_title: '⚡ 牌面关键词',
      keyword_tags_intro: '以下关键词帮助你快速抓住牌面核心能量：',
      // 行动步骤清单
      action_steps_title: '✅ 行动步骤清单',
      action_steps_intro: '基于牌面指引，建议采取以下行动：',
      action_step_immediate: '立即行动',
      action_step_short_term: '短期行动（本周内）',
      action_step_medium_term: '中期行动（本月内）',
      action_step_long_term: '长期行动（未来三个月）',
      // 元素平衡分析
      element_balance_title: '⚖ 元素平衡分析',
      element_balance_intro: '牌面中四元素（火/水/风/土）的分布情况：',
      element_fire: '火（权杖）',
      element_water: '水（圣杯）',
      element_air: '风（宝剑）',
      element_earth: '土（星币）',
      element_dominant: '主导元素',
      element_missing: '缺失元素',
      element_balanced: '元素分布均衡',
      element_advice_dominant: '你的能量集中在{0}，建议：{1}',
      element_advice_missing: '缺少{0}元素，建议补充：{1}',
      // 扩展功能：历史分析、时间维度、性格分析
      extended_reading: '扩展解读',
      reading_patterns: '你的占卜模式',
      time_dimension: '时间维度',
      tarot_personality: '你的塔罗性格',
      frequent_cards: '频繁出现的牌：',
      element_distribution: '元素分布：',
      recent_trend: '近期趋势：',
      reversal_rate: '逆位率：',
      preferred_element: '偏好元素：',
      decision_style: '决策风格：',
      growth_stage: '成长阶段：',
      personalized_advice: '个性化建议：',
      time_of_day: '时辰能量：',
      day_energy: '星期能量：',
      date_energy: '日期能量：',
      lunar_phase: '月相：',
      type: '类型：',
      description: '描述：',
      advice: '建议：'
    },
  en: {
    welcome_title: 'Magic Tarot',
    welcome_subtitle: 'Explore the magical guidance of fate',
    label_deck: 'Deck:',
    deck_magic: 'Magic Theme',
    deck_rider: 'Rider-Waite',
    deck_marseille: 'Marseille',
    deck_thoth: 'Thoth',
    deck_angel: 'Angel',
    deck_healing: 'Healing Tarot',
    deck_osho: 'Osho Zen',
    label_lang: 'Language:',
    inst_start: 'Choose a spread to begin your magical journey',
    inst_click: 'Tap cards to view upright / reversed meaning',
    inst_reshuffle: 'Reshuffle anytime for a new reading',
    btn_history: 'View History',
    btn_favorites: 'Favorites',
    btn_daily_fortune: 'Daily Fortune',
    fortune_panel_title: '✨ Daily Fortune',
    fortune_loading: 'Reading today\'s fortune...',
    cat_simple: 'Beginner Classic',
    cat_relationship: 'Love & Relationship',
    cat_decision: 'Decision Analysis',
    cat_advanced: 'Advanced Topics',
    cat_fortune: 'Fortune Forecast',
    cat_life: 'Life Decisions',
    cat_career: 'Career & Study',
    cat_spiritual: 'Spiritual Growth',
    badge_recommended: '★ Recommended',
    spread_single_name: 'Single Card',
    spread_single_desc: '1 card · Daily guidance / Quick decision',
    spread_three_name: 'Three Cards',
    spread_three_desc: '3 cards · Past · Present · Future',
    spread_celtic_name: 'Celtic Cross',
    spread_celtic_desc: '10 cards · Comprehensive in-depth reading',
    spread_relation_name: 'Relationship',
    spread_relation_desc: '6 cards · Interpersonal / Love',
    spread_choice_name: 'Choice Spread',
    spread_choice_desc: '5 cards · When facing two options',
    spread_five_name: 'Five Cards',
    spread_five_desc: '5 cards · General in-depth analysis',
    spread_horseshoe_name: 'Horseshoe',
    spread_horseshoe_desc: '7 cards · Comprehensive life guidance',
    spread_career_name: 'Career Spread',
    spread_career_desc: '5 cards · Work / Study decisions',
    spread_timeflow_name: 'Time Flow',
    spread_timeflow_desc: '5 cards · Past to future analysis',
    spread_action_name: 'Problem-Action-Result',
    spread_action_desc: '3 cards · Quick decision & action guide',
    spread_mind_name: 'Mind Spread',
    spread_mind_desc: '5 cards · Self-exploration & inner growth',
    placeholder_click_card: 'Tap a card above to see detailed meaning',
    comprehensive_reading: 'Comprehensive Reading',
    mode_simple: 'Simple',
    mode_standard: 'Standard',
    mode_deep: 'Deep',
    btn_expand: 'Expand',
    btn_collapse: 'Collapse',
    btn_back: 'Back',
    btn_reshuffle: 'Redraw',
    btn_reinterpret: 'Reinterpret',
    btn_share: 'Share Result',
    btn_copy_result: 'Copy Result',
    history_title: 'History',
    history_hint: 'View past readings',
    history_detail_title: 'Reading Detail',
    btn_back_to_list: 'Back to List',
    btn_clear_history: 'Clear History',
    history_empty: 'No history yet',
    fav_empty: 'No favorites yet. Click ☆ in card preview to favorite a card.',
    alert_copy_success: 'Reading result copied to clipboard!',
    alert_copy_fail: 'Copy failed, please copy manually.',
    alert_draw_error: 'Card drawing error: ',
    fav_title: 'Favorites',
    fav_hint: 'Your favorite cards',
    loading_shuffle: 'Shuffling...',
    single_tip: 'Quick daily guidance. One card shows your direction for today.',
    three_tip: 'Classic three-card spread: past influence, current state, and future development.',
    celtic_tip: 'Most comprehensive spread with 10 cards covering all aspects of a situation.',
    relation_tip: 'Designed for relationships and emotions. Understand both sides and where the relationship is heading.',
    choice_tip: 'Use when hesitating between two options. Shows possible outcomes for each choice.',
    five_tip: 'General in-depth spread. From core issue to final outcome, layer by layer.',
    horseshoe_tip: 'Horseshoe-shaped spread covering the full timeline from past to future. Great for a complete overview.',
    career_tip: 'Focused on career and study decisions. From current status to future development, with practical advice.',
    timeflow_tip: 'Analyze the problem through time dimensions. See the past, present and future clearly.',
    action_tip: 'Simple three-card spread. Quickly clarify the core issue and best action direction.',
    mind_tip: 'For self-exploration and inner growth. Helps see consciousness, subconscious, ideal and reality.',
    spread_decisiontree_name: 'Decision Tree Spread',
    spread_decisiontree_desc: '6 cards · Short & Long-term Analysis',
    decisiontree_tip: 'Suitable for important decisions, comprehensively analyze the short-term and long-term impacts of different choices, helping you make the wisest decision.',
    spread_office_name: 'Office Interpersonal',
    spread_office_desc: '6 cards · Workplace relationship analysis',
    office_tip: 'Suitable for understanding office relationships, improving colleague relationships, understanding your supervisor\'s view, etc.',
    spread_lost_name: 'Lost Item',
    spread_lost_desc: '5 cards · Locate lost item & search clues',
    lost_tip: 'Suitable for use after losing an item. Helps locate the lost item and determine if it can be found.',
    spread_dream_name: 'Dream Interpretation',
    spread_dream_desc: '5 cards · Subconscious & dream analysis',
    dream_tip: 'Suitable for use after having an impressive, recurring, or confusing dream.',
    fortune_overall: '★ Overall Fortune',
    fortune_dimensions: '➡ Dimension Scores',
    fortune_lucky_info: '💫 Lucky Info',
    fortune_lucky_color: 'Lucky Color',
    fortune_lucky_number: 'Lucky Number',
    fortune_lucky_direction: 'Lucky Direction',
    fortune_dos_donts: '☯ Dos & Don\'ts',
    fortune_tips: '💬 Daily Tip',
    fortune_score_unit: 'pts',
    fortune_suitable: 'Do: ',
    fortune_avoid: 'Avoid: ',
    btn_number_gen: 'Fate Number',
    numgen_title: 'Fate Number Generator',
    numgen_hint: 'Let tarot fate guide you to your lucky number',
    numgen_min: 'Min',
    numgen_max: 'Max',
    numgen_generate: 'Generate Fate Number',
    numgen_regenerate: 'Regenerate',
    numgen_your_number: 'Your Fate Number',
    numgen_reading_title: '✨ Tarot Fate Guidance',
    numgen_error_min: 'Min cannot be greater than max',
    numgen_error_range: 'Please enter a valid range (max - min ≥ 1)',
    numgen_copy: 'Copy Number',
    numgen_copy_all: 'Copy All',
    numgen_quantity: 'Quantity',
    numgen_numbers_label: 'Your Fate Numbers',
    numgen_preset_lottery: 'Mark Six (1-49)',
    numgen_preset_dice: '🎲 Dice',
    numgen_preset_phone: '📱 Phone Number',
    numgen_preset_lucky: '🍀 Lucky Number',
    numgen_preset_lottery2: '🎰 Lottery',
    numgen_generating: '⏳ Generating...',
    numgen_error_quantity: 'Quantity cannot exceed the range size',
    numgen_history_title: 'History',
    numgen_clear_history: 'Clear History',
    btn_dilemma: 'Decision Helper',
    dilemma_title: 'Decision Helper',
    dilemma_hint: 'Enter two options, let Rock-Paper-Scissors, Dice, or Tarot help you decide',
    dilemma_label_a: 'Option A',
    dilemma_label_b: 'Option B',
    dilemma_choose_method: 'Choose a method',
    dilemma_placeholder_a: 'Enter the first option...',
    dilemma_placeholder_b: 'Enter the second option...',
    dilemma_fate_btn: 'Let Fate Decide',
    dilemma_fate_sub: 'A random method will be chosen',
    dilemma_history_label: 'History',
    dilemma_rps: 'Rock Paper Scissors',
    dilemma_dice: 'Roll Dice',
    dilemma_tarot: 'Tarot Draw',
    dilemma_rps_title: '✊ Rock Paper Scissors',
    dilemma_dice_title: '🎲 Roll Dice',
    dilemma_dice_high: 'High (4-6)',
    dilemma_dice_low: 'Low (1-3)',
    dilemma_tarot_reading: '✨ Tarot Fate Reading',
    dilemma_redo: 'Try Again',
    dilemma_enter_both: 'Please enter both options',
    dilemma_you_chose: 'You chose: ',
    dilemma_computer_chose: 'Computer chose: ',
    dilemma_winner_is: 'Winner: ',
    dilemma_dice_point: 'Dice roll: ',
    dilemma_computer_roll: 'Computer rolled: ',
    dilemma_you_bet: 'You bet: ',
    dilemma_dice_result_high: 'High (4-6)',
    dilemma_dice_result_low: 'Low (1-3)',
    dilemma_winner_is: 'Winner: ',
    decision_tie: 'It\'s a tie, try again!',
    difficulty_easy: '★☆☆',
    difficulty_medium: '★★☆',
    difficulty_hard: '★★★',
    filter_all: 'All',
    filter_advanced: 'Complex',
    filter_favorites: '★ Favorites',
    spread_search_placeholder: 'Search spreads...',
    cat_self: 'Self Growth',
    spread_love_name: 'Love Spread',
    spread_love_desc: '7 cards · Comprehensive relationship analysis',
    spread_broken_name: 'Reunion Spread',
    spread_broken_desc: '6 cards · Breakup reasons & reunion chance',
    spread_yesno_name: 'Yes/No Spread',
    spread_yesno_desc: '3 cards · Yes/No decision guidance',
    spread_jobchange_name: 'Job Change Spread',
    spread_jobchange_desc: '5 cards · Job hopping / Career change',
    spread_exam_name: 'Exam Spread',
    spread_exam_desc: '5 cards · Exam/interview result prediction',
    exam_tip: 'Suitable for divination before exams or interviews. Understand results, key review points, and things to note.',
    spread_shadow_name: 'Shadow Spread',
    spread_shadow_desc: '5 cards · Self-integration & growth',
    spread_year_name: 'Yearly Spread',
    spread_year_desc: '7 cards · Yearly fortune guidance',
    love_tip: 'For those in love or flirting, comprehensively analyzes all aspects of the relationship.',
    broken_tip: 'Use when you want to know if there is a chance to get back together, or to understand the reason for the breakup.',
    yesno_tip: 'When you are hesitant about a decision and just want a "yes" or "no" guidance.',
    jobchange_tip: 'For those considering job change, career switch, or job hopping, helps make wiser career decisions.',
    shadow_tip: 'For those who want to understand themselves deeply, do psychological growth or integrate shadow self.',
    year_tip: 'Draw at New Year or birthday to understand the year\'s fortune trend and development in all areas.',
    spread_proscons_name: 'Pros & Cons',
    spread_proscons_desc: '4 cards · Analyze pros and cons',
    spread_travel_name: 'Travel Spread',
    spread_travel_desc: '5 cards · Travel decision & guidance',
    travel_tip: 'Suitable for divination before traveling. Understand the overall travel situation, things to note, and travel gains.',
    spread_lifepurpose_name: 'Life Purpose',
    spread_lifepurpose_desc: '8 cards · Explore destiny & life direction',
    proscons_tip: 'Suitable for when you need to do a simple pros and cons analysis of something. More detailed than the Yes/No spread.',
    lifepurpose_tip: 'For life turning points, confused periods, or when wanting to find the meaning and direction of life. Helps explore destiny and mission.',
    spread_zodiac_name: 'Zodiac Spread',
    spread_zodiac_desc: '12 cards · Comprehensive life analysis',
    spread_pastlife_name: 'Past Life',
    spread_pastlife_desc: '5 cards · Soul karma exploration',
    spread_health_name: 'Health Spread',
    spread_health_desc: '5 cards · Body & mind healing guide',
    spread_family_name: 'Family Spread',
    spread_family_desc: '5 cards · Family harmony analysis',
    spread_weekly_name: 'Weekly Fortune',
    spread_weekly_desc: '7 cards · Daily fortune guide for the week',
    spread_creative_name: 'Creative Inspiration',
    spread_creative_desc: '5 cards · Break through creative block',
    spread_finance_name: 'Finance & Investment',
    spread_finance_desc: '5 cards · Financial decision guidance',
    weekly_tip: 'Suitable for drawing on Sunday or Monday to understand the fortune trend for each day of the coming week.',
    finance_tip: 'Suitable for investment decisions, large purchases, buying a house/car, etc. Helps you see financial risks and opportunities.',
    creative_tip: 'Suitable for creators facing writer\'s block, seeking inspiration direction, or wanting to break through creative bottlenecks.',
    spread_declutter_name: 'Declutter & Let Go',
    spread_declutter_desc: '4 cards · Release attachment & cleanse',
    declutter_tip: 'Suitable when you are torn about letting go of someone/something, or want to clear your energy field.',
    zodiac_tip: 'Corresponding to the 12 astrological houses, comprehensively analyzes all areas of life. Suitable for annual fortune reading.',
    pastlife_tip: 'Explore the influence of past lives on this life, understand soul lessons and growth direction. Suitable for spiritual exploration.',
    health_tip: 'Focus on physical and mental health, explore the root causes of body and emotions, and give healing directions. For reference only, cannot replace professional medical advice.',
    family_tip: 'Suitable for analyzing family relationships, parent-child relationships, family atmosphere. Helps improve family harmony.',
    // Card meaning
    btn_custom_meaning: 'Custom Meaning',
    cards_count_label: 'cards',
    // Comprehensive reading titles
    theme_title: '★ Overall Theme',
    relation_title: '⚙ Card Relationships',
    trend_title: '➡ Trend',
    advice_title: '⚡ Advice',
    // Overall theme
    theme_intro: 'In this {0} reading, {1} cards were drawn, with {2} upright and {3} reversed.',
    theme_has_majors: 'Major Arcana cards appeared ({0} cards: {1}). This indicates the question involves important life themes or deep transformations, which deserve serious attention.',
    theme_no_majors: 'All cards drawn are from the Minor Arcana, suggesting the question is more about daily life matters.',
    theme_dominant: 'The element of {0} is most prominent, ',
    theme_wands: 'indicating that overall energy leans toward action, passion and creativity. This is a time to take initiative.',
    theme_cups: 'indicating that overall energy leans toward emotions, intuition and relationships. More attention to inner feelings is needed.',
    theme_swords: 'indicating that overall energy leans toward thinking, communication and challenges. Rational analysis and clear judgment are needed.',
    theme_pentacles: 'indicating that overall energy leans toward material matters, career and practical results. Down-to-earth actions are required.',
    theme_mostly_reversed: 'Reversed cards are in the majority, suggesting that there may be obstacles, inner resistance or a need to adjust direction in the current situation; a more flexible attitude toward change is recommended.',
    theme_mostly_upright: 'Upright cards are in the majority, indicating that overall energy flows smoothly. The current direction is basically correct, just keep confidence and continue moving forward.',
    // Card relationships
    relation_three_past: 'The past ({0} {1}) sets the stage for the present ({2} {3}), and the present energy will continue into the future ({4} {5}).',
    relation_three_past_rev_now_up: 'The reversed past card shows old patterns are being resolved; now is a time for a fresh start.',
    relation_three_past_up_now_rev: 'The smooth accumulation from the past has not continued into the present. Review where deviations occurred.',
    relation_three_now_rev_future_up: 'Current difficulties are temporary; the future shows an upward trend. Please persevere.',
    relation_you: 'You ({0} {1}) and the other person ({2} {3}) have a clear energy interaction.',
    relation_same_rev: 'Both cards are in similar positions, indicating you share a relatively consistent understanding of this relationship, yet both may carry some inner resistance or confusion.',
    relation_same_up: 'Both cards are in similar positions, indicating you share a relatively consistent understanding of this relationship. This is a relatively harmonious and mutually understanding relationship.',
    relation_diff: 'Your card positions differ, which may indicate cognitive differences or being out of sync. More communication is needed.',
    relation_choice: 'Option A ({0} {1}) and Option B ({2} {3}) show different energy directions. The advice card ({4} {5}) provides important guidance for your decision; please reflect carefully on its message.',
    relation_celtic: 'The two cards at the center of the cross — Current Situation ({0}) and Challenge ({1}) — form the core tension of the issue. The energy of the past ({2}) still influences the present, while the final outcome card ({3}) points to the possible destination of this journey.',
    relation_suite_continue: '"{0}" and "{1}" are both from the {2} suit, showing energy continuity; ',
    relation_rev_to_up: 'From reversed "{0}" to upright "{1}", the situation is improving; ',
    relation_up_to_rev: 'From upright "{0}" to reversed "{1}", be alert to potential risks; ',
    relation_smooth: 'The energy flow between card positions is relatively stable, with no obvious conflicts or sudden changes, showing a gradual development trajectory.',
    // Trend
    trend_good: 'The spread shows an overall positive trend — more reversals in the first half suggest obstacles at the start; more upright cards in the second half indicate the situation will gradually open up. Persistence will bring rewards.',
    trend_warning: 'A trend to watch — the first half goes relatively smoothly, but more reversals in the second half suggest possible changes or challenges ahead. Prepare in advance and stay alert.',
    trend_stable: 'The spread shows relatively stable energy without dramatic improvement or deterioration. This is a period of accumulation and settling. Stay steady, neither rush nor be passive.',
    trend_major_turn: 'The appearance of "{0}" indicates a major turning point is coming. Be mentally prepared to embrace change.',
    // Advice
    advice_intro: 'Based on the overall spread guidance, the most worthwhile attitude to adopt now is: ',
    advice_upright: 'Actively embrace the upright energy of "{0}" — {1} In concrete actions, ',
    advice_wands: 'take the initiative and do not wait for opportunities to come to you.',
    advice_cups: 'listen to your inner voice and follow your intuition when making choices.',
    advice_swords: 'analyze the situation rationally and let clear thinking guide your actions.',
    advice_pentacles: 'focus on practical steps and advance your plan one step at a time.',
    advice_major: 'reflect on the core message this card conveys and integrate it into your decision-making.',
    advice_reversed: 'The reversed "{0}" reminds you that {1} It is suggested to resolve inner obstacles first before starting anew.',
    advice_many_reversed: 'With many reversed cards in the spread, it is recommended to give yourself more patience and tolerance. Do not demand immediate results; allow things to unfold at their own pace.',
    advice_major_present: 'A Major Arcana card "{0}" appears in the present position. This is a soul-level lesson manifesting in the now. Please pay special attention to the message of this position, as it often points to the most important growth theme of this stage.',
    // Level 2 牌意组合解读 (英文)
    combo_major_many: '{0} Major Arcana cards appeared ({1}), indicating the current question touches soul-level themes. These cards collectively point to areas of life requiring deep transformation and growth.',
    combo_major_pair: '"{0}" and "{1}" appear together. These two Major Arcana cards create strong energy resonance. {2}',
    combo_light: 'The spread lacks Earth element (Pentacles), which may mean the practical execution level needs more attention. Ideas can easily stay at the fantasy stage. It is recommended to formulate a concrete action plan.',
    combo_grounded: 'Earth element (Pentacles) is abundant in the spread, showing you have the ability and resources to ground ideas into reality. This is a period suitable for pragmatic progress and accumulating results.',
    combo_air_water: 'Air element (Swords) and Water element (Cups) are both active, showing rational analysis and emotional feelings are in dialogue. This may be a moment requiring integration of head and heart.',
    combo_fire_earth_block: 'Fire element (Wands) is blocked by Earth element (Pentacles). Passion may be hindered by realistic conditions. Need to find a balance point — neither giving up on dreams nor ignoring practical constraints.',
    // 智能牌面关系分析 (英文)
    relation_synergy: 'Card Synergy: {0} and {1} form positive resonance, with energies enhancing each other.',
    relation_conflict: 'Card Conflict: {0} and {1} have energy conflict, need to pay attention to balance.',
    relation_complementary: 'Card Complementary: {0} and {1} complement each other, providing a comprehensive perspective.',
    relation_flow: 'Energy Flow: From {0} to {1}, energy shows a trend of {2}.',
    relation_tension: 'Card Tension: {0} and {1} form a tense relationship, indicating inner conflict that needs attention.',
    // 关系详细解释 (英文)
    relation_explain_synergy: '【Synergy Relation Details】{0} and {1} form positive resonance. {2} Advice: {3}',
    relation_explain_conflict: '【Conflict Relation Details】{0} and {1} have energy conflict. {2} Advice: {3}',
    relation_explain_complementary: '【Complementary Relation Details】{0} and {1} complement each other. {2} Advice: {3}',
    relation_explain_tension: '【Tension Relation Details】{0} and {1} form a tense relationship. {2} Advice: {3}',
    relation_explain_flow: '【Energy Flow Details】From {0} to {1}, energy shows {2}. {3}',
    // 综合解读摘要
    summary_title: '★ Reading Summary',
    summary_intro: 'Based on the {0} spread, the core summary is as follows:',
    summary_major: 'Involves {0} major destiny cards (Major Arcana), ',
    summary_mostly_reversed: 'Majority of reversed cards, indicating need for adjustment and release',
    summary_mostly_upright: 'Majority of upright cards, overall energy flows smoothly',
    summary_balanced: 'Balanced upright and reversed cards, situation in dynamic equilibrium',
    // 关键词标签
    keyword_tags_title: '⚡ Card Keywords',
    keyword_tags_intro: 'These keywords help you quickly grasp the core energy of the spread:',
    // 行动步骤清单
    action_steps_title: '✅ Action Steps Checklist',
    action_steps_intro: 'Based on the spread guidance, it is recommended to take the following actions:',
    action_step_immediate: 'Immediate Action',
    action_step_short_term: 'Short-term Action (This Week)',
    action_step_medium_term: 'Medium-term Action (This Month)',
    action_step_long_term: 'Long-term Action (Next 3 Months)',
    // 元素平衡分析
    element_balance_title: '⚖ Element Balance Analysis',
    element_balance_intro: 'Distribution of the four elements (Fire/Water/Air/Earth) in the spread:',
    element_fire: 'Fire (Wands)',
    element_water: 'Water (Cups)',
    element_air: 'Air (Swords)',
    element_earth: 'Earth (Pentacles)',
    element_dominant: 'Dominant Element',
    element_missing: 'Missing Element',
    element_balanced: 'Balanced Element Distribution',
    element_advice_dominant: 'Your energy is concentrated in {0}, advice: {1}',
    element_advice_missing: 'Lacking {0} element, suggestion to supplement: {1}',
    // 扩展功能：历史分析、时间维度、性格分析
    extended_reading: 'Extended',
    reading_patterns: 'Your Reading Patterns',
    time_dimension: 'Time Dimension',
    tarot_personality: 'Your Tarot Personality',
    frequent_cards: 'Frequently Appearing Cards:',
    element_distribution: 'Element Distribution:',
    recent_trend: 'Recent Trend:',
    reversal_rate: 'Reversal Rate',
    preferred_element: 'Preferred Element:',
    decision_style: 'Decision Style:',
    growth_stage: 'Growth Stage:',
    personalized_advice: 'Personalized Advice:',
    time_of_day: 'Time of Day',
    day_energy: 'Day Energy',
    date_energy: 'Date Energy',
    lunar_phase: 'Lunar Phase',
    type: 'Type',
    description: 'Description',
    advice: 'Advice'
  }
};
