/**
 * 星辰塔罗牌数据 (Stellar Tarot)
 * 宇宙/星空主题，结合占星学元素
 * 每张牌对应星象、星座或行星能量
 */

const stellarCards = [
  // ============ 大阿卡纳 Major Arcana (22张) ============
  {
    id: 0, name: "愚者", originalName: "The Fool", suit: "major", element: "天王星",
    astro: "天王星 · 突破与自由",
    keywords: ["自由","冒险","新星","无限","零潜能"],
    uprightBrief: "在星河中自由启程", reversedBrief: "迷失在虚空之中",
    imageUrl: "icons/stellar/major-00.png",
    upright: "你是宇宙中一颗即将点燃的新星。愚者牌呼唤你放下所有既定轨道，跃入未知的星海。天王星的能量带来突如其来的突破——你不需要完整的星图才能出发，你的直觉就是最精准的导航。此刻，宇宙正在为你清空旧轨道，好让全新的频率进入。相信那股拉扯你向前的力量，那是你的灵魂在召唤自己回家。",
    reversed: "逆位的愚者提醒你：自由不等于迷失。你可能正在用「随性」来逃避真正的选择，或者盲目地跃入没有准备的空间。宇宙喜欢勇敢的灵魂，但也尊重那些懂得在跳跃之前校准方向的人。停下来，深呼吸，感受脚下的星球——你不需要抓住所有东西，但你需要知道自己在为什么而出发。",
    translations: { en: { upright: "You are a newborn star about to ignite in the cosmos. Uranus brings sudden breakthroughs — you don't need a complete star map. Your intuition IS the most precise navigation.", reversed: "The reversed Fool reminds you: freedom ≠ being lost. Stop, breathe, feel the planet under your feet." } }
  },
  {
    id: 1, name: "魔术师", originalName: "The Magician", suit: "major", element: "水星",
    astro: "水星 · 沟通与显化",
    keywords: ["显化","意志","水星","工具","合一"],
    uprightBrief: "水星之力显化万物", reversedBrief: "才能被遮蔽或误用",
    imageUrl: "icons/stellar/major-01.png",
    upright: "魔术师牌是宇宙能量在你手中的聚焦。水星在你的喉咙脉轮闪耀，你的话语正在创造现实。你拥有所有元素——火、水、风、土——全部在你的指尖等待指令。宇宙不会给你你「想要」的东西，它会回应你「对齐」的频率。此刻，你的意志与宇宙的意志正在合一，显化之门已经打开。",
    reversed: "逆位的魔术师是一面被遮蔽的镜子。你的才能还在，但你的信号被自我怀疑干扰了。你可能还在等待「完美时机」，但宇宙没有完美时机——只有此刻。水星的逆行能量可能让你误以为自己不够好，但真相是：你一直在等待一个不会到来的许可。你不需要被选中，你本身就是选择。",
    translations: { en: { upright: "The Magician is the focusing of cosmic energy through your hands. Mercury shines at your throat chakra — your words are creating reality.", reversed: "The reversed Magician is a clouded mirror. You don't need to be chosen; you ARE the choice." } }
  },
  {
    id: 2, name: "女祭司", originalName: "The High Priestess", suit: "major", element: "月亮",
    astro: "月亮 · 直觉与潜意识",
    keywords: ["直觉","月亮","神秘","内在知晓","寂静"],
    uprightBrief: "在月光中聆听内在之声", reversedBrief: "忽视直觉被表象迷惑",
    imageUrl: "icons/stellar/major-02.png",
    upright: "女祭司是月球暗面的守护者，她坐在意识与潜意识的边界上。月亮在你的直觉体中反射出真相——不是逻辑能到达的真相，而是「知道」本身。当你停止向外寻求答案，内在的寂静就会开口。她手中的卷轴写着未被说出的知识，只有当你足够安静，才能读懂。这不是关于「学习」，而是关于「记起」。你的灵魂记得一切。",
    reversed: "逆位的女祭司是你的直觉在敲门，而你假装不在家。你可能过于依赖理性分析，忽视了身体和梦境传递给你的信号。月亮的能量被遮蔽时，你会误把噪音当作指引。停下来，关掉所有输入——社交媒体、他人的意见、你自己的评判——然后听。答案一直在那里，在寂静的最深处。",
    translations: { en: { upright: "The High Priestess guards the dark side of the Moon. When you stop seeking answers outward, inner silence speaks. This is not about learning; it's about remembering.", reversed: "The reversed High Priestess is your intuition knocking and you pretending you're not home. Turn off all inputs and listen." } }
  },
  {
    id: 3, name: "女皇", originalName: "The Empress", suit: "major", element: "金星",
    astro: "金星 · 爱与丰盛",
    keywords: ["丰盛","金星","滋养","感官","美"],
    uprightBrief: "金星照耀丰盛之园", reversedBrief: "创造力枯竭自我忽视",
    imageUrl: "icons/stellar/major-03.png",
    upright: "女皇牌是金星的化身——爱与美的行星在你的能量场上绽放。她不是「拥有」丰盛，她是「成为」丰盛本身。金星在你的心轮旋转，提醒你：你值得占据空间，值得被滋养，值得享受存在于此的愉悦。宇宙是一张丰盛的网，你只需要停止推开它。当你善待自己，整个星系都会镜像你的自我价值。你不需要「赚得」爱，你本身就是爱。",
    reversed: "逆位的女皇是你的内在花园在呼救。你可能一直在给别人浇水，却让自己的根枯萎。金星的能量被阻塞时，你会觉得「不配」——不配休息，不配快乐，不配被爱。但宇宙没有「不配」这个概念。你是一颗星星，不管你是否发光，你都存在。重新连接你的感官——触摸泥土，闻一朵花，听风的声音——你的身体是宇宙的乐器，需要被调音。",
    translations: { en: { upright: "The Empress is Venus embodied. You don't need to 'earn' love; you ARE love. The universe is a net of abundance — you just need to stop pushing it away.", reversed: "The reversed Empress means your inner garden is crying for help. You are a star — whether you shine or not, you exist." } }
  },
  {
    id: 4, name: "皇帝", originalName: "The Emperor", suit: "major", element: "白羊座",
    astro: "白羊座 · 开创与领导",
    keywords: ["领导","白羊","结构","意志","稳定"],
    uprightBrief: "白羊之火建立新秩序", reversedBrief: "控制欲过强或缺乏方向",
    imageUrl: "icons/stellar/major-04.png",
    upright: "皇帝牌是白羊座的开创能量——火与行动的行星在你的太阳神经丛燃烧。他不是关于「控制」，而是关于「建立」。白羊座的原型能量教你：真正的领导力不是支配他人，而是为自己和他人创造安全的边界和结构。你的意志是一颗恒星的引力——当你的频率稳定，整个系统会自动围绕你排列。你不需要推开任何人，你只需要成为那个稳定的中心。",
    reversed: "逆位的皇帝是白羊之火失控了。你可能正在用强硬来掩盖恐惧，或者用「纪律」来虐待自己。真正的力量不需要证明自己——它只是「在」。如果你觉得必须控制一切才能感到安全，那你的地基其实在摇晃。停下来，回到你的身体。真正的权威来自内在的秩序，而不是外在的支配。",
    translations: { en: { upright: "The Emperor is Aries' pioneering energy. True leadership isn't dominating others; it's creating safe boundaries. Your will is a star's gravity.", reversed: "The reversed Emperor means Aries fire has gone out of control. True power doesn't need to prove itself — it simply IS." } }
  },
  {
    id: 5, name: "教皇", originalName: "The Hierophant", suit: "major", element: "金牛座",
    astro: "金牛座 · 传统与智慧",
    keywords: ["智慧","金牛","传承","教导","信仰"],
    uprightBrief: "金牛之土承载古老智慧", reversedBrief: "反叛传统或盲从权威",
    imageUrl: "icons/stellar/major-05.png",
    upright: "教皇牌是金牛座的稳固能量——土与智慧的行星在你的根基脉轮扎根。他不是「规定」你应该相信什么，而是邀请你与比自己更大的存在建立关系。金牛座的能量教你：真正的信仰不是盲从，而是在身体的智慧中找到神圣。你的细胞记得远古的知识——你不需要向外寻找上师，你的内在就有通往源头的天线。传统是有价值的，当它服务于你的进化时。",
    reversed: "逆位的教皇是金牛之土变得僵化了。你可能正在质疑所有传统，或者相反——盲目地服从某个权威。金牛座的逆行能量提醒你：真理不是「在外面」等你去找到的，它一直在你的体验之中。打破你认为「应该」相信的东西，然后看看什么还剩下。真正的教导不会要求你的服从，它会激发你的觉醒。",
    translations: { en: { upright: "The Hierophant is Taurus' steady energy. True faith isn't blind obedience; it's finding the sacred in the wisdom of your body.", reversed: "The reversed Hierophant means Taurus earth has become rigid. Truth isn't 'out there' waiting for you to find it — it's been in your experience all along." } }
  },
  {
    id: 6, name: "恋人", originalName: "The Lovers", suit: "major", element: "双子座",
    astro: "双子座 · 选择与合一",
    keywords: ["选择","双子","爱情","合一","价值"],
    uprightBrief: "双子之风做出灵魂之选", reversedBrief: "价值冲突或逃避选择",
    imageUrl: "icons/stellar/major-06.png",
    upright: "恋人牌是双子座的选择能量——风与沟通在你们之间流动。这不是关于「找到对的人」，而是关于「成为对的自己」。双子座的原型能量教你：爱是一面镜子，它映照出你需要整合的自己。每一次真正的选择都是一次小型的死亡和重生——你放下旧版本的自己，步入更真实的频率。宇宙不会替你选择，但它会确保你选择的后果精确地带你走向你的灵魂合约。",
    reversed: "逆位的恋人是双子之风变得混乱了。你可能正在用「选择」来逃避亲密，或者相反——用「融合」来逃避自己。双子座的逆行能量提醒你：你无法在他人身上找到你不愿意在自己身上承认的东西。停下来，深呼吸，问自己：如果不需要任何人的认可，我会选择什么？那个答案，就是你的北极星。",
    translations: { en: { upright: "The Lovers is Gemini's choice energy. Love is a mirror reflecting the parts of yourself you're here to integrate. The universe won't choose for you, but it ensures the consequences lead to your soul contract.", reversed: "The reversed Lovers means Gemini's air has become chaotic. You cannot find in another what you're unwilling to acknowledge in yourself." } }
  },
  {
    id: 7, name: "战车", originalName: "The Chariot", suit: "major", element: "巨蟹座",
    astro: "巨蟹座 · 意志与胜利",
    keywords: ["意志","巨蟹","胜利","前进","掌控"],
    uprightBrief: "巨蟹之壳驱动意志之车", reversedBrief: "方向失控或意志消沉",
    imageUrl: "icons/stellar/major-07.png",
    upright: "战车牌是巨蟹座的意志能量——水与保护的行星在你的心轮与太阳神经丛之间建立桥梁。战车不是关于「推」，而是关于「引导」。巨蟹座的原型能量教你：真正的力量是温柔而坚定的，像潮汐一样——它不强迫，但不可阻挡。你的情绪不是你的敌人，它们是你的燃料。当你学会与你的感受合作，而不是对抗它们，你就会发现你一直拥有的力量。胜利不属于最强的人，它属于最懂得以心驾驶的人。",
    reversed: "逆位的战车是巨蟹之水溢出车厢了。你可能正在用「前进」来逃避感受，或者相反——被情绪淹没而无法行动。巨蟹座的逆行能量提醒你：你不需要控制海洋，你只需要学会在波浪上冲浪。停下来，感受你的心——它在告诉你什么？真正的掌控不是没有恐惧，而是带着恐惧依然前行。",
    translations: { en: { upright: "The Chariot is Cancer's will energy. True power is gentle yet firm, like the tide — it doesn't force, but it's unstoppable. Victory belongs to those who know how to drive from the heart.", reversed: "The reversed Chariot means Cancer's water has overflowed the carriage. You don't need to control the ocean; you just need to learn to surf the waves." } }
  },
  {
    id: 8, name: "力量", originalName: "Strength", suit: "major", element: "狮子座",
    astro: "狮子座 · 勇气与内在力量",
    keywords: ["勇气","狮子","温柔","内在力量","耐心"],
    uprightBrief: "狮子之心以柔克刚", reversedBrief: "自我怀疑或内在恐惧",
    imageUrl: "icons/stellar/major-08.png",
    upright: "力量牌是狮子座的内在力量——火与心的行星在你的心轮燃烧。这不是关于「征服」，而是关于「转化」。狮子座的原型能量教你：真正的力量不是压制，而是驯服——你不需要打败你的恐惧，你只需要坐在它旁边，直到它变成你的坐骑。你的温柔是一种武器，它比任何刀剑都要锋利，因为它能融化最坚硬的盔甲。当你停止对抗自己，你的力量就会自然流动。",
    reversed: "逆位的力量是狮子之火被自我怀疑浇灭了。你可能觉得自己「不够强」，但真相是：你一直在用错误的标准衡量力量。狮子座的逆行能量提醒你：承认脆弱不是软弱，它是勇气的另一种形式。你不需要成为一座堡垒，你可以成为一片森林——柔软，但深深扎根。",
    translations: { en: { upright: "Strength is Leo's inner power. True strength isn't suppression; it's taming — you don't need to defeat your fear, you just need to sit beside it. Your gentleness is a weapon sharper than any sword.", reversed: "The reversed Strength means Leo's fire has been extinguished by self-doubt. Admitting vulnerability isn't weakness; it's courage in another form." } }
  },
  {
    id: 9, name: "隐士", originalName: "The Hermit", suit: "major", element: "处女座",
    astro: "处女座 · 内省与智慧",
    keywords: ["内省","处女","智慧","独处","寻求"],
    uprightBrief: "处女之静照亮内在之光", reversedBrief: "孤立自我或逃避世界",
    imageUrl: "icons/stellar/major-09.png",
    upright: "隐士牌是处女座的内省能量——土与智慧的行星在你的顶轮闪耀。这不是关于「逃避世界」，而是关于「回到中心」。处女座的原型能量教你：真正的智慧不是累积知识，而是剥离一切不属于你的东西。你的孤独是一间实验室，你在其中炼金——把痛苦变成洞察，把困惑变成清晰。当你愿意独自面对自己，宇宙就会把最深的真相放在你的膝盖上。不需要急着回来，你的光芒在寂静中最为明亮。",
    reversed: "逆位的隐士是处女之土变得孤立了。你可能正在用「独处」来逃避关系，或者用「忙碌」来逃避自己。处女座的逆行能量提醒你：内省的目的是回归，而不是永远离开。如果你发现自己被困在分析中而无法行动，那就是时候走出洞穴了。智慧如果不被分享，它就会变成毒药。",
    translations: { en: { upright: "The Hermit is Virgo's introspective energy. True wisdom isn't accumulating knowledge; it's stripping away everything that isn't you. Your solitude is a laboratory where you alchemize pain into insight.", reversed: "The reversed Hermit means Virgo earth has become isolated. The purpose of introspection is to return, not to leave forever. Wisdom unshared becomes poison." } }
  },
  {
    id: 10, name: "命运之轮", originalName: "Wheel of Fortune", suit: "major", element: "木星",
    astro: "木星 · 扩张与命运",
    keywords: ["命运","木星","循环","转变","机遇"],
    uprightBrief: "木星扩张命运之轮转动", reversedBrief: "抗拒变化或厄运感",
    imageUrl: "icons/stellar/major-10.png",
    upright: "命运之轮牌是木星的扩张能量——幸运与智慧的行星在你的整个星盘上画出一个圆。这不是关于「控制」会发生什么，而是关于「信任」发生的过程。木星的能量教你：你不是轮子的受害者，你是轮子上的一部分——当你接受上升，你也必须接受下降。每一次失去都是空间被清空以容纳新的，每一次结束都是轮子转动时发出的音乐。你不需要抓住任何东西，你只需要学会在转动中跳舞。",
    reversed: "逆位的命运之轮是木星的扩张变得失控了。你可能觉得命运在针对你，或者相反——觉得自己被运气抛弃了。木星的逆行能量提醒你：轮子没有「上」或「下」，它只有「动」。如果你觉得自己在底部，那意味着你即将上升——只要你不停下来挖洞。命运不是发生在你身上的事，它是你与宇宙共同创造的舞蹈。",
    translations: { en: { upright: "The Wheel of Fortune is Jupiter's expansive energy. You're not a victim of the wheel; you ARE part of the wheel. You don't need to hold onto anything; you just need to learn to dance while turning.", reversed: "The reversed Wheel means Jupiter's expansion has gone out of control. The wheel has no 'up' or 'down' — it only has 'moving.'" } }
  },
  {
    id: 11, name: "正义", originalName: "Justice", suit: "major", element: "天秤座",
    astro: "天秤座 · 平衡与因果",
    keywords: ["正义","天秤","平衡","因果","真相"],
    uprightBrief: "天秤之衡裁决因果之链", reversedBrief: "逃避责任或不公感",
    imageUrl: "icons/stellar/major-11.png",
    upright: "正义牌是天秤座的平衡能量——风与和谐的行星在你的心轮与喉轮之间建立天秤。这不是关于「惩罚」，而是关于「回应」。天秤座的原型能量教你：宇宙是一本精密的账本，每一笔都被记录，但不是为了审判你，而是为了让你看到你种下的是什么。你的每一个选择都在创造你的未来——不是作为惩罚，而是作为教学工具。当你接受责任，你就重新获得了力量。正义不是「外面」的东西，它是你与真相的关系。",
    reversed: "逆位的正义是天秤之秤失衡了。你可能觉得生活对你不公平，或者相反——你正在逃避某个你需要承担的责任。天秤座的逆行能量提醒你：你无法欺骗宇宙，你只能欺骗自己。如果你觉得被不公正地对待，问问自己：我在哪里对自己不公正？真正的平衡不是所有东西都平等，而是所有东西都在正确的位置。",
    translations: { en: { upright: "Justice is Libra's balancing energy. The universe is a precise ledger — not to judge you, but to show you what you've planted. Justice isn't 'out there'; it's your relationship with truth.", reversed: "The reversed Justice means Libra's scale has tipped. You cannot cheat the universe; you can only cheat yourself." } }
  },
  {
    id: 12, name: "倒吊人", originalName: "The Hanged Man", suit: "major", element: "海王星",
    astro: "海王星 · 牺牲与超越",
    keywords: ["超越","海王星","暂停","换个角度","臣服"],
    uprightBrief: "海王之星倒悬以见真相", reversedBrief: "拖延抗拒或虚假牺牲",
    imageUrl: "icons/stellar/major-12.png",
    upright: "倒吊人牌是海王星的超越能量——灵性与消融的行星邀请你倒过来看待一切。这不是关于「受苦」，而是关于「换个角度」。海王星的原型能量教你：有时候，为了得到答案，你必须停止寻找。你的「暂停」不是失败，它是一次重新校准。当你愿意放下「必须怎样」的执念，宇宙就会给你一个你从未想过的答案。倒吊人是一面镜子——他问你：如果你不再试图控制结果，你会看到什么？",
    reversed: "逆位的倒吊人是海王之星变得混乱了。你可能正在用「等待」来拖延真正的决定，或者用「牺牲」来换取爱。海王星的逆行能量提醒你：真正的臣服不是放弃你的力量，而是停止与生命对抗。如果你觉得自己被困住了，问问自己：我在坚持什么其实已经不需要了？有时候，放手是你能做的最勇敢的事。",
    translations: { en: { upright: "The Hanged Man is Neptune's transcendent energy. Sometimes, to get the answer, you must stop looking. The Hanged Man asks: if you no longer tried to control the outcome, what would you see?", reversed: "The reversed Hanged Man means Neptune's star has become cloudy. True surrender isn't giving up your power; it's stopping the fight with life. Sometimes, letting go is the bravest thing you can do." } }
  },
  {
    id: 13, name: "死神", originalName: "Death", suit: "major", element: "天蝎座",
    astro: "天蝎座 · 转化与重生",
    keywords: ["转化","天蝎","结束","重生","释放"],
    uprightBrief: "天蝎之毒蜕变为新生", reversedBrief: "抗拒改变或执着过去",
    imageUrl: "icons/stellar/major-13.png",
    upright: "死神牌是天蝎座的转化能量——水与深度的行星在你的海底轮和生殖轮之间引发地震。这不是关于「结束」，而是关于「蜕变」。天蝎座的原型能量教你：你无法重生，如果你不愿意先死掉。每一次真正的转变都要求你放下旧身份——不是因为它不好，而是因为你已经超出了它。死神不是敌人，他是助产士——他帮助你把不再服务于你的东西排出来，好让新的你能够出生。你不需要害怕，你只需要呼吸，然后放手。",
    reversed: "逆位的死神是天蝎之水变得停滞了。你可能正在抗拒一个必要的结束，或者用「执着」来避免重生。天蝎座的逆行能量提醒你：你无法阻止轮子转动，你只能决定是跳上去还是被拖在后面。如果你觉得自己正在死而不得，问问自己：我在抓着什么其实已经死了？有时候，最深的爱就是放手。",
    translations: { en: { upright: "Death is Scorpio's transformative energy. You cannot be reborn if you're unwilling to die first. Death isn't the enemy; he's a midwife — he helps you expel what no longer serves you.", reversed: "The reversed Death means Scorpio water has become stagnant. You cannot stop the wheel from turning. Sometimes the deepest love is letting go." } }
  },
  {
    id: 14, name: "节制", originalName: "Temperance", suit: "major", element: "射手座",
    astro: "射手座 · 融合与耐心",
    keywords: ["融合","射手","耐心","调和","长远"],
    uprightBrief: "射手之箭射中融合之杯", reversedBrief: "失衡急躁或缺乏远见",
    imageUrl: "icons/stellar/major-14.png",
    upright: "节制牌是射手座的融合能量——火与远见的行星在你的整个能量场上画出一道彩虹。这不是关于「妥协」，而是关于「炼金」。射手座的原型能量教你：你不需要在你灵魂的不同部分之间做选择——你可以把她们全部融合成一种全新的颜色。节制是一杯茶——你需要让茶叶在水中充分展开，才能尝到真正的味道。你的急躁是你在试图加速一个需要时间的进程。信任 timing，宇宙从来没有迟到。",
    reversed: "逆位的节制是射手之火变得散乱了。你可能正在试图把不兼容的东西强行融合，或者相反——在不同部分之间割裂自己。射手座的逆行能量提醒你：你无法在所有方向上同时前进。如果你觉得自己的生活失去了和谐，那可能是因为你在试图取悦所有人。回到你的中心，然后问问自己：什么对我来说是真的？那个答案，就是你的罗盘。",
    translations: { en: { upright: "Temperance is Sagittarius' blending energy. You don't need to choose between different parts of your soul — you can blend them all into a completely new color. Trust timing; the universe is never late.", reversed: "The reversed Temperance means Sagittarius fire has become scattered. You cannot move in all directions simultaneously. Return to your center and ask: what is true for me?" } }
  },
  {
    id: 15, name: "恶魔", originalName: "The Devil", suit: "major", element: "摩羯座",
    astro: "摩羯座 · 束缚与物质",
    keywords: ["束缚","摩羯","物质","欲望","觉醒"],
    uprightBrief: "摩羯之链实为自我所铸", reversedBrief: "挣脱束缚或逃避物质",
    imageUrl: "icons/stellar/major-15.png",
    upright: "恶魔牌是摩羯座的物质能量——土与结构的行星在你的海底轮发出挑战。这不是关于「邪恶」，而是关于「认同」。摩羯座的原型能量教你：你最大的监狱不是外面的任何东西，它是你对自己的故事。恶魔是你的阴影——那些你不愿意承认的欲望、恐惧和需要。当你把阴影带到光中，它就会失去力量。你看，链子没有锁——它们只是看起来像锁。你一直都有钥匙，你只是从来没有试着转动它。",
    reversed: "逆位的恶魔是摩羯之土崩塌了。你可能正在经历一次觉醒，看到了自己曾经被束缚的方式，或者相反——用「灵性」来逃避物质现实。摩羯座的逆行能量提醒你：你无法通过否认物质来超越物质。你的身体、你的需求、你的欲望——它们都是神圣的。整合它们，而不是排斥它们。当你停止与自己的黑暗作战，它就会变成你的盟友。",
    translations: { en: { upright: "The Devil is Capricorn's material energy. Your biggest prison isn't anything outside; it's the story you tell about yourself. The chains aren't locked — they just look like they are. You've always had the key.", reversed: "The reversed Devil means Capricorn earth has crumbled. You cannot transcend matter by denying it. Your body, your needs, your desires — they are all sacred." } }
  },
  {
    id: 16, name: "塔", originalName: "The Tower", suit: "major", element: "火星",
    astro: "火星 · 突变与解放",
    keywords: ["突变","火星","崩塌","真相","解放"],
    uprightBrief: "火星之火焚毁虚假之塔", reversedBrief: "内在崩塌或抗拒突变",
    imageUrl: "icons/stellar/major-16.png",
    upright: "塔牌是火星的突变能量——行动与突破的行星用一把火把你的虚假结构烧成灰烬。这不是关于「破坏」，而是关于「解放」。火星的能量教你：有时候，只有当你愿意放下你辛苦建造的东西，真正的你才能出现。塔是一栋你为自己建造的监狱——它看起来像保护，但实际上它是限制。当火星来敲门，它不是来惩罚你，它是来解放你。灰烬是肥沃的——它们会养育全新的你。",
    reversed: "逆位的塔是火星之火在内部燃烧了。你可能正在经历内在的崩塌，但试图向外表现得一切正常，或者相反——用「危机」来避免面对真正的问题。火星的逆行能量提醒你：你无法阻止地震，你只能决定是在废墟上跳舞还是在废墟下被埋。如果生活正在崩塌，那可能是因为它一直都是纸牌屋。让它与真相。",
    translations: { en: { upright: "The Tower is Mars' mutation energy. Sometimes, only when you're willing to release what you've worked hard to build can your true self emerge. The Tower is a prison you built for yourself. Mars isn't here to punish you; it's here to free you.", reversed: "The reversed Tower means Mars fire is burning internally. If your life is crumbling, it may have been a house of cards all along. Let it fall." } }
  },
  {
    id: 17, name: "星辰", originalName: "The Star", suit: "major", element: "水瓶座",
    astro: "水瓶座 · 希望与灵感",
    keywords: ["希望","水瓶","灵感","疗愈","信念"],
    uprightBrief: "水瓶之星照耀希望之河", reversedBrief: "失望绝望或失去信念",
    imageUrl: "icons/stellar/major-17.png",
    upright: "星辰牌是水瓶座的希望能量——风与创新的行星在你的顶轮和眉心轮之间洒下星光。这不是关于「愿望」，而是关于「对齐」。水瓶座的原型能量教你：你是宇宙的一部分，就像一颗星星是银河的一部分。你的存在本身就在发出信号——当你对齐你的真实频率，整个宇宙都会来帮助你。星辰是一面镜子——她让你看到你一直都是星星，不管你是否发光。你的伤痕不是缺陷，它们是光进入你的地方。",
    reversed: "逆位的星辰是水瓶之风变得冰冷了。你可能正在失去希望，或者相反——用「灵性 bypass」来避免感受痛苦。水瓶座的逆行能量提醒你：你不需要「积极思考」来配得上美好。你的黑暗和你的光明都是神圣的。如果你觉得自己「永远找不到对的人」，那可能是因为你在寻找一个不存在的完美。放下那个幻象，然后看看真实的人。真实比完美性感得多。",
    translations: { en: { upright: "The Star is Aquarius' hope energy. You are part of the universe, just as a star is part of the galaxy. Your scars aren't flaws; they're where the light enters you.", reversed: "The reversed Star means Aquarius wind has become cold. Real is so much sexier than perfect." } }
  },
  {
    id: 18, name: "月亮", originalName: "The Moon", suit: "major", element: "双鱼座",
    astro: "双鱼座 · 幻想与恐惧",
    keywords: ["幻想","双鱼","恐惧","直觉","潜意识"],
    uprightBrief: "双鱼之梦映照潜意识之月", reversedBrief: "释放幻觉或直面恐惧",
    imageUrl: "icons/stellar/major-18.png",
    upright: "月亮牌是双鱼座的幻想能量——水与梦境的行星在你的海底轮和眉心轮之间投射出幻象。这不是关于「虚假」，而是关于「象征」。双鱼座的原型能量教你：你的恐惧不是你的敌人，它们是你的导游——它们告诉你你在哪里还没有完全信任生命。月亮是潜意识的镜子——它映照出你还没有准备好在阳光下看到的东西。你不需要打败你的恐惧，你只需要带着它们一起走。当你停止逃离阴影，你就会发现它一直在保护你。",
    reversed: "逆位的月亮是双鱼之水变得清澈了。你可能正在从幻觉中醒来，或者相反——用「理性」来逃避感受。双鱼座的逆行能量提醒你：你无法用头脑来导航心灵的水域。如果你觉得自己「永远找不到对的人」，那可能是因为你在寻找一个不存在的完美。放下那个幻象，然后看看真实的人。真实比完美性感得多。",
    translations: { en: { upright: "The Moon is Pisces' fantasy energy. Your fears aren't your enemies; they're your tour guides. When you stop running from shadows, you'll discover they've been protecting you.", reversed: "The reversed Moon means Pisces water has become clear. Real is so much sexier than perfect." } }
  },
  {
    id: 19, name: "太阳", originalName: "The Sun", suit: "major", element: "太阳",
    astro: "太阳 · 生命力与喜悦",
    keywords: ["喜悦","太阳","活力","成功","清晰"],
    uprightBrief: "太阳之光融化一切阴影", reversedBrief: "暂时阴云或内在小孩受伤",
    imageUrl: "icons/stellar/major-19.png",
    upright: "太阳牌是太阳本身的生命力——不是一颗行星，而是你星系的中心。这不是关于「快乐」，而是关于「存在」。太阳的能量教你：你不需要「做到」任何东西才值得被爱——你的存在本身就是一份礼物。太阳是一面放大镜——它照亮一切，包括你试图隐藏的东西。但你不需要隐藏，因为太阳爱你的全部——你的光明和你的黑暗，你的成功和你的失败。当你允许自己被看见，你的整个生命就会开始发光。",
    reversed: "逆位的太阳是云层暂时遮住了光。你可能正在经历一段阴郁的时期，或者相反——用「快乐」来掩盖真正的感受。太阳的逆行能量提醒你：你不需要「固定」任何东西。阴云是暂时的，就像夜晚是暂时的一样。如果你觉得自己「永远找不到对的人」，那可能是因为你在寻找一个不存在的完美。放下那个幻象，然后看看真实的人。真实比完美性感得多。",
    translations: { en: { upright: "The Sun is the life force of the Sun itself. You don't need to 'achieve' anything to be worthy of love — your existence itself is a gift. When you allow yourself to be seen, your whole life begins to shine.", reversed: "The reversed Sun means clouds have temporarily blocked the light. Real is so much sexier than perfect." } }
  },
  {
    id: 20, name: "审判", originalName: "Judgement", suit: "major", element: "冥王星",
    astro: "冥王星 · 觉醒与召唤",
    keywords: ["觉醒","冥王星","召唤","重生","使命"],
    uprightBrief: "冥王之星吹响觉醒之号", reversedBrief: "自我怀疑或逃避召唤",
    imageUrl: "icons/stellar/major-20.png",
    upright: "审判牌是冥王星的觉醒能量——转化与重生的行星在你的整个存在中引发共振。这不是关于「审判」，而是关于「召唤」。冥王星的能量教你：你没有被审判，你被召唤。你的灵魂正在召唤你成为你已经是的那个人。审判是一声号角——它唤醒你从沉睡中醒来，记起你是谁。你不需要「变得」更好，你只需要记起你一直都是谁。你的过去不是你的定义，它是你的训练场。",
    reversed: "逆位的审判是冥王之星变得沉默了。你可能正在忽视你灵魂的召唤，或者用「自我怀疑」来逃避你的使命。冥王星的逆行能量提醒你：你无法永远沉睡。你的灵魂不会放弃你，它会一直敲门，直到你打开。如果你觉得自己没有「听到」召唤，那可能是因为你在用噪音淹没它。停下来，然后听——那声号角一直在吹，从你的第一天开始。",
    translations: { en: { upright: "Judgement is Pluto's awakening energy. You're not being judged; you're being called. Your soul is calling you to become who you already are. Your past isn't your definition; it's your training ground.", reversed: "The reversed Judgement means Pluto's star has gone silent. That trumpet has been blowing since your first day. Stop and listen." } }
  },
  {
    id: 21, name: "世界", originalName: "The World", suit: "major", element: "土星",
    astro: "土星 · 完成与整合",
    keywords: ["完成","土星","整合","成就","旅程"],
    uprightBrief: "土星之环圆满宇宙之舞", reversedBrief: "未完成或抗拒圆满",
    imageUrl: "icons/stellar/major-21.png",
    upright: "世界牌是土星的完成能量——责任与时间的行星在你的整个能量场上画出一个完整的圆。这不是关于「终点」，而是关于「整合」。土星的能量教你：每一次结束都是一个新的开始——你不是在「到达」，你是在「成为」。世界是一面镜子——它映照出你已经走了多远，以及你已经成为谁。你不需要「找到」自己，你一直在「创造」自己。你的旅程不是线性的，它是螺旋的——你每次回到同一点，但你在一个更高的层面上。",
    reversed: "逆位的世界是土星之环出现了裂缝。你可能觉得自己的旅程还没有完成，或者相反——害怕完成因为那意味着要面对「接下来是什么」。土星的逆行能量提醒你：你不需要「完美」才能圆满。你的不完美就是你的完美——它们是让你的光能够透出来的裂缝。如果你觉得自己还没有「准备好」，那你可能永远都不会觉得准备好了。完美是一个陷阱，完成是一个选择。",
    translations: { en: { upright: "The World is Saturn's completion energy. Every ending is a new beginning — you're not 'arriving'; you're 'becoming.' Your journey isn't linear; it's spiral.", reversed: "The reversed World means Saturn's ring has developed a crack. Your imperfections ARE your perfection — they're the cracks that let your light through. Perfection is a trap; completion is a choice." } }
  },

  // ============ 小阿卡纳 - 权杖 Wands (14张) ============
  { id:"W1", name:"权杖王牌", originalName:"Ace of Wands", suit:"wands", element:"火", astro:"火星 · 开创之火", keywords:["灵感爆发","新行动","创意种子","火之潜能"], uprightBrief:"火星之火点燃新创意", reversedBrief:"灵感受阻或行动延迟", imageUrl:"icons/stellar/wands-01.png", upright:"权杖王牌是火星的开创之火——纯然的行动能量从星空中降临。这不是关于「计划」，而是关于「点燃」。火星的能量教你：真正的创意不需要理由，它只需要一个出口。你的灵感是一颗流星——如果你不抓住它，它就会消失在大气层中。你不需要知道目的地，你只需要开始。火会找到自己的路。", reversed:"逆位的权杖王牌是火星之火被浇灭了。你可能有很多想法，但没有一个被点燃。火星的逆行能量提醒你：灵感不会等你「准备好」。如果你一直在推迟行动，那你的火就会冷却。捡起一根火柴，然后点燃什么——哪怕是很小的东西。行动会召唤更多的行动。", translations:{en:{upright:"The Ace of Wands is Mars' initiating fire. Your inspiration is a meteor — if you don't catch it, it will disappear. You don't need to know the destination; you just need to begin.", reversed:"The reversed Ace of Wands means Mars' fire has been extinguished. Inspiration won't wait for you to be 'ready.' Pick up a match and light something."}} },
  { id:"W2", name:"权杖二", originalName:"Two of Wands", suit:"wands", element:"火/土", astro:"火星 · 规划与远见", keywords:["规划","远见","选择","全球视野"], uprightBrief:"火星之眼眺望新大陆", reversedBrief:"恐惧选择或规划过度", imageUrl:"icons/stellar/wands-02.png", upright:"权杖二牌是火星的远见能量——你在地平线上看到了新的可能性。这不是关于「知道答案」，而是关于「敢于想象」。火星的能量教你：规划不是限制，它是给行动一个方向。你手中握着一颗星球——你可以选择留在熟悉的海岸，或者启航去未知的水域。恐惧是好的，它说明你在意。但不要让恐惧替你做决定。", reversed:"逆位的权杖二是火星之眼变得模糊了。你可能因为害怕错误而拒绝选择，或者相反——用「分析」来拖延行动。火星的逆行能量提醒你：没有「完美」的选择，只有「被行动赋予生命」的选择。如果你一直在权衡利弊，那你可能永远都不会出发。选一个方向，然后走。路会在你脚下展开。", translations:{en:{upright:"The Two of Wands is Mars' visionary energy. Fear is okay; it means you care. But don't let fear make decisions for you.", reversed:"The reversed Two of Wands means Mars' eye has become blurry. There's no 'perfect' choice, only choices brought to life by action."}} },
  { id:"W3", name:"权杖三", originalName:"Three of Wands", suit:"wands", element:"火", astro:"火星 · 扩张与远航", keywords:["扩张","远航","合作","等待","进展"], uprightBrief:"火星之舟驶向远方星辰", reversedBrief:"延迟受阻或缺乏远见", imageUrl:"icons/stellar/wands-03.png", upright:"权杖三牌是火星的扩张能量——你的船已经启航，正在驶向远方的星辰。这不是关于「控制」结果，而是关于「信任」过程。火星的能量教你：你已经做了你能做的一切，现在需要让宇宙来完成剩下的。你的耐心不是被动的——它是积极的等待，就像农夫等待种子发芽。你种下的已经在成长，即使你还看不到芽。", reversed:"逆位的权杖三是火星之舟遇到了逆风。你可能觉得进展太慢，或者相反——你的计划被外部因素延迟了。火星的逆行能量提醒你：延迟不是拒绝，它是宇宙在重新安排时间线。如果你的船还没有到港，那可能是因为港口还在建造中。信任 timing，你的星图正在被精确地绘制。", translations:{en:{upright:"The Three of Wands is Mars' expansion energy. What you've planted is already growing, even if you can't see the sprout yet.", reversed:"The reversed Three of Wands means Mars' ship has encountered headwinds. Delay isn't rejection; it's the universe rearranging timelines."}} },
  { id:"W4", name:"权杖四", originalName:"Four of Wands", suit:"wands", element:"火/土", astro:"金星/火星 · 庆祝与稳定", keywords:["庆祝","稳定","家庭","和谐","里程碑"], uprightBrief:"金星与火星共舞庆丰收", reversedBrief:"不稳定或缺乏庆祝", imageUrl:"icons/stellar/wands-04.png", upright:"权杖四牌是金星与火星的共舞——庆祝与稳定的能量在你的生活中开花。这不是关于「完美」，而是关于「欣赏」。金星的能量教你：你不需要等到「全部完成」才庆祝。每一个里程碑都值得被标记，每一次胜利都值得被分享。你的喜悦是一面磁铁——它吸引更多的理由来庆祝。停下来，看看你已经走了多远。你做得很好。", reversed:"逆位的权杖四是金星与火星的舞步乱了。你可能觉得「还没有准备好庆祝」，或者相反——你的基础还不够稳定。金星的逆行能量提醒你：你不需要「完美」的家或生活才能感到安稳。如果你的庆祝被延迟了，那可能是因为你在等待一个不会到来的完美时刻。现在就庆祝，用你拥有的东西。", translations:{en:{upright:"The Four of Wands is Venus and Mars dancing together. Every milestone deserves to be marked. Stop and see how far you've come. You've done well.", reversed:"The reversed Four of Wands means Venus and Mars' dance steps have become messy. Celebrate now, with what you have."}} },
  { id:"W5", name:"权杖五", originalName:"Five of Wands", suit:"wands", element:"火", astro:"火星 · 竞争与冲突", keywords:["竞争","冲突","挑战","成长","活力"], uprightBrief:"火星之火花在竞争中闪耀", reversedBrief:"逃避冲突或内部混乱", imageUrl:"icons/stellar/wands-05.png", upright:"权杖五牌是火星的竞争能量——冲突和竞争是你的成长催化剂。这不是关于「打败」别人，而是关于「发现」你自己的极限。火星的能量教你：竞争是一面镜子，它映照出你有多想要某样东西。你的火花在摩擦中变得更亮——没有挑战，你就会变得迟钝。所以，当冲突出现时，不要退缩。深呼吸，然后加入舞蹈。争论不是战争，它是能量的交换。", reversed:"逆位的权杖五是火星之火花变成了内耗。你可能正在避免必要的冲突，或者相反——被卷入没有意义的争斗中。火星的逆行能量提醒你：不是每一场战斗都值得你的能量。如果你发现自己在内耗，那可能是因为你在与自己的影子作战。把能量转向外部，去做一些需要勇气的事。", translations:{en:{upright:"The Five of Wands is Mars' competitive energy. Your spark becomes brighter through friction. When conflict arises, don't retreat. Arguing isn't war; it's an exchange of energy.", reversed:"The reversed Five of Wands means Mars' spark has turned into internal burnout. Not every battle is worth your energy."}} },
  { id:"W6", name:"权杖六", originalName:"Six of Wands", suit:"wands", element:"火", astro:"木星/火星 · 胜利与认可", keywords:["胜利","认可","进步","自信","公众"], uprightBrief:"木星扩张火星的胜利游行", reversedBrief:"骄傲自大或缺乏认可", imageUrl:"icons/stellar/wands-06.png", upright:"权杖六牌是木星扩张火星的胜利能量——你的努力得到了认可和庆祝。这不是关于「自夸」，而是关于「接受赞美」。木星的能量教你：你值得被看见，你值得被认可。你的胜利不是「运气」，它是你投入的能量回流。当你允许自己被庆祝时，你就在给其他人许可去庆祝他们自己的胜利。所以，抬起头来，微笑，接受掌声。你赢得了它。", reversed:"逆位的权杖六是木星之扩张变成了膨胀。你可能过于在意他人的认可，或者相反——觉得自己的成就「不够好」而不值得被认可。木星的逆行能量提醒你：你的价值不需要外部验证。如果你觉得没有被认可，那可能是因为你在用别人的尺子量自己。放下比较，然后为自己的胜利感到骄傲——不管别人怎么看。", translations:{en:{upright:"The Six of Wands is Jupiter expanding Mars' victory energy. You deserve to be seen, to be acknowledged. When you allow yourself to be celebrated, you're giving others permission to celebrate too.", reversed:"The reversed Six of Wands means Jupiter's expansion has turned into inflation. Your worth doesn't need external validation."}} },
  { id:"W7", name:"权杖七", originalName:"Seven of Wands", suit:"wands", element:"火", astro:"火星 · 坚守与防卫", keywords:["坚守","防卫","挑战","毅力","边界"], uprightBrief:"火星之盾坚守高地", reversedBrief:"放弃抵抗或过度防御", imageUrl:"icons/stellar/wands-07.png", upright:"权杖七牌是火星的坚守能量——你站在一个有挑战的位置上，但你有能力守住它。这不是关于「战斗」，而是关于「立场」。火星的能量教你：你不需要攻击别人来保护自己，你只需要站稳脚跟。你的边界是你的责任——没有人能替你守护它们。当你说「不」时，你实际上是在说「是」给你真正重要的事情。所以，守住你的高地，你不需要为你的边界道歉。", reversed:"逆位的权杖七是火星之盾出现了裂缝。你可能觉得自己无法再坚持了，或者相反——你在过度防御，把每个人当作敌人。火星的逆行能量提醒你：放弃不是失败，有时候它是智慧。如果你一直在打一场不再服务于你的战斗，那可能是时候放下了。选择你的战斗，然后把能量留给真正重要的事情。", translations:{en:{upright:"The Seven of Wands is Mars' stand-your-ground energy. Your boundaries are your responsibility. You don't need to apologize for your boundaries.", reversed:"The reversed Seven of Wands means Mars' shield has developed a crack. Giving up isn't failure; sometimes it's wisdom. Choose your battles."}} },
  { id:"W8", name:"权杖八", originalName:"Eight of Wands", suit:"wands", element:"火", astro:"水星/火星 · 快速与流动", keywords:["快速","流动","消息","旅行","同步"], uprightBrief:"水星之风加速火星之箭", reversedBrief:"延迟混乱或缺乏方向", imageUrl:"icons/stellar/wands-08.png", upright:"权杖八牌是水星加速火星的快速能量——事情正在加速，消息正在飞来，旅行正在安排。这不是关于「控制」速度，而是关于「跟上」节奏。水星的能量教你：当你与宇宙同步时，一切都会变得流畅。你的行动不是孤立的——它们是一张更大的网的一部分。所以，当能量开始流动时，跳上去。不要问太多问题，只要享受旅程。速度是一种魔法。", reversed:"逆位的权杖八是水星之风变成了飓风。你可能觉得事情失去了控制，或者相反——一切都在延迟，没有进展。水星的逆行能量提醒你：有时候「慢下来」是你能做的最快的事。如果你觉得混乱，那可能是因为你在试图控制每一片叶子。放手，让风来决定方向。混乱之后就是清晰。", translations:{en:{upright:"The Eight of Wands is Mercury accelerating Mars' swift energy. When energy starts flowing, hop on. Don't ask too many questions; just enjoy the journey. Speed is a kind of magic.", reversed:"The reversed Eight of Wands means Mercury's wind has become a hurricane. Sometimes 'slowing down' is the fastest thing you can do. After chaos comes clarity."}} },
  { id:"W9", name:"权杖九", originalName:"Nine of Wands", suit:"wands", element:"火", astro:"火星 · 坚韧与警惕", keywords:["坚韧","警惕","恢复","边界","经验"], uprightBrief:"火星之伤化作坚韧之盾", reversedBrief:"偏执恐惧或耗尽精力", imageUrl:"icons/stellar/wands-09.png", upright:"权杖九牌是火星的坚韧能量——你已经经历了很多，但你还在站着。这不是关于「创伤」，而是关于「智慧」。火星的能量教你：你的伤痕不是你的缺陷，它们是你的勋章。每一次你站起来，你就变得更强大。你的警惕不是偏执——它是你从经验中获得的智慧。所以，深呼吸，看看你已经走了多远。你比你认为的更强大。你不需要完美才能继续，你只需要不愿意放弃。", reversed:"逆位的权杖九是火星之伤变成了偏执。你可能觉得自己「不能再承受更多了」，或者相反——你在预期伤害，即使它不在那里。火星的逆行能量提醒你：过去不等于未来。如果你一直在用旧的故事来解释新的体验，那你可能错过了奇迹。放下你的盔甲，即使只是片刻。你不需要一直准备战斗。", translations:{en:{upright:"The Nine of Wands is Mars' resilience energy. Your scars aren't your flaws; they're your medals. You're stronger than you think. You don't need to be perfect to continue.", reversed:"The reversed Nine of Wands means Mars' wounds have turned into paranoia. The past doesn't equal the future. Put down your armor, even for a moment."}} },
  { id:"W10", name:"权杖十", originalName:"Ten of Wands", suit:"wands", element:"火/土", astro:"土星/火星 · 负担与责任", keywords:["负担","责任","压力","完成","释放"], uprightBrief:"土星之重压在火星之肩", reversedBrief:"无法放手或逃避责任", imageUrl:"icons/stellar/wands-10.png", upright:"权杖十牌是土星压在火星上的负担能量——你承担了太多，你的肩膀在痛。这不是关于「坚强」，而是关于「智慧」。土星的能量教你：你不需要独自承担一切。有时候，放下不是失败，它是给自己空间去呼吸。你的责任是你的选择——但如果它们开始压垮你，那可能是因为你试图控制你不负责的东西。所以，看看你手中的权杖，问问自己：这些中有多少是我真正需要携带的？", reversed:"逆位的权杖十是土星之重变得无法承受了。你可能觉得自己无法再走一步了，或者相反——你在拒绝放下你不需要携带的东西。土星的逆行能量提醒你：你不需要「完成」一切才能休息。如果你觉得被困在负担下，那可能是因为你在等待一个不会到来的许可来放下。给自己那个许可。现在。你值得休息。", translations:{en:{upright:"The Ten of Wands is Saturn pressing down on Mars. You don't need to carry everything alone. Look at the wands in your hands and ask: how many of these do I actually need to carry?", reversed:"The reversed Ten of Wands means Saturn's weight has become unbearable. Give yourself that permission. Now. You deserve rest."}} },
  { id:"W11", name:"权杖侍从", originalName:"Page of Wands", suit:"wands", element:"火", astro:"火星/水星 · 探索与消息", keywords:["探索","消息","冒险","热情","自由精神"], uprightBrief:"火星之子带来冒险消息", reversedBrief:"延迟消息或缺乏方向", imageUrl:"icons/stellar/wands-11.png", upright:"权杖侍从牌是火星的探索能量——一个充满热情的消息或机会正在来到你身边。这不是关于「知道答案」，而是关于「保持好奇」。火星的能量教你：你不需要有计划才能探索。有时候，最美好的冒险开始于「我想知道如果我……」。你的自由精神是你的超级力量——它让你看到别人错过的可能性。所以，当一个新想法出现时，追随它。即使它看起来「不实际」。魔法从不「实际」。", reversed:"逆位的权杖侍从是火星之子变得犹豫了。你可能有一个想法，但没有采取行动，或者相反——你在冲动地跳跃，没有方向。火星的逆行能量提醒你：探索不是漫无目的。如果你觉得自己失去了方向，那可能是因为你在试图同时去所有地方。选择一个火花，然后追随它。专注不是限制，它是给火焰一个燃烧的机会。", translations:{en:{upright:"The Page of Wands is Mars' exploratory energy. Sometimes the most beautiful adventures begin with 'I wonder what would happen if I...' Magic is never 'practical.'", reversed:"The reversed Page of Wands means Mars' child has become hesitant. Exploration isn't aimless. Pick one spark and follow it."}} },
  { id:"W12", name:"权杖骑士", originalName:"Knight of Wands", suit:"wands", element:"火", astro:"火星/木星 · 行动与冒险", keywords:["行动","冒险","急躁","魅力","速度"], uprightBrief:"火星骑士疾驰向新冒险", reversedBrief:"鲁莽或延迟行动", imageUrl:"icons/stellar/wands-12.png", upright:"权杖骑士牌是火星的行动能量——你充满了热情和冲动，准备疾驰向新的冒险。这不是关于「思考」，而是关于「做」。火星的能量教你：有时候，你需要先跳跃，然后在空中建立翅膀。你的魅力是你的武器——它打开别人紧紧关闭的门。所以，当你感到那股冲动时，相信它。即使别人说你「太冲动了」。他们可能永远不会理解你的火，但你自己理解。燃烧吧。", reversed:"逆位的权杖骑士是火星之马失去了控制。你可能行动过于冲动，导致了可以避免的错误，或者相反——你在犹豫，错过了时机。火星的逆行能量提醒你：速度不是一切，方向也很重要。如果你觉得自己跑得太快了，那可能是因为你在试图逃离某些东西。停下来，深呼吸，然后检查你的罗盘。冒险是美好的，但知道自己为什么冒险是智慧。", translations:{en:{upright:"The Knight of Wands is Mars' action energy. Sometimes you need to jump first and build wings in mid-air. When you feel that impulse, trust it. Burn.", reversed:"The reversed Knight of Wands means Mars' horse has lost control. Speed isn't everything; direction matters too. Check your compass."}} },
  { id:"W13", name:"权杖王后", originalName:"Queen of Wands", suit:"wands", element:"火", astro:"火星/金星 · 魅力与自信", keywords:["热情","自信","魅力","创造力","独立"], uprightBrief:"火星王后以热情统治", reversedBrief:"缺乏自信或过度支配", imageUrl:"icons/stellar/wands-13.png", upright:"权杖王后牌是火星的魅力能量——你充满了自信和热情，你的存在本身就在启发他人。这不是关于「控制」，而是关于「启发」。火星的能量教你：真正的力量不是推，而是吸引。你的创造力是一团不灭的火——它从你的伤口中燃烧出来，把痛苦变成美。所以，当你感到自我怀疑时，记住：你的火不是你的 ego，它是你的灵魂。你被设计成发光。所以，发光吧。即使它让一些人感到刺眼。", reversed:"逆位的权杖王后是火星之火变成了嫉妒或控制欲。你可能觉得自己「不够好」，或者相反——你在试图控制每一个火焰。火星的逆行能量提醒你：真正的自信不是「没有不安全感」，而是带着不安全感依然行动。如果你觉得自己失去了光芒，那可能是因为你在试图偷别人的火。回到你自己的祭坛，然后重新点燃你自己的蜡烛。你的火是独一无二的，它不需要看起来像任何其他人的。", translations:{en:{upright:"The Queen of Wands is Mars' charismatic energy. Your creativity is an unextinguishable fire. You were designed to shine. So shine. Even if it's blinding to some.", reversed:"The reversed Queen of Wands means Mars' fire has turned into jealousy. Return to your own altar and relight your own candle. Your fire is unique."}} },
  { id:"W14", name:"权杖国王", originalName:"King of Wands", suit:"wands", element:"火", astro:"火星/太阳 · 远见与领导力", keywords:["远见","领导力","企业家","魅力","行动"], uprightBrief:"火星国王以远见领导", reversedBrief:"专制或缺乏远见", imageUrl:"icons/stellar/wands-14.png", upright:"权杖国王牌是火星的远见能量——你是一个天生的领导者，你的愿景能够启发他人跟随。这不是关于「支配」，而是关于「鼓舞」。火星的能量教你：真正的领导者不是那些大声说话的人，而是那些愿意先走的人。你的企业家精神是你的天赋——你看得到可能性，在哪里别人只看到障碍。所以，当你有一个愿景时，相信它。即使没有人理解它。他们不需要理解它，他们只需要看到你相信它。你的信念是最好的营销。", reversed:"逆位的权杖国王是火星之国王变得专制了。你可能试图控制每一个细节，或者相反——你的愿景变得如此宏大，以至于你失去了与地面的联系。火星的逆行能量提醒你：真正的领导力包括倾听。如果你觉得自己需要一直是对的，那你可能已经停止学习了。一个真正的国王知道他不知道的比他知道的多。谦虚不是弱点，它是智慧的开始。", translations:{en:{upright:"The King of Wands is Mars' visionary energy. A true leader isn't the one who speaks loudest, but the one willing to walk first. Your belief is the best marketing.", reversed:"The reversed King of Wands means Mars' king has become authoritarian. A true king knows he knows less than he knows. Humility isn't weakness; it's the beginning of wisdom."}} },

  // ============ 小阿卡纳 - 圣杯 Cups (14张) ============
  { id:"C1", name:"圣杯王牌", originalName:"Ace of Cups", suit:"cups", element:"水", astro:"金星 · 爱的开端", keywords:["新情感","爱","喜悦","直觉","灵感"], uprightBrief:"金星之爱注满新圣杯", reversedBrief:"情感受阻或内在空虚", imageUrl:"icons/stellar/cups-01.png", upright:"圣杯王牌是金星的爱之能量——新的情感正在从你的心中涌出。这不是关于「找到」爱，而是关于「成为」爱。金星的能量教你：你的心不是一个容器，它是一口井——当你从它喝水时，它会被补充。你的情感是神圣的，它们不是你的弱点，它们是你的超能力。所以，当爱来临时，打开你的门。即使你过去被伤过。你的心被设计成爱，就像肺被设计成呼吸一样。", reversed:"逆位的圣杯王牌是金星之爱被阻塞了。你可能觉得自己的情感「不安全」，或者相反——你在过度付出，以至于自己变空了。金星的逆行能量提醒你：你无法从空杯中倾倒。如果你觉得情感受阻，那可能是因为你在试图控制爱应该如何表现。放下你的期望，然后让爱以它自己的方式到来。爱有它自己的智慧。", translations:{en:{upright:"The Ace of Cups is Venus' love energy. Your heart was designed to love, just as lungs were designed to breathe.", reversed:"The reversed Ace of Cups means Venus' love is blocked. You cannot pour from an empty cup. Let love come in its own way."}} },
  { id:"C2", name:"圣杯二", originalName:"Two of Cups", suit:"cups", element:"水", astro:"金星/月亮 · 和谐与吸引", keywords:["和谐","吸引","合作","关系","平等"], uprightBrief:"金星与月亮共酿爱的圣杯", reversedBrief:"关系失衡或误解", imageUrl:"icons/stellar/cups-02.png", upright:"圣杯二牌是金星和月亮的共酿——两个能量场正在和谐地融合。这不是关于「得到」某人，而是关于「分享」自己。金星的能量教你：真正的关系是两面镜子，它们互相映照出对方的美丽。你的吸引力不是你的技巧，它是你的频率。所以，当你感到与某人「连接」时，相信那种感觉。即使它没有「意义」。灵魂不需要理由来认出彼此。", reversed:"逆位的圣杯二是金星与月亮的酒变酸了。你可能觉得关系「不平等」，或者相反——你在过度妥协自己来取悦对方。金星的逆行能量提醒你：你无法在别人身上找到你不愿意给自己东西。如果你觉得关系失衡，那可能是因为你在忽视自己的需要。回到你自己的杯子里，然后重新装满它。一个满的杯子才能与另一个满的杯子碰杯。", translations:{en:{upright:"The Two of Cups is Venus and Moon brewing together. Soul don't need reasons to recognize each other.", reversed:"The reversed Two of Cups means Venus and Moon's wine has turned sour. You cannot find in another what you're unwilling to give yourself."}} },
  { id:"C3", name:"圣杯三", originalName:"Three of Cups", suit:"cups", element:"水", astro:"水星/金星 · 庆祝与友谊", keywords:["庆祝","友谊","社交","欢乐","团聚"], uprightBrief:"水星与金星举杯共庆", reversedBrief:"过度放纵或社交孤立", imageUrl:"icons/stellar/cups-03.png", upright:"圣杯三牌是水星和金星的举杯——庆祝、友谊和欢乐的能量正在流动。这不是关于「逃避」，而是关于「连接」。水星的能量教你：笑声是最好的药，朋友是最好的镜子。你的社交生活不是「浪费时间」，它是你的营养。所以，当你被邀请去庆祝时，去吧。即使你「太忙了」。忙碌是一个糟糕的借口，喜悦是一个很好的理由。你的朋友们在你的生活中有目的，让他们靠近。", reversed:"逆位的圣杯三是水星与金星的派对失去了控制。你可能过度放纵了，或者相反——你在孤立自己，错过了与朋友的欢乐时光。水星的逆行能量提醒你：孤独不会治愈任何东西，它只会放大你的内在声音（它可能不是最友善的）。如果你觉得自己「不值得」被围绕，那可能是因为你在听旧的故事。你值得快乐，你值得朋友，你值得被爱。现在就去告诉某人你关心他们。", translations:{en:{upright:"The Three of Cups is Mercury and Venus raising a toast. When you're invited to celebrate, go. Your friends have a purpose in your life.", reversed:"The reversed Three of Cups means Mercury and Venus' party has gone out of control. Loneliness doesn't heal anything. Go tell someone you care about them."}} },
  { id:"C4", name:"圣杯四", originalName:"Four of Cups", suit:"cups", element:"水", astro:"月亮 · 沉思与重新评估", keywords:["沉思","重新评估","不满","机会","觉醒"], uprightBrief:"月亮照见被忽视的圣杯", reversedBrief:"觉醒与新机会", imageUrl:"icons/stellar/cups-04.png", upright:"圣杯四牌是月亮的沉思能量——你正在重新评估什么是真正重要的。这不是关于「抑郁」，而是关于「深化」。月亮的能量教你：有时候，你需要说「不」给某些机会，才能为真正的机会腾出空间。你的不满不是你的缺陷，它是你的指南针——它在告诉你，你正在超出你曾经想要的东西。所以，当你感到「不感兴趣」时，不要评判自己。你可能只是在等待正确的杯子被递给你。", reversed:"逆位的圣杯四是月亮之不满变成了觉醒。你可能终于看到了你一直在忽视的机会，或者相反——你意识到你在拒绝好东西，仅仅因为你「不觉得值得」。月亮的逆行能量提醒你：你值得好的东西，仅仅因为你存在。如果你觉得自己「不值得」这个机会，那可能是因为你在用旧的故事来解释新的现实。放下那个故事，然后接受这个杯子。它是给你的。", translations:{en:{upright:"The Four of Cups is the Moon's contemplative energy. Your dissatisfaction isn't your flaw; it's your compass.", reversed:"The reversed Four of Cups means the Moon's dissatisfaction has turned into awakening. You deserve good things simply because you exist."}} },
  { id:"C5", name:"圣杯五", originalName:"Five of Cups", suit:"cups", element:"水", astro:"冥王星/月亮 · 悲伤与恢复", keywords:["悲伤","失落","遗憾","恢复","原谅"], uprightBrief:"冥王星之泪洗去失落", reversedBrief:"从悲伤中恢复", imageUrl:"icons/stellar/cups-05.png", upright:"圣杯五牌是冥王星和月亮的悲伤能量——你正在经历一个失落，你的心在痛。这不是关于「弱」，而是关于「人性」。冥王星的能量教你：悲伤不是问题，它是过程。你的眼泪不是你的缺陷，它们是你的河流——它们正在把你带到新的地方。所以，当你感到悲伤时，让它来。不要试图「积极思考」它 away。悲伤需要被感受，才能被释放。你失去的已经失去了，但你还在这里。而你在这里，就是奇迹。", reversed:"逆位的圣杯五是冥王之星开始移动了。你可能正在从悲伤中恢复，或者相反——你意识到你在执着于一个你已经无法改变的东西。冥王星的逆行能量提醒你：原谅不是「原谅那个人」，它是「释放你自己」。如果你觉得自己被困在遗憾中，那可能是因为你在用你的过去来定义你的未来。放下那个定义。你不仅仅是一个你失去东西的人，你是一个正在学习如何再次爱的人。", translations:{en:{upright:"The Five of Cups is Pluto and Moon's grief energy. Your tears aren't your flaw; they're your river. You lost what you lost, but you're still here. And you being here is a miracle.", reversed:"The reversed Five of Cups means Pluto's star has started moving again. Forgiveness isn't 'forgiving that person'; it's 'releasing yourself.'"}} },
  { id:"C6", name:"圣杯六", originalName:"Six of Cups", suit:"cups", element:"水", astro:"月亮/金星 · 怀旧与纯真", keywords:["怀旧","童年","回忆","分享","纯真"], uprightBrief:"月亮与金星唤醒童年圣杯", reversedBrief:"困在过去或天真过度", imageUrl:"icons/stellar/cups-06.png", upright:"圣杯六牌是月亮和金星的怀旧能量——美好的回忆正在温暖你的心。这不是关于「活在过去」，而是关于「从过去中汲取甜蜜」。月亮的能量教你：你的童年不是「已过去的东西」，它是你的一部分——它一直在影响你如何爱、如何信任、如何做梦。所以，当你感到怀旧时，让它来。那些回忆是你灵魂的锚——它们提醒你你曾经是谁，这样你就不会在风暴中迷失。", reversed:"逆位的圣杯六是月亮与金星变得沉溺了。你可能困在过去的回忆中，无法享受现在，或者相反——你在过度天真，忽视了过去的教训。月亮的逆行能量提醒你：怀旧不是家，它是一张明信片。如果你觉得自己「以前更快乐」，那可能是因为你在用玫瑰色的眼镜看过去。过去有它的美丽，但它也有它的痛苦。两者都是真的。接受整个故事，然后继续前进。", translations:{en:{upright:"The Six of Cups is Moon and Venus' nostalgic energy. Those memories are your soul's anchor — they remind you who you once were.", reversed:"The reversed Six of Cups means Moon and Venus have become lost in nostalgia. The past has its beauty, but it also has its pain. Both are true."}} },
  { id:"C7", name:"圣杯七", originalName:"Seven of Cups", suit:"cups", element:"水", astro:"海王星/月亮 · 幻想与选择", keywords:["幻想","选择","幻觉","直觉","可能性"], uprightBrief:"海王星之雾笼罩圣杯之选", reversedBrief:"幻灭或明确选择", imageUrl:"icons/stellar/cups-07.png", upright:"圣杯七牌是海王星和月亮的幻想能量——你面前有很多选择，但它们中的一些可能是幻觉。这不是关于「现实」，而是关于「辨别」。海王星的能量教你：不是每一个闪亮的东西都是金子，不是每一个梦想都适合你。你的直觉是你的指南针——它知道哪个杯子有真正的酒，哪个杯子只是看起来有。所以，当你感到困惑时，不要急于选择。深呼吸，然后感受你的身体。你的身体知道答案，即使你的头脑不知道。", reversed:"逆位的圣杯七是海王之星穿透了迷雾。你可能终于看清了什么是真的，什么是幻觉，或者相反——你意识到你在过度幻想，用白日梦来逃避行动。海王星的逆行能量提醒你：梦想不是目的地，它们是方向。如果你一直在「梦想」但没有行动，那你的梦想就只是逃避。选择一个杯子，然后喝下去。即使它是苦的。至少你会知道它的味道。", translations:{en:{upright:"The Seven of Cups is Neptune and Moon's fantasy energy. Your intuition is your compass — it knows which cup has real wine. When confused, don't rush to choose.", reversed:"The reversed Seven of Cups means Neptune's star has pierced the fog. Dreams aren't destinations; they're directions. Pick a cup and drink. At least you'll know its taste."}} },
  { id:"C8", name:"圣杯八", originalName:"Eight of Cups", suit:"cups", element:"水", astro:"土星/月亮 · 寻求与离开", keywords:["离开","寻求","勇气","成长","朝圣"], uprightBrief:"土星之足离开满溢的圣杯", reversedBrief:"害怕离开或回到过去", imageUrl:"icons/stellar/cups-08.png", upright:"圣杯八牌是土星和月亮的离开能量——你正在离开一些「很好」但不是「对的」东西。这不是关于「放弃」，而是关于「朝圣」。土星的能量教你：有时候，你需要离开一个舒适的情况，才能找到你真正的家。你的勇气不是「没有恐惧」，它是「带着恐惧依然行走」。所以，当你感到那种「我需要更多」的感觉时，相信它。即使其他人说你「不知感恩」。你不需要为你的渴望道歉。渴望是灵魂的语言。", reversed:"逆位的圣杯八是土星之足变得沉重了。你可能害怕离开你知道的东西，或者相反——你在不断地寻找，但永远找不到「对」的东西。土星的逆行能量提醒你：完美的家不存在，但「足够好」的家存在。如果你一直在寻找一个你永远不会到达的应许之地，那可能是因为你在用「寻求」来逃避「成为」。停止寻找，开始建立。你现在的所在地可能是你的家，如果你允许它是的话。", translations:{en:{upright:"The Eight of Cups is Saturn and Moon's leaving energy. Longing is the language of the soul. You don't need to apologize for your longing.", reversed:"The reversed Eight of Cups means Saturn's foot has become heavy. The perfect home doesn't exist, but a 'good enough' home does. Stop searching, start building."}} },
  { id:"C9", name:"圣杯九", originalName:"Nine of Cups", suit:"cups", element:"水", astro:"木星/金星 · 满足与愿望", keywords:["满足","愿望","享受","成功","感官"], uprightBrief:"木星之丰盛注满圣杯", reversedBrief:"不满或过度放纵", imageUrl:"icons/stellar/cups-09.png", upright:"圣杯九牌是木星和金星的满足能量——你的愿望正在实现，你的心正在歌唱。这不是关于「完美」，而是关于「欣赏」。木星的能量教你：你已经足够好了，你已经拥有足够多了。你的满足不是「到达某个地方」，它是「意识到你已经在这里」。所以，当你感到满足时，停下来。深呼吸。看看你的生活。它并不完美，但它是你的。而「你的」比「完美的」好一千倍。享受这一刻，它不会永远持续——但它现在在这里，而你现在在这里。这就是魔法。", reversed:"逆位的圣杯九是木星之丰盛变成了贪婪。你可能觉得「还不够」，或者相反——你在过度放纵，试图用物质来填补情感空洞。木星的逆行能量提醒你：更多的东西不会让你更满足，更好的关系不会让你更完整。如果你觉得自己「仍然不快乐」，那可能是因为你在寻找外在的解决方案来解决内在的问题。回到你的内心，然后问问自己：我现在需要什么才能真正感到满足？那个答案可能不是「更多」。", translations:{en:{upright:"The Nine of Cups is Jupiter and Venus' satisfaction energy. 'Yours' is a thousand times better than 'perfect.' Enjoy this moment; it won't last forever — but it's here now.", reversed:"The reversed Nine of Cups means Jupiter's abundance has turned into greed. More things won't make you more satisfied. Ask yourself: what do I need right now to truly feel satisfied?"}} },
  { id:"C10", name:"圣杯十", originalName:"Ten of Cups", suit:"cups", element:"水", astro:"金星/木星 · 和谐与家庭", keywords:["和谐","家庭","幸福","圆满","情感满足"], uprightBrief:"金星与木星共绘家庭彩虹", reversedBrief:"家庭冲突或缺乏和谐", imageUrl:"icons/stellar/cups-10.png", upright:"圣杯十牌是金星和木星的和谐能量——你的家庭生活和情感关系正处于和谐的状态。这不是关于「完美家庭」，而是关于「欣赏你所拥有的」。金星的能量教你：幸福不是「到达某个地方」，它是「意识到你已经在这里」。你的家庭可能不是完美的，但它是你的。而「你的」比「完美的」好得多。所以，当你与家人相处时，放下你的评判。他们不完美，你不完美，但这正是为什么你们需要彼此。", reversed:"逆位的圣杯十是金星与木星的彩虹被暴风雨遮蔽了。你可能正在经历家庭冲突，或者相反——你觉得自己的情感生活「不够好」。金星的逆行能量提醒你：和谐不是「没有冲突」，它是「冲突后依然选择彼此」。如果你觉得自己的家庭「不够好」，那可能是因为你在用别人的标准来衡量自己的幸福。放下那个标准，然后创建你自己的。你的家庭是你定义的，不是别人定义的。", translations:{en:{upright:"The Ten of Cups is Venus and Jupiter's harmonious energy. Your family may not be perfect, but it's yours. Drop your judgments when with family.", reversed:"The reversed Ten of Cups means Venus and Jupiter's rainbow has been obscured. Harmony isn't 'no conflict'; it's 'choosing each other even after conflict.'"}} },
  { id:"C11", name:"圣杯侍从", originalName:"Page of Cups", suit:"cups", element:"水", astro:"月亮/海王星 · 直觉与敏感", keywords:["直觉","敏感","创意","消息","梦想家"], uprightBrief:"月亮之子带来直觉的消息", reversedBrief:"情绪不稳或创意受阻", imageUrl:"icons/stellar/cups-11.png", upright:"圣杯侍从牌是月亮和海王星的直觉能量——一个敏感的、有创意的消息或机会正在来到你身边。这不是关于「逻辑」，而是关于「感受」。月亮的能量教你：你的敏感不是你的弱点，它是你的天线——它让你接收到别人错过的信号。你的创意是孩子般的——它不关心「是否可行」，它只关心「是否有趣」。所以，当你感到灵感时，追随它。即使它看起来「不实际」。孩子般的快乐是你与生俱来的权利，不要让它被「成熟」杀死。", reversed:"逆位的圣杯侍从是月亮之子变得情绪化了。你可能过于敏感，把每件事都个人化，或者相反——你在关闭你的直觉，试图「理性」一切。月亮的逆行能量提醒你：你不能「思考」你的方式进入直觉。如果你觉得自己「太情绪化」，那可能是因为你在用头脑来分析心脏。放下分析，然后感受。你的情绪是信息，不是敌人。", translations:{en:{upright:"The Page of Cups is Moon and Neptune's intuitive energy. Your sensitivity isn't your weakness; it's your antenna. Childlike joy is your birthright; don't let 'maturity' kill it.", reversed:"The reversed Page of Cups means the Moon's child has become overly emotional. Your emotions are information, not enemies."}} },
  { id:"C12", name:"圣杯骑士", originalName:"Knight of Cups", suit:"cups", element:"水", astro:"海王星/金星 · 浪漫与追求", keywords:["浪漫","追求","理想主义","魅力","情感"], uprightBrief:"海王星骑士追寻情感之杯", reversedBrief:"情绪化或空想家", imageUrl:"icons/stellar/cups-12.png", upright:"圣杯骑士牌是海王星和金星的浪漫能量——你充满了浪漫的理想和情感上的勇气。这不是关于「现实」，而是关于「情感真理」。海王星的能量教你：有时候，你需要跟随你的心，即使它没有「意义」。你的魅力是你的超能力——它让别人感到被看见、被理解。所以，当你感到情感的冲动时，相信它。即使别人说你「太感性了」。他们可能永远不会理解你的深度，但你自己理解。感受吧。这就是活着的意义。", reversed:"逆位的圣杯骑士是海王之星变成了幻梦。你可能过于理想化，忽视了关系的现实，或者相反——你在情感上逃避，不敢追求你真正想要的。海王星的逆行能量提醒你：浪漫不是「逃避现实」，它是「用情感来丰富现实」。如果你觉得自己「永远找不到对的人」，那可能是因为你在寻找一个不存在的完美。放下那个幻象，然后看看真实的人。真实比完美性感得多。", translations:{en:{upright:"The Knight of Cups is Neptune and Venus' romantic energy. Feel. That's what living is about.", reversed:"The reversed Knight of Cups means Neptune's star has turned into fantasy. Real is so much sexier than perfect."}} },
  { id:"C13", name:"圣杯王后", originalName:"Queen of Cups", suit:"cups", element:"水", astro:"月亮/海王星 · 同理心与直觉", keywords:["同理心","直觉","滋养","敏感","深度"], uprightBrief:"月亮王后深潜情感之海", reversedBrief:"情绪化或边界不清", imageUrl:"icons/stellar/cups-13.png", upright:"圣杯王后牌是月亮和海王星的同理心能量——你与情感世界的连接非常深，你的直觉几乎从未出错。这不是关于「理性」，而是关于「感受」。月亮的能量教你：你的同理心不是你的负担，它是你的天赋——它让你能够治愈他人，只要你先治愈自己。你的深度是美丽的，但有时候它是孤独的。所以，当你感到「太多」时，记住：你不需要承载每个人的情感。你可以同情而不同理。你可以关心而不承担。", reversed:"逆位的圣杯王后是月亮之海变成了沼泽。你可能过于沉浸在情感中，失去了与现实的连接，或者相反——你在过度保护你自己，害怕再次被伤害。月亮的逆行能量提醒你：你不能通过关闭你的心来保护自己。如果你觉得自己「太敏感了」，那可能是因为你在用你的情感作为武器或盾牌。放下那个防御，然后让情感流动。情感是能量，能量需要流动。", translations:{en:{upright:"The Queen of Cups is Moon and Neptune's empathetic energy. You can sympathize without empathizing. You can care without carrying.", reversed:"The reversed Queen of Cups means the Moon's sea has turned into a swamp. You cannot protect yourself by closing your heart. Let emotions flow."}} },
  { id:"C14", name:"圣杯国王", originalName:"King of Cups", suit:"cups", element:"水", astro:"海王星/木星 · 情感成熟与智慧", keywords:["情感成熟","智慧","慈悲","平衡","导师"], uprightBrief:"海王星国王以慈悲统治情感", reversedBrief:"情感操控或压抑情感", imageUrl:"icons/stellar/cups-14.png", upright:"圣杯国王牌是海王星和木星的智慧能量——你在情感上非常成熟，能够平衡理性和直觉。这不是关于「没有情感」，而是关于「不被情感控制」。海王星的能量教你：真正的力量不是「不感受」，它是「感受一切但仍然选择 wisely」。你的慈悲是你的超能力——它让你能够理解甚至最困难的人。所以，当你感到情感上的挑战时，深呼吸。你不需要立即反应。你可以感受，然后选择如何回应。这就是国王的力量。", reversed:"逆位的圣杯国王是海王之星变得操控了。你可能在使用情感作为控制他人的工具，或者相反——你在过度压抑自己的情感，看起来「冷漠」。海王星的逆行能量提醒你：你不能通过否认情感来控制它们。如果你觉得自己「不需要任何人」，那可能是因为你在用独立作为防御。真正的力量包括脆弱。放下那个面具，然后让某人靠近。你不需要独自承担一切。", translations:{en:{upright:"The King of Cups is Neptune and Jupiter's wisdom energy. True power isn't 'not feeling'; it's 'feeling everything and still choosing wisely.'", reversed:"The reversed King of Cups means Neptune's star has become manipulative. True power includes vulnerability. You don't need to carry everything alone."}} },

  // ============ 小阿卡纳 - 宝剑 Swords (14张) ============
  { id:"S1", name:"宝剑王牌", originalName:"Ace of Swords", suit:"swords", element:"风", astro:"天王星/水星 · 真理与突破", keywords:["真理","突破","清晰","新思维"], uprightBrief:"天王之星斩断迷雾", reversedBrief:"混乱思维或真相残酷", imageUrl:"icons/stellar/swords-01.png", upright:"宝剑王牌是天王星和水星的突破能量——一把全新的宝剑从星空中降临，斩断一切迷雾。这不是关于「赢」争论，而是关于「看见」真相。天王星的能量教你：有时候，你需要一个突然的洞察来打破旧的模式。你的思维是一把双刃剑——它既能切开谎言，也能切开你与自己之间的连接。所以，当你感到一个突然的清晰时，相信它。即使它让你失去了舒适。真相可能不舒适，但它是自由的。", reversed:"逆位的宝剑王牌是天王之星的能量变得混乱了。你可能感到思维混乱，无法看清真相，或者相反——你在用「真相」作为伤害他人的武器。天王星的逆行能量提醒你：真理不是「打败」别人，它是「对齐」你自己。如果你觉得自己「太诚实了」以至于伤害了别人，那你可能忘记了诚实也需要慈悲。真相加上慈悲等于自由。真相减去慈悲等于暴力。", translations:{en:{upright:"The Ace of Swords is Uranus and Mercury's breakthrough energy. Truth may be uncomfortable, but it's liberating.", reversed:"The reversed Ace of Swords means Uranus' energy has become chaotic. Truth + compassion = liberation. Truth - compassion = violence."}} },
  { id:"S2", name:"宝剑二", originalName:"Two of Swords", suit:"swords", element:"风", astro:"月亮/水星 · 僵局与选择", keywords:["僵局","选择","逃避","直觉"], uprightBrief:"月亮之雾遮蔽宝剑之择", reversedBrief:"做出困难选择或逃避", imageUrl:"icons/stellar/swords-02.png", upright:"宝剑二牌是月亮和水星的僵局能量——你面前有两个选择，但你不愿意选任何一个。这不是关于「没有答案」，而是关于「害怕选错」。月亮的能量教你：有时候，不做选择也是一个选择——它叫做「逃避」。你的直觉知道答案，但你的恐惧不让你说出来。所以，当你感到「卡住」时，问问自己：我在害怕什么？如果你选错了，那又怎样？错误也是老师。", reversed:"逆位的宝剑二是月亮之雾变得太浓了。你可能终于做了一个你一直在逃避的选择，或者相反——你意识到你的「不做选择」实际上是一个选择，而且它正在伤害你。月亮的逆行能量提醒你：你无法永远坐在 fence 上。选择不是关于「正确」，它是关于「活着」。一个错误的选择好过一个没有选择的生活。", translations:{en:{upright:"The Two of Swords is Moon and Mercury's stalemate energy. Not choosing IS a choice — it's called 'avoidance.' A wrong choice is better than a life with no choice.", reversed:"The reversed Two of Swords means the Moon's fog has become too thick. You cannot sit on the fence forever. Choose."}} },
  { id:"S3", name:"宝剑三", originalName:"Three of Swords", suit:"swords", element:"风", astro:"土星/水星 · 心碎与清醒", keywords:["心碎","清醒","真相","分离"], uprightBrief:"土星之剑刺穿幻象", reversedBrief:"从痛苦中恢复", imageUrl:"icons/stellar/swords-03.png", upright:"宝剑三牌是土星和水星的清醒能量——心碎的真相正在刺穿你的幻象。这不是关于「惩罚」，而是关于「清醒」。土星的能量教你：有时候，你需要被刺穿，才能看到你一直在欺骗自己什么。你的痛苦不是你的敌人，它是你的老师——它在教你什么是真的，什么只是你想要的。所以，当你感到心碎时，让它痛。不要试图「积极思考」它 away。心碎是清醒的另一种形式。", reversed:"逆位的宝剑三是土星之剑开始被拔出来了。你可能正在从心碎中恢复，或者相反——你意识到你在执着于一个已经结束了的痛苦。土星的逆行能量提醒你：你不需要「修复」过去才能继续前进。如果你觉得自己「永远无法愈合」，那可能是因为你在用你的痛苦来定义你自己。你不仅仅是一个心碎的人，你是一个正在学习如何再次信任的人。", translations:{en:{upright:"The Three of Swords is Saturn and Mercury's sobering energy. Heartbreak is just another form of sobering up. Let it hurt; don't 'positive think' it away.", reversed:"The reversed Three of Swords means Saturn's sword has started to be pulled out. You are not just a heartbroken person; you're someone learning how to trust again."}} },
  { id:"S4", name:"宝剑四", originalName:"Four of Swords", suit:"swords", element:"风", astro:"木星/水星 · 休息与恢复", keywords:["休息","恢复","冥想","反思"], uprightBrief:"木星之静谧修复宝剑之伤", reversedBrief:"无法休息或过度孤立", imageUrl:"icons/stellar/swords-04.png", upright:"宝剑四牌是木星和水星的休息能量——你需要暂停，让你的思维恢复。这不是关于「放弃」，而是关于「重新校准」。木星的能量教你：休息不是「懒惰」，它是「整合」。你的思维需要休息，就像你的身体需要睡眠一样。所以，当你感到疲惫时，允许自己停下来。你不需要「一直都在」。你被设计成有节奏的——工作然后休息，行动然后反思。这就是生命的方式。", reversed:"逆位的宝剑四是木星之扩张变得过度了。你可能无法休息，因为你的思维在疯狂地转动，或者相反——你在过度孤立自己，拒绝与任何人连接。木星的逆行能量提醒你：休息不是「完全断开」，它是「有意识的暂停」。如果你觉得自己「太忙了无法休息」，那你可能已经失去了与自己的连接。停下来。呼吸。你值得休息。", translations:{en:{upright:"The Four of Swords is Jupiter and Mercury's rest energy. Rest isn't 'lazy'; it's 'integration.' You're designed to have rhythms — work then rest, action then reflection.", reversed:"The reversed Four of Swords means Jupiter's expansion has become excessive. Rest isn't 'completely disconnecting'; it's 'conscious pausing.' You deserve rest."}} },
  { id:"S5", name:"宝剑五", originalName:"Five of Swords", suit:"swords", element:"风", astro:"水星/土星 · 冲突与空虚", keywords:["冲突","空虚","胜利","代价"], uprightBrief:"水星之锋赢得空虚之战", reversedBrief:"和解或从冲突中恢复", imageUrl:"icons/stellar/swords-05.png", upright:"宝剑五牌是水星和土星的冲突能量——你可能在争论中「赢」了，但你失去了更重要的东西。这不是关于「赢」，而是关于「值得」。水星的能量教你：不是每一个争论都值得你的能量。有时候，你在争论中「赢」了，但你在关系中「输」了。你的宝剑是双刃的——它能切开真相，也能切开连接。所以，在争论之前，问问自己：这个胜利值得它的代价吗？", reversed:"逆位的宝剑五是水星和土星的冲突变得不必要的了。你可能正在从一场「空洞的胜利」中恢复，或者相反——你在寻求和解，即使这意味着「输」。水星的逆行能量提醒你：有时候，「输」争论是你能做的最强大的事。当你愿意放下你的宝剑，你就在教别人放下他们的。和平从你开始。", translations:{en:{upright:"The Five of Swords is Mercury and Saturn's conflict energy. Not every argument is worth your energy. Ask: is this victory worth its cost?", reversed:"The reversed Five of Swords means Mercury and Saturn's conflict has become unnecessary. Sometimes, 'losing' an argument is the most powerful thing you can do. Peace starts with you."}} },
  { id:"S6", name:"宝剑六", originalName:"Six of Swords", suit:"swords", element:"风/水", astro:"水星/海王星 · 过渡与疗愈", keywords:["过渡","疗愈","旅行","离开"], uprightBrief:"水星之舟渡向疗愈之岸", reversedBrief:"抗拒过渡或困在痛苦中", imageUrl:"icons/stellar/swords-06.png", upright:"宝剑六牌是水星和海王星的过渡能量——你正在离开一个痛苦的情况，渡向更平静的水域。这不是关于「逃跑」，而是关于「过渡」。水星的能量教你：有时候，你需要离开一个有毒的情况，才能开始疗愈。你的离开不是「放弃」，它是「选择你自己」。所以，当你感到那种「我需要离开」的感觉时，相信它。即使其他人说你「在逃避」。离开不是逃避，它是勇气。", reversed:"逆位的宝剑六是水星之舟遇到了逆风。你可能觉得你无法离开一个痛苦的情况，或者相反——你在离开，但你的心还在原地。水星的逆行能量提醒你：身体可以离开，但心需要时间才能跟上。如果你觉得自己「离开了但仍然在痛」，那可能是正常的。疗愈不是线性的。给自己时间。你值得平静的水域。", translations:{en:{upright:"The Six of Swords is Mercury and Neptune's transition energy. Leaving isn't 'running away'; it's courage. When you feel 'I need to leave,' trust it.", reversed:"The reversed Six of Swords means Mercury's boat has encountered headwinds. Healing isn't linear. Give yourself time. You deserve calm waters."}} },
  { id:"S7", name:"宝剑七", originalName:"Seven of Swords", suit:"swords", element:"风", astro:"天王星/水星 · 策略与欺骗", keywords:["策略","欺骗","偷偷","不诚"], uprightBrief:"天王之星暗中行动", reversedBrief:"被揭露或放弃欺骗", imageUrl:"icons/stellar/swords-07.png", upright:"宝剑七牌是天王星和水星的暗中能量——你可能正在使用策略来得到你想要的，或者相反——有人在偷偷地对你做同样的事。这不是关于「诚实 vs 不诚实」，而是关于「对齐」。天王星的能量教你：有时候，你需要「玩弄系统」来生存，但你不需要通过欺骗来繁荣。你的策略是你的生存工具——但它们不应该成为你的生活方式。所以，检查一下：你的行动与你价值观一致吗？", reversed:"逆位的宝剑七是天王之星变得透明了。你可能正在被揭露你一直在隐藏的东西，或者相反——你意识到你在欺骗自己关于某件事。天王星的逆行能量提醒你：你无法永远隐藏真相。它总会浮出水面。如果你觉得自己「被抓住了」，那可能是时候停止躲藏了。真相可能不舒适，但它它是自由的。", translations:{en:{upright:"The Seven of Swords is Uranus and Mercury's strategic energy. Your strategies are your survival tools — but they shouldn't become your life style. Are your actions aligned with your values?", reversed:"The reversed Seven of Swords means Uranus' star has become transparent. You cannot hide the truth forever. Stop hiding. Truth = freedom."}} },
  { id:"S8", name:"宝剑八", originalName:"Eight of Swords", suit:"swords", element:"风", astro:"土星/水星 · 自我限制与恐惧", keywords:["自我限制","恐惧","受害者","觉醒"], uprightBrief:"土星之链束缚思维", reversedBrief:"突破限制或获得自由", imageUrl:"icons/stellar/swords-08.png", upright:"宝剑八牌是土星和水星的限制能量——你可能感到被困住了，但链子其实没有锁。这不是关于「外面」的限制，而是关于「内在」的限制。土星的能量教你：你最大的监狱是你对自己的故事。你的思维已经创造了这个监狱——它也可以摧毁它。所以，当你感到「我不能」时，问问自己：这是真的吗？还是我只是害怕？恐惧不是你的监狱长，你是。", reversed:"逆位的宝剑八是土星之链被打破了。你可能终于看到了你一直在限制自己的方式，或者相反——你意识到你的「限制」只存在于你的头脑中。土星的逆行能量提醒你：你一直都有钥匙。你只是从来没有试着转动它。如果你觉得自己「自由了」，那恭喜你。现在，走出去。世界在等你。", translations:{en:{upright:"The Eight of Swords is Saturn and Mercury's restriction energy. Your biggest prison is the story you tell about yourself. Fear isn't your prison guard; YOU are.", reversed:"The reversed Eight of Swords means Saturn's chains have been broken. You've always had the key. Now go out. The world is waiting for you."}} },
  { id:"S9", name:"宝剑九", originalName:"Nine of Swords", suit:"swords", element:"风", astro:"火星/水星 · 焦虑与噩梦", keywords:["焦虑","噩梦","担忧","释放"], uprightBrief:"火星之剑刺穿睡眠", reversedBrief:"从焦虑中释放", imageUrl:"icons/stellar/swords-09.png", upright:"宝剑九牌是火星和水星的焦虑能量——你的思维在夜晚疯狂地转动，让你无法入睡。这不是关于「软弱」，而是关于「人性」。火星的能量教你：你的担忧不是你的敌人，它们是你的警报系统——但它们有时候会误报。你的思维是一台时间机器——它喜欢把你送到你无法控制的未来。所以，当你在凌晨3点醒来，感到焦虑时，深呼吸。问自己：这个担忧是真的吗？还是我只是害怕？现在，这一刻，你是安全的。", reversed:"逆位的宝剑九是火星之剑变得迟钝了。你可能正在从焦虑中恢复，或者相反——你意识到你的担忧大多数都不会成真。火星的逆行能量提醒你：你的思维是一个糟糕的算命先生。它不知道未来。所以，停止问「如果……怎么办？」开始问「现在，我需要什么？」。活在当下。这是唯一的时刻。", translations:{en:{upright:"The Nine of Swords is Mars and Mercury's anxiety energy. Your mind is a terrible fortune teller. It doesn't know the future. Right now, in this moment, you're safe.", reversed:"The reversed Nine of Swords means Mars' sword has become dull. Stop asking 'what if...?' Start asking 'what do I need right now?' Live in the present."}} },
  { id:"S10", name:"宝剑十", originalName:"Ten of Swords", suit:"swords", element:"风", astro:"土星/水星 · 终结与谷底", keywords:["终结","谷底","释放","重生"], uprightBrief:"土星之剑终结一切", reversedBrief:"从谷底爬起", imageUrl:"icons/stellar/swords-10.png", upright:"宝剑十牌是土星和水星的终结能量——你感到自己已经到了谷底，无法再更低了。这不是关于「惩罚」，而是关于「终结」。土星的能量教你：有时候，你需要碰到谷底，才能开始往上爬。你的痛苦不会永远持续——它有一个目的，即使你现在看不到。所以，当你感到「我无法再承受更多了」时，记住：谷底也是转折点。从那里，唯一的方向是上。你不会被给与你无法承受的东西。", reversed:"逆位的宝剑十是土星之重变得可以承受了。你可能正在从谷底爬起来，或者相反——你意识到你的「谷底」实际上是一个新的开始。土星的逆行能量提醒你：每一次终结都是一个开始。你不会被给与你无法承受的东西。如果你觉得自己「正在死亡」，那可能是因为你正在重生。死亡和重生是同一枚硬币的两面。", translations:{en:{upright:"The Ten of Swords is Saturn and Mercury's ending energy. Rock bottom is also a turning point. From there, the only direction is up. You won't be given more than you can handle.", reversed:"The reversed Ten of Swords means Saturn's weight has become bearable. Every ending is a beginning. You might be rebirthing."}} },
  { id:"S11", name:"宝剑侍从", originalName:"Page of Swords", suit:"swords", element:"风", astro:"水星/天王星 · 好奇与真相", keywords:["好奇","真相","沟通","警觉"], uprightBrief:"水星之子带来真相之讯", reversedBrief:"八卦或思维混乱", imageUrl:"icons/stellar/swords-11.png", upright:"宝剑侍从牌是水星和天王星的好奇能量——一个关于真相或新信息的消息正在来到你身边。这不是关于「 gossip」，而是关于「求知」。水星的能量教你：你的好奇心不是你的弱点，它是你的超能力——它让你看到别人错过的连接。你的思维是敏锐的——它能在混乱中找到模式。所以，当你感到好奇时，探索它。即使别人说你「想太多了」。思考不是你的敌人，它是你的超能力。", reversed:"逆位的宝剑侍从是水星之子变得八卦了。你可能过于好奇别人的事，或者相反——你的思维变得如此混乱，以至于你无法看清任何东西。水星的逆行能量提醒你：不是每一个想法都需要被思考，不是每一个问题都需要被回答。如果你觉得自己「无法关闭我的思维」，那可能是因为你在试图控制你无法控制的东西。放下控制。让思维休息。", translations:{en:{upright:"The Page of Swords is Mercury and Uranus' curious energy. Your curiosity is your superpower — it lets you see connections others miss.", reversed:"The reversed Page of Swords means Mercury's child has become gossipy. Not every thought needs to be thought. Let the mind rest."}} },
  { id:"S12", name:"宝剑骑士", originalName:"Knight of Swords", suit:"swords", element:"风", astro:"水星/天王星 · 快速行动与直言", keywords:["快速","直言","冲动","清晰"], uprightBrief:"水星骑士挥剑疾驰", reversedBrief:"鲁莽或言语伤人", imageUrl:"icons/stellar/swords-12.png", upright:"宝剑骑士牌是水星和天王星的快速能量——你充满了清晰的和直言不讳的勇气。这不是关于「残忍」，而是关于「诚实」。水星的能量教你：有时候，你需要说那个「困难的真话」，即使它会伤害别人的感受。你的清晰是一把剑——它切开谎言和错觉。所以，当你感到那种「我需要说真话」的冲动时，相信它。即使别人说你「太直接了」。世界需要更多说真话的人。", reversed:"逆位的宝剑骑士是水星之马失去了控制。你可能过于直接，伤害了别人的感受，或者相反——你在用「诚实」作为伤害别人的借口。水星的逆行能量提醒你：真理不需要残忍。你可以说真话而不伤害别人。如果你觉得自己「只是说实话而已」，那你可能忘记了诚实也需要智慧。真话是一颗药——它可以是苦的，但它也可以被裹在糖里面。", translations:{en:{upright:"The Knight of Swords is Mercury and Uranus' swift energy. The world needs more truth-tellers. When you feel the impulse to speak truth, trust it.", reversed:"The reversed Knight of Swords means Mercury's horse has lost control. Truth doesn't need to be cruel. You can speak truth without hurting others."}} },
  { id:"S13", name:"宝剑王后", originalName:"Queen of Swords", suit:"swords", element:"风", astro:"水星/土星 · 清晰与独立", keywords:["清晰","独立","智慧","直率"], uprightBrief:"水星王后以清晰统治", reversedBrief:"冷漠或过于尖锐", imageUrl:"icons/stellar/swords-13.png", upright:"宝剑王后牌是水星和土星的清晰能量——你的思维非常清晰，你的直觉几乎从未出错。这不是关于「没有情感」，而是关于「不被情感控制」。水星的能量教你：你的清晰不是你的冰冷，它是你的超能力——它让你能够在混乱中找到中心。你的独立是你的力量——你不需要任何人来定义你。所以，当你感到「我知道真相是什么」时，相信它。即使别人说你「太理性了」。理性不是你的敌人，它是你的超能力。", reversed:"逆位的宝剑王后是水星之剑变得过于尖锐了。你可能用「理性」来保护自己，避免受伤，或者相反——你在过度压抑自己的情感，看起来「冷漠」。水星的逆行能量提醒你：你不需要「没有情感」才能清晰。你的情感是你的数据——它们给你信息。如果你觉得自己「太冷了」，那可能是因为你在用清晰作为防御。真正的清晰包括慈悲。", translations:{en:{upright:"The Queen of Swords is Mercury and Saturn's clarity energy. Your clarity isn't your coldness; it's your superpower. You don't need to be 'without emotion' to be clear.", reversed:"The reversed Queen of Swords means Mercury's sword has become too sharp. True clarity includes compassion. You don't need to be cold to be clear."}} },
  { id:"S14", name:"宝剑国王", originalName:"King of Swords", suit:"swords", element:"风", astro:"水星/天王星 · 权威与真理", keywords:["权威","真理","逻辑","公正"], uprightBrief:"水星国王以真理统治", reversedBrief:"专制或滥用权力", imageUrl:"icons/stellar/swords-14.png", upright:"宝剑国王牌是水星和天王星的权威能量——你在思维和沟通上非常强大，能够做出公正的决定。这不是关于「控制」，而是关于「服务真理」。水星的能量教你：真正的权威不是「让其他人服从你」，而是「服从真理本身」。你的逻辑是你的超能力——它让你能够在混乱中找到秩序。所以，当你需要做一个困难的决定时，相信你的逻辑。即使别人说你「太理性了」。理性不是你的敌人，它是你的超能力。", reversed:"逆位的宝剑国王是水星之国王变得专制了。你可能正在使用你的逻辑和沟通技巧来控制他人，或者相反——你在过度认同你的「理性」，以至于你失去了与情感的连接。水星的逆行能量提醒你：逻辑是一个伟大的仆人，但是一个可怕的主人。如果你觉得自己「永远是对的」，那你可能已经停止学习了。一个真正的国王知道他不知道的比他知道的多。", translations:{en:{upright:"The King of Swords is Mercury and Uranus' authority energy. True authority isn't 'making others obey you'; it's 'obeying the truth itself.'", reversed:"The reversed King of Swords means Mercury's king has become authoritarian. Logic is a great servant but a terrible master. A true king knows he knows less than he knows."}} },

  // ============ 小阿卡纳 - 钱币 Pentacles (14张) ============
  { id:"P1", name:"钱币王牌", originalName:"Ace of Pentacles", suit:"pentacles", element:"土", astro:"金星/土星 · 新机会与丰盛", keywords:["新机会","丰盛","物质","种子"], uprightBrief:"金星之种落入丰饶之土", reversedBrief:"机会流失或缺乏落地", imageUrl:"icons/stellar/pentacles-01.png", upright:"钱币王牌是金星和土星的新机会能量——一个全新的物质机会正在从星空中降临到你的生活中。这不是关于「赚大钱」，而是关于「种下种子」。金星的能量教你：丰盛不是一个目的地，它是一个方向。你的种子是一个承诺——你对未来的自己的承诺。所以，当你看到一个机会时，相信它。即使它看起来「不够大」。每一个橡树都曾经是一颗_acorn。每一个财富都曾经是一个想法。", reversed:"逆位的钱币王牌是金星和土星的种子能量被阻塞了。你可能有一个很好的机会，但没有采取行动，或者相反——你在行动，但没有耐心等待结果。金星的逆行能量提醒你：丰盛需要时间才能成长。如果你觉得自己「永远无法丰盛」，那可能是因为你在用别人的时间线来衡量自己的成功。放下比较。你的花园有自己的季节。", translations:{en:{upright:"The Ace of Pentacles is Venus and Saturn's new opportunity energy. Every oak tree was once an acorn. Every fortune was once an idea. When you see an opportunity, trust it.", reversed:"The reversed Ace of Pentacles means Venus and Saturn's seed energy is blocked. Abundance takes time to grow. Your garden has its own seasons."}} },
  { id:"P2", name:"钱币二", originalName:"Two of Pentacles", suit:"pentacles", element:"土/水", astro:"木星/金星 · 平衡与适应", keywords:["平衡","适应","多任务","灵活"], uprightBrief:"木星之舞平衡两枚钱币", reversedBrief:"失衡或过度伸展", imageUrl:"icons/stellar/pentacles-02.png", upright:"钱币二牌是木星和金星的平衡能量——你正在 juggling 多个责任，试图保持一切平衡。这不是关于「完美平衡」，而是关于「适应」。木星的能量教你：生活不是 static 的，它是 dynamic 的。你的平衡是一个舞蹈——你一直在移动，但你不倒下。所以，当你感到「我有太多事情要做」时，深呼吸。你不需要完美地做所有事情。选择最重要的，然后让其他事情 wait。你不是一台机器，你是一个人。", reversed:"逆位的钱币二是木星和金星的舞蹈变得笨拙了。你可能过度伸展了自己，或者相反——你失去了平衡，一切都在倒塌。木星的逆行能量提醒你：你不需要「做所有事情」。有时候，「不做」是最强大的选择。如果你觉得自己「无法说不」，那可能是因为你在用「忙碌」来逃避感受。停下来。呼吸。你值得休息。", translations:{en:{upright:"The Two of Pentacles is Jupiter and Venus' balancing energy. Life isn't static; it's dynamic. You're not a machine; you're a human. Choose what's most important and let other things wait.", reversed:"The reversed Two of Pentacles means Jupiter and Venus' dance has become clumsy. You don't need to 'do all the things.' Sometimes 'not doing' is the most powerful choice."}} },
  { id:"P3", name:"钱币三", originalName:"Three of Pentacles", suit:"pentacles", element:"土", astro:"太阳/土星 · 合作与技艺", keywords:["合作","技艺","团队","认可"], uprightBrief:"太阳之光点亮合作之艺", reversedBrief:"缺乏合作或品质不佳", imageUrl:"icons/stellar/pentacles-03.png", upright:"钱币三牌是太阳和土星的合作能量——你正在与一个团队合作，创造一个高质量的项目。这不是关于「独自做所有事情」，而是关于「欣赏他人的技艺」。太阳的能量教你：真正的卓越不是「我一个人做」，它是「我们 together 做」。你的团队是你的资源——他们每个人都有你不具备的技能。所以，当你感到「我无法做所有事情」时，寻求帮助。即使你觉得「别人不会做得像我一样好」。他们不需要做得像你一样好。他们只需要做得够好。", reversed:"逆位的钱币三是太阳和土星的合能变得 disharmonious 了。你可能在一个团队中工作，但没有人被真正欣赏，或者相反——你在独自工作，因为你「不信任任何人」。太阳的逆行能量提醒你：你不需要「控制每一个细节」才能确保质量。如果你觉得自己「必须自己做所有事情」，那你可能已经失去了与他人的连接。信任是一个风险，但它也是一个机会。", translations:{en:{upright:"The Three of Pentacles is Sun and Saturn's collaboration energy. True excellence isn't 'I do everything alone'; it's 'we do it together.' Seek help when you feel 'I can't do all this.'", reversed:"The reversed Three of Pentacles means Sun and Saturn's collaborative energy has become disharmonious. Trust is a risk, but it's also an opportunity."}} },
  { id:"P4", name:"钱币四", originalName:"Four of Pentacles", suit:"pentacles", element:"土", astro:"天王星/土星 · 固守与不安", keywords:["固守","不安","控制","物质"], uprightBrief:"天王之星固守物质之币", reversedBrief:"过度慷慨或缺乏安全感", imageUrl:"icons/stellar/pentacles-04.png", upright:"钱币四牌是天王星和土星的固守能量——你可能过于执着于你的物质资源，害怕失去它们。这不是关于「贪心」，而是关于「不安全感」。天王星的能量教你：你无法「拥有」任何东西——你只能「暂时使用」它们。你的钱币是你的工具——它们不是你的身份。所以，当你感到「我需要抓住这个」时，问问自己：我在害怕什么？如果你放开它，会发生什么？最糟的情况是什么？它可能不会像你想象的那么糟。", reversed:"逆位的钱币四是天王星和土星的固守变得不必要的了。你可能正在学习放下，或者相反——你在过度「慷慨」，以至于自己变空了。天王星的逆行能量提醒你：你无法从空杯中倾倒。如果你觉得自己「需要给更多人」，那先给自己。你值得被滋养。一个满的杯子才能与另一个满的杯子碰杯。", translations:{en:{upright:"The Four of Pentacles is Uranus and Saturn's holding energy. You cannot 'own' anything — you can only 'borrow' them. What's the worst that could happen if you let go?", reversed:"The reversed Four of Pentacles means Uranus and Saturn's holding has become unnecessary. You cannot pour from an empty cup. Fill your own cup first."}} },
  { id:"P5", name:"钱币五", originalName:"Five of Pentacles", suit:"pentacles", element:"土", astro:"水星/土星 · 困难与坚持", keywords:["困难","坚持","健康","物质"], uprightBrief:"水星之冷考验物质之基", reversedBrief:"从困难中恢复", imageUrl:"icons/stellar/pentacles-05.png", upright:"钱币五牌是水星和土星的困难能量——你可能正在经历一个物质上的困难时期，感觉被排除在外。这不是关于「惩罚」，而是关于「考验」。水星的能量教你：困难不是你的敌人，它们是你的老师——它们在教你什么是真正重要的。你的物质资源可能会来来去去，但你的内在资源——你的技能、你的智慧、你的韧性——它们永远不会离开你。所以，当你感到「我不够」时，记住：你拥有的一切都在你的内在。", reversed:"逆位的钱币五是水星和土星的困难变得可以承受了。你可能正在从物质困难中恢复，或者相反——你意识到你的「困难」实际上是一个机会来重新评估你的优先级。水星的逆行能量提醒你：你比你认为的更有资源。如果你觉得自己「永远无法恢复」，那可能是因为你在用旧的故事来解释新的现实。放下那个故事。你是一个幸存者。", translations:{en:{upright:"The Five of Pentacles is Mercury and Saturn's hardship energy. Your material resources may come and go, but your inner resources never leave you. When you feel 'I'm not enough,' remember: everything you need is within you.", reversed:"The reversed Five of Pentacles means Mercury and Saturn's hardship has become bearable. You're a survivor. Everything you need is within you."}} },
  { id:"P6", name:"钱币六", originalName:"Six of Pentacles", suit:"pentacles", element:"土", astro:"金星/土星 · 给予与接受", keywords:["给予","接受","平衡","慈善"], uprightBrief:"金星之衡衡量给予之币", reversedBrief:"不平衡的给予或接受", imageUrl:"icons/stellar/pentacles-06.png", upright:"钱币六牌是金星和土星的给予能量——你正在给予或接受帮助，建立一种平衡的交换。这不是关于「慈善」，而是关于「循环」。金星的能量教你：给予和接受是同一枚硬币的两面。你无法只给予而不接受——那会创造不平衡。你的丰盛是一个循环——它需要在你的生活中流动。所以，当你有机会给予时，给予。但当你有机会接受时，也接受。接受不是「软弱」，它是「允许丰盛流动」。", reversed:"逆位的钱币六是金星和土星的循环变得阻塞了。你可能给得太多，以至于自己变空了，或者相反——你在拒绝接受帮助，因为「骄傲」。金星的逆行能量提醒你：接受不是「软弱」，它是「允许别人感受到给予的喜悦」。如果你觉得自己「不需要任何人的帮助」，那可能是因为你在用独立作为防御。真正的力量包括脆弱。", translations:{en:{upright:"The Six of Pentacles is Venus and Saturn's giving energy. Giving and receiving are two sides of the same coin. Receiving isn't 'weakness'; it's 'allowing abundance to flow.'", reversed:"The reversed Six of Pentacles means Venus and Saturn's circulation has become blocked. Receiving isn't 'weakness'; it's 'allowing others to feel the joy of giving.'"}} },
  { id:"P7", name:"钱币七", originalName:"Seven of Pentacles", suit:"pentacles", element:"土", astro:"土星/金星 · 耐心与评估", keywords:["耐心","评估","投资","等待"], uprightBrief:"土星之耐心浇灌成长之币", reversedBrief:"缺乏耐心或投资失败", imageUrl:"icons/stellar/pentacles-07.png", upright:"钱币七牌是土星和金星的耐心能量——你正在等待你的投资的回报，无论是时间、金钱还是精力。这不是关于「懒惰」，而是关于「信任过程」。土星的能量教你：成长需要时间。你的种子正在地下生长——你看不到它，但它正在发生。所以，当你感到「为什么我还没有看到结果」时，深呼吸。信任 timing。宇宙从来没有迟到。你的花园有自己的季节。你不需要「加速」成长。你只需要耐心。", reversed:"逆位的钱币七是土星和金星的耐心变得耗尽了。你可能过于急于看到结果，或者相反——你在等待一个永远不会到来的回报。土星的逆行能量提醒你：不是每一个种子都会发芽。有时候，你需要「拔掉」一个不再服务于你的项目，然后把你的能量投入到别的地方。耐心不是「被动地等待」。它是「积极地评估」。", translations:{en:{upright:"The Seven of Pentacles is Saturn and Venus' patience energy. Growth takes time. Trust the timing. The universe is never late. Your garden has its own seasons.", reversed:"The reversed Seven of Pentacles means Saturn and Venus' patience has become exhausted. Not every seed will sprout. Patience isn't 'passively waiting'; it's 'actively evaluating.'"}} },
  { id:"P8", name:"钱币八", originalName:"Eight of Pentacles", suit:"pentacles", element:"土", astro:"土星/太阳 · 技艺与专注", keywords:["技艺","专注","工作","精进"], uprightBrief:"土星之匠人精雕细琢", reversedBrief:"缺乏专注或工作过度", imageUrl:"icons/stellar/pentacles-08.png", upright:"钱币八牌是土星和太阳的专注能量——你正在精进一项技能，投入大量的时间和努力。这不是关于「完美主义」，而是关于「精进」。土星的能量教你：卓越是一个旅程，不是一个目的地。你的技艺是你的表达——它们让你把你的内在世界变成外在的形式。所以，当你感到「我想变得更好」时，投入时间。即使别人说你「太 obsessive 了」。追求卓越不是 obsesssion，它是爱。如果你爱你所做的，它会显示在你的工作中。", reversed:"逆位的钱币八是土星和太阳的专注变得不健康了。你可能工作过度，忽视了你的健康和其他生活领域，或者相反——你失去了动力，不再关心你的工作质量。土星的逆行能量提醒你：工作不是你的身份。你是一个人，不仅仅是一个 worker。如果你觉得自己「我的工作就是我的一切」，那你可能已经失去了与自己的连接。停下来。呼吸。你值得拥有生活，而不仅仅是生存。", translations:{en:{upright:"The Eight of Pentacles is Saturn and Sun's focused energy. Excellence is a journey, not a destination. When you feel 'I want to get better,' invest time. Pursuing excellence is an act of love.", reversed:"The reversed Eight of Pentacles means Saturn and Sun's focus has become unhealthy. Work isn't your identity. You're a human, not just a worker. You deserve to have a life, not just survive."}} },
  { id:"P9", name:"钱币九", originalName:"Nine of Pentacles", suit:"pentacles", element:"土", astro:"金星/土星 · 独立与丰盛", keywords:["独立","丰盛","享受","自给自足"], uprightBrief:"金星之园独立自主", reversedBrief:"空虚或过度物质主义", imageUrl:"icons/stellar/pentacles-09.png", upright:"钱币九牌是金星和土星的独立能量——你已经创造了一种生活，你在其中可以自给自足，享受你努力的成果。这不是关于「孤立」，而是关于「独立」。金星的能量教你：你不需要任何人来「让你完整」。你已经是完整的。你的丰盛是你自己的创造——它来自你的技能、你的努力、你的智慧。所以，当你感到「我做到了」时，停下来。深呼吸。欣赏你创建的花园。你值得这一切。", reversed:"逆位的钱币九是金星和土星的独立变得空虚了。你可能拥有所有的物质东西，但仍然感到空虚，或者相反——你在过度追求物质，试图用「东西」来填补情感空洞。金星的逆行能量提醒你：物质丰盛不是「终点」。它是「工具」——它让你有能力做更多你想做的事。但如果你没有梦想，那再多的钱也不会让你快乐。回到你的内心。你的梦想在等你。", translations:{en:{upright:"The Nine of Pentacles is Venus and Saturn's independence energy. You don't need anyone to 'complete you.' You're already whole. Your abundance is your own creation.", reversed:"The reversed Nine of Pentacles means Venus and Saturn's independence has become empty. Material abundance isn't the 'destination'; it's the 'tool.' What's your dream beyond money?"}} },
  { id:"P10", name:"钱币十", originalName:"Ten of Pentacles", suit:"pentacles", element:"土", astro:"木星/土星 · 传承与家族", keywords:["传承","家族","财富","长久"], uprightBrief:"木星之丰盛传承十代", reversedBrief:"家族冲突或缺乏传承", imageUrl:"icons/stellar/pentacles-10.png", upright:"钱币十牌是木星和土星的传承能量——你的家族和物质资源正在一个长长的传承线上。这不是关于「钱」，而是关于「 Legacy」。木星的能量教你：你不仅仅是在为你自己创造丰盛，你是在为未来的世代创造基础。你的家族是你的根——它们给你身份和意义。所以，当你感到与家人连接时，珍惜它。即使你的家族不完美（没有家族是完美的）。你的家族是你的故事的开始。尊重它。", reversed:"逆位的钱币十是木星和土星的传承变得断裂了。你可能正在经历家族冲突，或者相反——你觉得自己的家族「不够好」。木星的逆行能量提醒你：家族不是「完美的」。它是「真实的」。如果你的家族不完美，那正是为什么你需要他们。你的家族是你的根——即使它们看起来很乱，它们仍然支撑着你。尊重你的根。它们值得被尊重。", translations:{en:{upright:"The Ten of Pentacles is Jupiter and Saturn's legacy energy. You're creating abundance not just for yourself, but for future generations. Your family is your roots — they give you identity and meaning.", reversed:"The reversed Ten of Pentacles means Jupiter and Saturn's legacy has become broken. Family isn't 'perfect'; it's 'real.' Your family is your roots — even if they look messy, they still support you."}} },
  { id:"P11", name:"钱币侍从", originalName:"Page of Pentacles", suit:"pentacles", element:"土", astro:"土星/金星 · 实用与学习", keywords:["实用","学习","新技能","踏实"], uprightBrief:"土星之子踏实学习", reversedBrief:"缺乏落地或学习缓慢", imageUrl:"icons/stellar/pentacles-11.png", upright:"钱币侍从牌是土星和金星的实用能量——一个关于新技能、新工作或新投资机会的消息正在来到你身边。这不是关于「快速致富」，而是关于「踏实」。土星的能量教你：真正的丰盛需要时间和努力来建立。你的学习是你的投资——它会在未来回报你。所以，当你感到「我想学这个」时，投入时间。即使别人说你「太慢了」。真正的技能需要时间来发展。你不需要「快速」。你需要「扎实」。", reversed:"逆位的钱币侍从是土星之子变得不耐烦了。你可能想要快速结果，或者相反——你在学习新东西时感到缓慢和笨拙。土星的逆行能量提醒你：每一个专家都曾经是初学者。如果你觉得自己「不够好」，那可能是因为你在用别人的终点来衡量你的起点。放下比较。你正在你的自己的时间线上。信任它。", translations:{en:{upright:"The Page of Pentacles is Saturn and Venus' practical energy. True abundance takes time and effort to build. When you feel 'I want to learn this,' invest time. You don't need to be 'fast'; you need to be 'solid.'", reversed:"The reversed Page of Pentacles means Saturn's child has become impatient. Every expert was once a beginner. Don't compare your beginning to someone else's middle."}} },
  { id:"P12", name:"钱币骑士", originalName:"Knight of Pentacles", suit:"pentacles", element:"土", astro:"土星/金星 · 可靠与稳健", keywords:["可靠","稳健","耐心","实用"], uprightBrief:"土星骑士稳健前行", reversedBrief:"过于缓慢或抗拒变化", imageUrl:"icons/stellar/pentacles-12.png", upright:"钱币骑士牌是土星和金星的可靠能量——你正在稳步前进，实现你的物质目标。这不是关于「快速」，而是关于「稳健」。土星的能量教你：真正的成功不是「一夜成名」，它是「日复一日的坚持」。你的耐心是你的超能力——它让你能够在别人放弃时继续。所以，当你感到「我想实现这个目标」时，制定计划。然后坚持它。即使别人说你「太慢了」。世界需要更多踏实的人。", reversed:"逆位的钱币骑士是土星和金星的稳健变得过于缓慢了。你可能抗拒变化，或者相反——你在等待「完美时机」来开始行动。土星的逆行能量提醒你：没有「完美时机」。只有「现在」。如果你觉得自己「还没有准备好」，那你可能永远都不会觉得准备好了。完美是一个陷阱。开始吧。即使你的开始是混乱的。你会沿途学习。", translations:{en:{upright:"The Knight of Pentacles is Saturn and Venus' reliable energy. True success isn't 'overnight'; it's 'day after day of persistence.' The world needs more steady people.", reversed:"The reversed Knight of Pentacles means Saturn and Venus' steadiness has become too slow. There's no 'perfect timing.' Only 'now.' Start now, even if your beginning is messy."}} },
  { id:"P13", name:"钱币王后", originalName:"Queen of Pentacles", suit:"pentacles", element:"土", astro:"金星/土星 · 滋养与丰盛", keywords:["滋养","丰盛","实用","接地"], uprightBrief:"金星王后以丰盛滋养大地", reversedBrief:"忽视自我或过度工作", imageUrl:"icons/stellar/pentacles-13.png", upright:"钱币王后牌是金星和土星的滋养能量——你是一个非常实际和滋养的人，能够为自己和他人创造丰盛。这不是关于「工作狂」，而是关于「创造」。金星的能量教你：丰盛是一个创造性的行为——你从星空中带来想法，然后把它们变成地球上的现实。你的实用是你的超能力——它让你能够把梦想变成可触摸的形式。所以，当你感到「我想创造这个」时，相信它。即使别人说你「太实际了」。实际不是你的限制，它是你的超能力。", reversed:"逆位的钱币王后是金星和土星的滋养变得不平衡了。你可能过于工作，忽视了你的健康和其他生活领域，或者相反——你在过度放纵自己，不再关心你的责任。金星的逆行能量提醒你：你无法从空杯中倾倒。如果你觉得自己「需要给更多人」，那先给自己。你值得被滋养。一个满的杯子才能与另一个满的杯子碰杯。", translations:{en:{upright:"The Queen of Pentacles is Venus and Saturn's nurturing energy. Abundance is a creative act — you bring ideas from the stars and turn them into earthly reality. Practicality isn't your limitation; it's your superpower.", reversed:"The reversed Queen of Pentacles means Venus and Saturn's nurturing has become unbalanced. You cannot pour from an empty cup. Fill your own cup first. You deserve to be nourished."}} },
  { id:"P14", name:"钱币国王", originalName:"King of Pentacles", suit:"pentacles", element:"土", astro:"土星/金星 · 丰盛与成功", keywords:["丰盛","成功","实用","领导"], uprightBrief:"土星国王以丰盛统治", reversedBrief:"过度控制或滥用资源", imageUrl:"icons/stellar/pentacles-14.png", upright:"钱币国王牌是土星和金星的丰盛能量——你在物质上非常成功，能够为自己和他人创造安全感和丰盛。这不是关于「贪婪」，而是关于「服务」。土星的能量教你：真正的丰盛不是「拥有最多的玩具」，它是「有能力创造你想要的生活」。你的成功是你的工具——它让你有能力帮助别人。所以，当你感到「我想实现财务自由」时，制定计划。然后执行它。即使别人说你「太野心了」。野心不是你的敌人，它是你的指南针。", reversed:"逆位的钱币国王是土星和金星的丰盛变得扭曲了。你可能正在使用你的资源来控制他人，或者相反——你在过度认同你的「成功」，以至于你失去了与真正重要的东西的连接。土星的逆行能量提醒你：你不需要「赚更多的钱」才能有价值。你的价值不是你的银行账户余额。即使你失去了所有的钱，你仍然是值得的。真正的丰盛包括灵魂。", translations:{en:{upright:"The King of Pentacles is Saturn and Venus' abundance energy. True abundance isn't 'having the most toys'; it's 'having the ability to create the life you want.' Ambition isn't your enemy; it's your compass.", reversed:"The reversed King of Pentacles means Saturn and Venus' abundance has become distorted. Your worth isn't your bank account balance. Even if you lost all your money, you'd still be worthy."}} }
];
