// 魔法主题塔罗牌数据 - 78张牌完整版（优化版）
// 新增字段：element(元素), keywords(关键词), uprightBrief(正位简义), reversedBrief(逆位简义), imageUrl(图片路径)
const tarotCards = [
  // ============ 大阿卡纳 Major Arcana (22张) ============
  {
    id: 0,
    name: "愚者",
    themeName: "魔法少年",
    originalName: "The Fool",
    suit: "major",
    element: "风",
    keywords: ["新的开始", "冒险", "自由", "天真", "无限可能"],
    uprightBrief: "新的冒险即将展开",
    reversedBrief: "盲目冲动缺乏规划",
    imageUrl: "icons/major-00.png",
    upright: "新的冒险即将展开。带着勇气踏上未知旅程，相信自己的直觉。魔法世界充满无限可能，勇敢地迈出第一步。",
    reversed: "盲目冲动可能导致危险。需要更谨慎地评估风险，不要被幻想蒙蔽双眼。停下来思考再行动。"
  },
  {
    id: 1,
    name: "魔术师",
    themeName: "智慧导师",
    originalName: "The Magician",
    suit: "major",
    element: "风",
    keywords: ["创造力", "技能", "行动力", "意志力", "资源"],
    uprightBrief: "拥有实现目标的一切",
    reversedBrief: "才能被浪费或误用",
    imageUrl: "icons/major-01.png",
    upright: "你拥有实现目标所需的一切工具和才能。现在是采取行动的最佳时机，运用你的智慧和魔力创造奇迹。",
    reversed: "才能被浪费或误用。可能感到能力不足或缺乏资源，需要重新评估自己的优势和机会。"
  },
  {
    id: 2,
    name: "女祭司",
    themeName: "严厉教师",
    originalName: "The High Priestess",
    suit: "major",
    element: "水",
    keywords: ["直觉", "潜意识", "神秘", "内在智慧", "静心"],
    uprightBrief: "倾听内心的声音",
    reversedBrief: "忽视直觉被表象迷惑",
    imageUrl: "icons/major-02.png",
    upright: "倾听内心的声音和直觉。隐藏的知识即将浮现，信任你的潜意识。静心冥想，答案就在其中。",
    reversed: "忽视了直觉和内在智慧。可能被表面现象迷惑，需要重新连接内在的声音。"
  },
  {
    id: 3,
    name: "女皇",
    themeName: "慈爱母亲",
    originalName: "The Empress",
    suit: "major",
    element: "土",
    keywords: ["丰饶", "创造力", "养育", "感官", "富足"],
    uprightBrief: "丰收与富足的时刻",
    reversedBrief: "创造力受阻过度依赖",
    imageUrl: "icons/major-03.png",
    upright: "丰收与富足的时刻。创造力旺盛，充满母性的温暖与关怀。享受生活中的美好事物，分享你的爱。",
    reversed: "创造力受阻或过度依赖他人。可能在人际关系中失去自我，需要重新找回内在的平衡。"
  },
  {
    id: 4,
    name: "皇帝",
    themeName: "黑暗领主",
    originalName: "The Emperor",
    suit: "major",
    element: "火",
    keywords: ["权威", "稳定", "领导力", "结构", "控制"],
    uprightBrief: "稳定与秩序的建立",
    reversedBrief: "过于专制缺乏自律",
    imageUrl: "icons/major-04.png",
    upright: "稳定与秩序的建立。运用领导力和理性思维掌控局面。结构是成功的基础，坚持你的原则。",
    reversed: "过于专制或缺乏自律。可能面临权威的挑战，需要灵活变通而不是固执己见。"
  },
  {
    id: 5,
    name: "教皇",
    themeName: "复杂导师",
    originalName: "The Hierophant",
    suit: "major",
    element: "土",
    keywords: ["传统", "信仰", "指引", "规则", "导师"],
    uprightBrief: "寻求传统精神指引",
    reversedBrief: "挑战传统精神束缚",
    imageUrl: "icons/major-05.png",
    upright: "寻求传统智慧和精神指引。遵循既定的道路和传统价值观。向值得信赖的导师学习，获得深层理解。",
    reversed: "挑战传统或感到精神束缚。需要打破常规，寻找属于自己的真理和道路。"
  },
  {
    id: 6,
    name: "恋人",
    themeName: "挚友伙伴",
    originalName: "The Lovers",
    suit: "major",
    element: "风",
    keywords: ["选择", "爱情", "和谐", "价值观", "结合"],
    uprightBrief: "重要的选择和价值观契合",
    reversedBrief: "关系不和谐价值观冲突",
    imageUrl: "icons/major-06.png",
    upright: "重要的选择和价值观的契合。爱情与和谐的关系正在发展。倾听内心的声音，做出符合真心的选择。",
    reversed: "关系中的不和谐或价值观冲突。可能面临艰难的选择，需要诚实地面对自己的感受。"
  },
  {
    id: 7,
    name: "战车",
    themeName: "秘密组织",
    originalName: "The Chariot",
    suit: "major",
    element: "水",
    keywords: ["意志", "胜利", "决心", "控制", "进展"],
    uprightBrief: "意志力战胜障碍",
    reversedBrief: "失去控制方向不明",
    imageUrl: "icons/major-07.png",
    upright: "意志力战胜障碍。充满决心和动力向目标前进。控制你的情绪和欲望，胜利就在前方。",
    reversed: "失去控制或方向不明。可能遇到阻碍和挫折，需要重新调整心态和策略。"
  },
  {
    id: 8,
    name: "力量",
    themeName: "迷之少女",
    originalName: "Strength",
    suit: "major",
    element: "火",
    keywords: ["勇气", "耐心", "内在力量", "温柔", "同理心"],
    uprightBrief: "内在的力量和勇气",
    reversedBrief: "自我怀疑内心恐惧",
    imageUrl: "icons/major-08.png",
    upright: "内在的力量和勇气。用温柔和耐心克服困难。真正的力量来自于内心的平静与自信。",
    reversed: "自我怀疑或内心恐惧。可能感到无力或缺乏自信，需要重新连接内在的力量源泉。"
  },
  {
    id: 9,
    name: "隐士",
    themeName: "隐居智者",
    originalName: "The Hermit",
    suit: "major",
    element: "土",
    keywords: ["内省", "智慧", "独处", "寻求真理", "指引"],
    uprightBrief: "内省与独处的时刻",
    reversedBrief: "孤立过度拒绝帮助",
    imageUrl: "icons/major-09.png",
    upright: "内省与独处的时刻。暂时退出喧嚣，寻找内在的智慧。孤独是成长的必经之路。",
    reversed: "孤立过度或拒绝帮助。可能在逃避现实，需要重新融入世界并分享你的智慧。"
  },
  {
    id: 10,
    name: "命运之轮",
    themeName: "时间魔法",
    originalName: "Wheel of Fortune",
    suit: "major",
    element: "火",
    keywords: ["命运", "转变", "机遇", "周期", "运气"],
    uprightBrief: "命运的转变和机遇到来",
    reversedBrief: "生活中的挫折感命运不公",
    imageUrl: "icons/major-10.png",
    upright: "命运的转变和机遇的到来。接受生活的变化，好运正在转向你。这是一个周期的结束和新的开始。",
    reversed: "生活中的挫折或坏运气。感觉命运不公，但记住车轮总会转动，困难只是暂时的。"
  },
  {
    id: 11,
    name: "正义",
    themeName: "正义之厅",
    originalName: "Justice",
    suit: "major",
    element: "风",
    keywords: ["公正", "真理", "因果", "平衡", "诚实"],
    uprightBrief: "公正与真理的胜利",
    reversedBrief: "不公正或逃避责任",
    imageUrl: "icons/major-11.png",
    upright: "公正与真理的胜利。你的行为将得到相应的回报。保持诚实和正直，因果循环不会缺席。",
    reversed: "不公正或逃避责任。可能面临不公平的对待，需要坚持真理并寻求正义。"
  },
  {
    id: 12,
    name: "倒吊人",
    themeName: "自由之魂",
    originalName: "The Hanged Man",
    suit: "major",
    element: "水",
    keywords: ["牺牲", "等待", "换个角度", "放手", "觉醒"],
    uprightBrief: "牺牲与等待的智慧",
    reversedBrief: "拖延不必要的牺牲",
    imageUrl: "icons/major-12.png",
    upright: "牺牲与等待的智慧。换个角度看问题，暂时的停顿带来更深的理解。放下执念，接受当下的状态。",
    reversed: "拖延或不必要的牺牲。可能陷入僵局无法自拔，需要采取行动而不是被动等待。"
  },
  {
    id: 13,
    name: "死神",
    themeName: "黑暗碎片",
    originalName: "Death",
    suit: "major",
    element: "水",
    keywords: ["结束", "转化", "重生", "释放", "改变"],
    uprightBrief: "结束与新的开始",
    reversedBrief: "抗拒变化无法放下过去",
    imageUrl: "icons/major-13.png",
    upright: "结束与新的开始。旧的事物必须消亡，新的才能诞生。接受转变，这是成长的必经之路。",
    reversed: "抗拒变化或无法放下过去。可能陷入停滞，需要勇敢地面对结束才能迎来新生。"
  },
  {
    id: 14,
    name: "节制",
    themeName: "变形使者",
    originalName: "Temperance",
    suit: "major",
    element: "火",
    keywords: ["平衡", "耐心", "适度", "调和", "长远"],
    uprightBrief: "平衡与和谐的状态",
    reversedBrief: "失衡或过度行为",
    imageUrl: "icons/major-14.png",
    upright: "平衡与和谐的状态。耐心地融合对立的力量。适度与中庸之道将带来长久的平静与满足。",
    reversed: "失衡或过度行为。可能缺乏远见或过于冲动，需要重新寻找生活的平衡点。"
  },
  {
    id: 15,
    name: "恶魔",
    themeName: "绝望阴影",
    originalName: "The Devil",
    suit: "major",
    element: "土",
    keywords: ["束缚", "物质欲望", "阴影", "觉醒", "自由"],
    uprightBrief: "面对内心的阴影和束缚",
    reversedBrief: "从束缚中解放",
    imageUrl: "icons/major-15.png",
    upright: "面对内心的阴影和束缚。可能是物质欲望或不良习惯的掌控。认识到真正的束缚来自于内心。",
    reversed: "从束缚中解放。打破旧有的模式，重获自由。意识到自己的力量，摆脱负面的影响。"
  },
  {
    id: 16,
    name: "塔",
    themeName: "最终决战",
    originalName: "The Tower",
    suit: "major",
    element: "火",
    keywords: ["突变", "崩塌", "觉醒", "重建", "真相"],
    uprightBrief: "突然的转变和崩塌",
    reversedBrief: "避免灾难延迟必然改变",
    imageUrl: "icons/major-16.png",
    upright: "突然的转变和崩塌。旧的结构必须被摧毁才能重建。虽然痛苦，但这是必要的净化过程。",
    reversed: "避免灾难或延迟必然的改变。内在的动荡需要释放，逃避只会让情况变得更糟。"
  },
  {
    id: 17,
    name: "星星",
    themeName: "希望之光",
    originalName: "The Star",
    suit: "major",
    element: "风",
    keywords: ["希望", "灵感", "治愈", "信仰", "宁静"],
    uprightBrief: "希望与灵感的涌现",
    reversedBrief: "失去希望或感到绝望",
    imageUrl: "icons/major-17.png",
    upright: "希望与灵感的涌现。在黑暗中看到光明，相信美好的未来。这是治愈和重新充满信心的时刻。",
    reversed: "失去希望或感到绝望。可能需要重新连接内心的信仰，在困境中寻找微光。"
  },
  {
    id: 18,
    name: "月亮",
    themeName: "双面之人",
    originalName: "The Moon",
    suit: "major",
    element: "水",
    keywords: ["幻觉", "恐惧", "潜意识", "不确定", "直觉"],
    uprightBrief: "幻觉与不确定性的时期",
    reversedBrief: "恐惧消散真相大白",
    imageUrl: "icons/major-18.png",
    upright: "幻觉与不确定性的时期。信任直觉但小心错觉。隐藏的恐惧需要被面对，真相即将浮现。",
    reversed: "恐惧消散，真相大白。走出迷茫，清晰地看到事物的本质。释放内心的恐惧。"
  },
  {
    id: 19,
    name: "太阳",
    themeName: "胜利之翼",
    originalName: "The Sun",
    suit: "major",
    element: "火",
    keywords: ["喜悦", "成功", "活力", "光明", "正能量"],
    uprightBrief: "喜悦与成功的到来",
    reversedBrief: "暂时的阴霾或过度乐观",
    imageUrl: "icons/major-19.png",
    upright: "喜悦与成功的到来。光明正大地追求幸福，一切都在最好的状态下。这是充满活力和快乐的时期。",
    reversed: "暂时的阴霾或过度的乐观。可能需要调整期望，在光明中寻找真实而非幻象。"
  },
  {
    id: 20,
    name: "审判",
    themeName: "亡者之石",
    originalName: "Judgement",
    suit: "major",
    element: "火",
    keywords: ["觉醒", "重生", "使命", "反思", "救赎"],
    uprightBrief: "觉醒与重生",
    reversedBrief: "自我怀疑拒绝反思",
    imageUrl: "icons/major-20.png",
    upright: "觉醒与重生。过去的行动需要被审视，这是反思和宽恕的时刻。召唤你走向更高的使命。",
    reversed: "自我怀疑或拒绝反思。可能在逃避过去的错误，需要勇敢地面对并寻求救赎。"
  },
  {
    id: 21,
    name: "世界",
    themeName: "永恒之石",
    originalName: "The World",
    suit: "major",
    element: "土",
    keywords: ["完成", "圆满", "成就", "旅行", "整合"],
    uprightBrief: "完成与圆满",
    reversedBrief: "未完成或延迟成功",
    imageUrl: "icons/major-21.png",
    upright: "完成与圆满。一个周期的完美结束，成就与 fulfillment。你已经准备好迎接更大的冒险。",
    reversed: "未完成或延迟成功。可能急于求成，需要完善细节才能真正完成旅程。"
  },

  // ============ 小阿卡纳 - 权杖 Wands (14张) ============
  // 权杖组对应：格兰芬多精神 - 行动、创意、冒险
  { id:"W1", name:"权杖王牌", themeName:"格兰芬多之剑", originalName:"Ace of Wands", suit:"wands", element:"火",
    keywords:["创意","灵感","新开始","潜力","热情"], uprightBrief:"创意的新火花", reversedBrief:"创意受阻延迟开始",
    imageUrl:"icons/wands-01.png",
    upright:"创意的火花和新的灵感。充满激情的项目即将开始。抓住这个充满潜力的时刻，勇敢行动。",
    reversed:"创意受阻或延迟开始。可能缺乏信心或方向不明，需要重新点燃内心的火焰。"},
  { id:"W2", name:"权杖二", themeName:"分院帽", originalName:"Two of Wands", suit:"wands", element:"火",
    keywords:["规划","远见","扩张","决策","探索"], uprightBrief:"规划与远见", reversedBrief:"恐惧改变计划延迟",
    imageUrl:"icons/wands-02.png",
    upright:"规划和远见。站在高处俯瞰未来，制定长远的计划。这是扩张和探索新领域的好时机。",
    reversed:"恐惧改变或计划延迟。可能在犹豫不决，需要勇敢地迈出舒适区。"},
  { id:"W3", name:"权杖三", themeName:"魁地奇世界杯", originalName:"Three of Wands", suit:"wands", element:"火",
    keywords:["远见","成果","扩展","等待","进展"], uprightBrief:"远见卓识显现成果", reversedBrief:"进展延迟视野受限",
    imageUrl:"icons/wands-03.png",
    upright:"远见卓识开始显现成果。等待已久的机会终于到来。扩展视野，迎接更广阔的天地。",
    reversed:"进展延迟或视野受限。可能遇到障碍，需要重新评估长期策略。"},
  { id:"W4", name:"权杖四", themeName:"霍格沃茨城堡", originalName:"Four of Wands", suit:"wands", element:"火",
    keywords:["庆祝","和谐","稳定","团聚","成果"], uprightBrief:"庆祝与和谐", reversedBrief:"不和谐延迟的庆祝",
    imageUrl:"icons/wands-04.png",
    upright:"庆祝与和谐。努力得到回报，享受成果和团聚的喜悦。这是稳定与幸福的时刻。",
    reversed:"不和谐或延迟的庆祝。可能缺乏稳定感，需要建立更牢固的基础。"},
  { id:"W5", name:"权杖五", themeName:"学院杯竞赛", originalName:"Five of Wands", suit:"wands", element:"火",
    keywords:["竞争","冲突","成长","观点","挑战"], uprightBrief:"竞争与冲突", reversedBrief:"避免冲突内在混乱",
    imageUrl:"icons/wands-05.png",
    upright:"竞争与冲突。不同的观点相互碰撞，这是通过竞争获得成长的机会。保持开放的心态。",
    reversed:"避免冲突或内在的混乱。可能感到不堪重负，需要找到和平的解决方案。"},
  { id:"W6", name:"权杖六", themeName:"魁地奇胜利", originalName:"Six of Wands", suit:"wands", element:"火",
    keywords:["胜利","认可","自信","成功","荣誉"], uprightBrief:"胜利与认可", reversedBrief:"缺乏认可或自大",
    imageUrl:"icons/wands-06.png",
    upright:"胜利与认可。你的努力得到了应有的赞赏。自信地前进，成功正在向你招手。",
    reversed:"缺乏认可或自大。可能感到被忽视，或者过于自负需要保持谦逊。"},
  { id:"W7", name:"权杖七", themeName:"勇敢对抗", originalName:"Seven of Wands", suit:"wands", element:"火",
    keywords:["防御","坚持","挑战","勇气","立场"], uprightBrief:"坚守立场和防御", reversedBrief:"不堪重负放弃抵抗",
    imageUrl:"icons/wands-07.png",
    upright:"坚守立场和防御。面对挑战需要勇气和毅力。相信自己的立场，不要轻易放弃。",
    reversed:"不堪重负或放弃抵抗。可能感到无法继续，需要重新评估是否值得这场战斗。"},
  { id:"W8", name:"权杖八", themeName:"飞天汽车", originalName:"Eight of Wands", suit:"wands", element:"火",
    keywords:["快速","进展","消息","行动","加速"], uprightBrief:"快速进展和能量流动", reversedBrief:"延迟缺乏方向",
    imageUrl:"icons/wands-08.png",
    upright:"快速进展和能量流动。消息或机会迅速到来。把握时机，事情正在加速发展。",
    reversed:"延迟或缺乏方向。可能感到事情停滞，需要重新找到行动的节奏。"},
  { id:"W9", name:"权杖九", themeName:"最后的守护", originalName:"Nine of Wands", suit:"wands", element:"火",
    keywords:["韧性","坚持","防御","警惕","毅力"], uprightBrief:"韧性和持久的防御", reversedBrief:"精疲力竭或偏执",
    imageUrl:"icons/wands-09.png",
    upright:"韧性和持久的防御。虽然疲惫但依然坚持。你已经接近终点，再坚持一下。",
    reversed:"精疲力竭或偏执。可能承担了太多，需要学会放下一些负担。"},
  { id:"W10", name:"权杖十", themeName:"沉重的责任", originalName:"Ten of Wands", suit:"wands", element:"火",
    keywords:["责任","压力","负担","坚持","释放"], uprightBrief:"承担重任和压力", reversedBrief:"释放负担或无法承受",
    imageUrl:"icons/wands-10.png",
    upright:"承担重任和压力。虽然艰难但你能够承受。记住，有时需要放下一些负担才能轻装前行。",
    reversed:"释放负担或无法承受。可能终于放下了重担，或者需要寻求帮助来完成任务。"},
  { id:"W11", name:"权杖侍从", themeName:"年轻的巫师", originalName:"Page of Wands", suit:"wands", element:"火",
    keywords:["热情","新想法","冒险","自由","探索"], uprightBrief:"充满热情的新想法", reversedBrief:"延迟或鲁莽",
    imageUrl:"icons/wands-11.png",
    upright:"充满热情的新想法。冒险精神和自由探索的欲望。保持好奇心，勇敢尝试新事物。",
    reversed:"延迟或鲁莽。可能缺乏方向或过于冲动，需要更有计划地行动。"},
  { id:"W12", name:"权杖骑士", themeName:"骑士巴士", originalName:"Knight of Wands", suit:"wands", element:"火",
    keywords:["行动","冒险","急躁","魅力","速度"], uprightBrief:"迅速行动和冒险", reversedBrief:"鲁莽或延迟",
    imageUrl:"icons/wands-12.png",
    upright:"迅速行动和冒险。充满魅力和活力，但有时可能过于急躁。把握机会，但也要留意细节。",
    reversed:"鲁莽或延迟。可能行动过于冲动导致问题，需要放慢脚步思考。"},
  { id:"W13", name:"权杖王后", themeName:"海格", originalName:"Queen of Wands", suit:"wands", element:"火",
    keywords:["热情","自信","魅力","创造力","独立"], uprightBrief:"热情和自信的领导力", reversedBrief:"缺乏自信过度支配",
    imageUrl:"icons/wands-13.png",
    upright:"热情和自信的领导力。充满魅力和创造力，能够激励他人。相信自己，展现你的光芒。",
    reversed:"缺乏自信或过度支配。可能感到自我怀疑，或者变得过于控制欲强。"},
  { id:"W14", name:"权杖国王", themeName:"狂热者", originalName:"King of Wands", suit:"wands", element:"火",
    keywords:["远见","领导力","企业家","魅力","行动"], uprightBrief:"远见卓识的领导力", reversedBrief:"专制或缺乏远见",
    imageUrl:"icons/wands-14.png",
    upright:"远见卓识的领导力。充满魅力和企业家精神。自然地吸引他人跟随你的愿景。",
    reversed:"专制或缺乏远见。可能变得过于控制或冲动，需要平衡热情与理智。"},

  // ============ 小阿卡纳 - 圣杯 Cups (14张) ============
  // 圣杯组对应：赫奇帕奇精神 - 情感、直觉、关系
  { id:"C1", name:"圣杯王牌", themeName:"爱之魔药", originalName:"Ace of Cups", suit:"cups", element:"水",
    keywords:["新情感","爱","喜悦","直觉","灵感"], uprightBrief:"新的情感开始", reversedBrief:"情感受阻内在空虚",
    imageUrl:"icons/cups-01.png",
    upright:"新的情感开始。爱、喜悦和直觉的涌现。打开你的心，接受情感的馈赠。",
    reversed:"情感受阻或内在空虚。可能需要 healing 过去的情感创伤，重新连接内心的感受。"},
  { id:"C2", name:"圣杯二", themeName:"友谊的纽带", originalName:"Two of Cups", suit:"cups", element:"水",
    keywords:["和谐","吸引","合作","关系","平等"], uprightBrief:"和谐的关系和相互吸引", reversedBrief:"关系失衡或误解",
    imageUrl:"icons/cups-02.png",
    upright:"和谐的关系和相互吸引。平等的合作和深厚的情感连接。这是建立重要关系的时刻。",
    reversed:"关系失衡或误解。可能面临分歧，需要沟通和理解来修复关系。"},
  { id:"C3", name:"圣杯三", themeName:"霍格沃茨宴会", originalName:"Three of Cups", suit:"cups", element:"水",
    keywords:["庆祝","友谊","社交","欢乐","团聚"], uprightBrief:"庆祝和友谊的喜悦", reversedBrief:"过度放纵社交孤立",
    imageUrl:"icons/cups-03.png",
    upright:"庆祝和友谊的喜悦。与挚友共度的美好时光。分享快乐，扩大你的社交圈。",
    reversed:"过度放纵或社交孤立。可能在群体中感到不适，需要平衡社交与个人空间。"},
  { id:"C4", name:"圣杯四", themeName:"冥想室", originalName:"Four of Cups", suit:"cups", element:"水",
    keywords:["沉思","重新评估","不满","觉醒","机会"], uprightBrief:"沉思和重新评估", reversedBrief:"觉醒和新机会",
    imageUrl:"icons/cups-04.png",
    upright:"沉思和重新评估。可能对现状感到不满，但需要睁开眼睛看到已有的祝福。",
    reversed:"觉醒和新机会。从冷漠中走出，重新拥抱生活的可能性。"},
  { id:"C5", name:"圣杯五", themeName:"失去的伙伴", originalName:"Five of Cups", suit:"cups", element:"水",
    keywords:["悲伤","失落","遗憾","恢复","原谅"], uprightBrief:"失落和悲伤", reversedBrief:"从悲伤中恢复",
    imageUrl:"icons/cups-05.png",
    upright:"失落和悲伤。专注于失去的东西而忽视了还在身边的。允许自己悲伤，然后向前看。",
    reversed:"从悲伤中恢复。接受过去，重新开始。学会原谅自己和他人。"},
  { id:"C6", name:"圣杯六", themeName:"霍格莫德村", originalName:"Six of Cups", suit:"cups", element:"水",
    keywords:["怀旧","童年","回忆","分享","纯真"], uprightBrief:"怀旧和童真的快乐", reversedBrief:"困在过去天真过度",
    imageUrl:"icons/cups-06.png",
    upright:"怀旧和童真的快乐。美好的回忆带来温暖。分享和慷慨让关系更加深厚。",
    reversed:"困在过去或天真过度。可能需要放下过去，或者过于依赖旧有的模式。"},
  { id:"C7", name:"圣杯七", themeName:"幻象", originalName:"Seven of Cups", suit:"cups", element:"水",
    keywords:["想象","选择","幻想","欲望","困惑"], uprightBrief:"丰富的想象和多个选择", reversedBrief:"从幻想中清醒",
    imageUrl:"icons/cups-07.png",
    upright:"丰富的想象和多个选择。可能感到困惑不知如何选择。需要澄清你的真实欲望。",
    reversed:"从幻想中清醒。做出实际的选择，将梦想变为现实。"},
  { id:"C8", name:"圣杯八", themeName:"寻找更深的意义", originalName:"Eight of Cups", suit:"cups", element:"水",
    keywords:["离开","寻求","成长","勇气","蜕变"], uprightBrief:"离开不满足寻找更深意义", reversedBrief:"害怕离开或回到过去",
    imageUrl:"icons/cups-08.png",
    upright:"离开不满足的状况寻找更深的意义。虽然有遗憾但必须前行。这是灵魂成长的旅程。",
    reversed:"害怕离开或回到过去。可能犹豫不决，需要勇气面对改变。"},
  { id:"C9", name:"圣杯九", themeName:"如愿以偿", originalName:"Nine of Cups", suit:"cups", element:"水",
    keywords:["满足","愿望成真","愉悦","富足","享受"], uprightBrief:"愿望成真和情感的满足", reversedBrief:"虚荣或贪婪",
    imageUrl:"icons/cups-09.png",
    upright:"愿望成真和情感的满足。这是一个充满喜悦和满足的时期。享受你努力带来的成果。",
    reversed:"虚荣或贪婪。可能过于关注物质满足而忽视精神成长，需要平衡欲望。"},
  { id:"C10", name:"圣杯十", themeName:"韦斯莱家的爱", originalName:"Ten of Cups", suit:"cups", element:"水",
    keywords:["家庭","和谐","幸福","长久","归属"], uprightBrief:"家庭的和谐与长久幸福", reversedBrief:"家庭不和破碎的梦想",
    imageUrl:"icons/cups-10.png",
    upright:"家庭的和谐与长久的幸福。真正的快乐来自于爱与归属。珍惜与亲人共度的时光。",
    reversed:"家庭不和或破碎的梦想。可能面临关系问题，需要努力修复和维护。"},
  { id:"C11", name:"圣杯侍从", themeName:"年轻的巫师", originalName:"Page of Cups", suit:"cups", element:"水",
    keywords:["情感萌芽","直觉","创意","敏感","消息"], uprightBrief:"情感的萌芽和直觉的消息", reversedBrief:"情感不成熟错过直觉",
    imageUrl:"icons/cups-11.png",
    upright:"情感的萌芽和直觉的消息。保持开放和敏感，创造性的想法正在涌现。",
    reversed:"情感不成熟或错过直觉。可能需要更多地关注内心世界，发展情商。"},
  { id:"C12", name:"圣杯骑士", themeName:"浪漫的追求者", originalName:"Knight of Cups", suit:"cups", element:"水",
    keywords:["浪漫","追求","理想","魅力","敏感"], uprightBrief:"浪漫和追求理想", reversedBrief:"情感操纵不切实际",
    imageUrl:"icons/cups-12.png",
    upright:"浪漫和追求理想。带着情感和魅力前进。跟随你的心，但也要保持理智。",
    reversed:"情感操纵或不切实际。可能过于理想化，需要脚踏实地。"},
  { id:"C13", name:"圣杯王后", themeName:"秋·张", originalName:"Queen of Cups", suit:"cups", element:"水",
    keywords:["同情心","直觉","慈悲","敏感","理解"], uprightBrief:"同情心和直觉的智慧", reversedBrief:"情感依赖封闭内心",
    imageUrl:"icons/cups-13.png",
    upright:"同情心和直觉的智慧。深深地理解他人，用爱和慈悲引导。信任你的直觉。",
    reversed:"情感依赖或封闭内心。可能在情感上过度投入，需要建立健康的界限。"},
  { id:"C14", name:"圣杯国王", themeName:"卢平教授", originalName:"King of Cups", suit:"cups", element:"水",
    keywords:["成熟","平衡","同理心","智慧","稳定"], uprightBrief:"情感的成熟和平衡", reversedBrief:"情感操控压抑感情",
    imageUrl:"icons/cups-14.png",
    upright:"情感的成熟和平衡。用同理心和智慧领导。在情感表达和理智之间找到完美平衡。",
    reversed:"情感操控或压抑感情。可能滥用情感力量，或者无法表达真实的感受。"},

  // ============ 小阿卡纳 - 宝剑 Swords (14张) ============
  // 宝剑组对应：拉文克劳精神 - 思维、真理、挑战
  { id:"S1", name:"宝剑王牌", themeName:"格兰芬多宝剑", originalName:"Ace of Swords", suit:"swords", element:"风",
    keywords:["真理","清晰","突破","新想法","正义"], uprightBrief:"清晰的思维和突破性的真理", reversedBrief:"思维混乱滥用真理",
    imageUrl:"icons/swords-01.png",
    upright:"清晰的思维和突破性的真理。新的想法和洞察力。用理性和逻辑切割迷惑。",
    reversed:"思维混乱或滥用真理。可能沟通不当，需要澄清思路和意图。"},
  { id:"S2", name:"宝剑二", themeName:"僵局", originalName:"Two of Swords", suit:"swords", element:"风",
    keywords:["两难","选择","僵局","平衡","回避"], uprightBrief:"两难的选择和内心的僵局", reversedBrief:"信息不明避免决定",
    imageUrl:"icons/swords-02.png",
    upright:"两难的选择和内心的僵局。需要平衡对立的观点。暂时封闭情感，用理性做决定。",
    reversed:"信息不明或避免决定。可能终于做出了选择，或者需要更多信息来做决定。"},
  { id:"S3", name:"宝剑三", themeName:"心碎", originalName:"Three of Swords", suit:"swords", element:"风",
    keywords:["心碎","痛苦","疗愈","宽恕","释放"], uprightBrief:"心碎和痛苦的时刻", reversedBrief:"从痛苦中恢复",
    imageUrl:"icons/swords-03.png",
    upright:"心碎和痛苦的时刻。虽然艰难但是必要的净化。允许自己感受痛苦，这是愈合的开始。",
    reversed:"从痛苦中恢复。宽恕和释放过去。伤口愈合，准备重新打开心扉。"},
  { id:"S4", name:"宝剑四", themeName:"休息与恢复", originalName:"Four of Swords", suit:"swords", element:"风",
    keywords:["休息","反思","恢复","平静","准备"], uprightBrief:"休息和反思的时期", reversedBrief:"不安或急于行动",
    imageUrl:"icons/swords-04.png",
    upright:"休息和反思的时期。从混乱中退隐，恢复精力和清晰度。静心思考后再行动。",
    reversed:"不安或急于行动。可能休息不足就匆忙返回，需要更多时间恢复。"},
  { id:"S5", name:"宝剑五", themeName:"无谓的胜利", originalName:"Five of Swords", suit:"swords", element:"风",
    keywords:["冲突","胜利","空虚"," ego","和解"], uprightBrief:"冲突和空虚的胜利", reversedBrief:"和解或接受失败",
    imageUrl:"icons/swords-05.png",
    upright:"冲突和空虚的胜利。赢得战斗但失去关系。反思什么才是真正重要的。",
    reversed:"和解或接受失败。从冲突中学习和成长。放下 ego，寻求和平。"},
  { id:"S6", name:"宝剑六", themeName:"渡湖", originalName:"Six of Swords", suit:"swords", element:"风",
    keywords:["过渡","离开","疗愈","旅程","平静"], uprightBrief:"过渡和离开困难", reversedBrief:"抵抗改变困在困境中",
    imageUrl:"icons/swords-06.png",
    upright:"过渡和离开困难。虽然不舍但必须前行。这是通往更平静水域的旅程。",
    reversed:"抵抗改变或困在困境中。可能不愿意离开舒适区，需要勇气面对过渡。"},
  { id:"S7", name:"宝剑七", themeName:"狡猾的计划", originalName:"Seven of Swords", suit:"swords", element:"风",
    keywords:["策略","欺骗","智慧","不诚实","隐瞒"], uprightBrief:"策略和不正当的手段", reversedBrief:"坦白或内疚",
    imageUrl:"icons/swords-07.png",
    upright:"策略和不正当的手段。可能需要运用智慧而非力量。小心被欺骗或自欺。",
    reversed:"坦白或内疚。可能真相大白，或者需要诚实地面对自己的行动。"},
  { id:"S8", name:"宝剑八", themeName:"自我束缚", originalName:"Eight of Swords", suit:"swords", element:"风",
    keywords:["限制","束缚","恐惧","觉醒","自由"], uprightBrief:"感觉被困和受限", reversedBrief:"解放和自我发现",
    imageUrl:"icons/swords-08.png",
    upright:"感觉被困和受限。但实际上束缚多来自于内心。重新审视处境，你会发现出路。",
    reversed:"解放和自我发现。从限制中挣脱，重新获得自由和清晰的视野。"},
  { id:"S9", name:"宝剑九", themeName:"噩梦", originalName:"Nine of Swords", suit:"swords", element:"风",
    keywords:["焦虑","恐惧","噩梦","担忧","恢复"], uprightBrief:"焦虑和不眠之夜", reversedBrief:"从焦虑中恢复",
    imageUrl:"icons/swords-09.png",
    upright:"焦虑和不眠之夜。担忧和恐惧在夜间放大。寻求支持，不要独自承受。",
    reversed:"从焦虑中恢复。噩梦结束，黎明到来。学会管理担忧，寻找内心的平静。"},
  { id:"S10", name:"宝剑十", themeName:"终结", originalName:"Ten of Swords", suit:"swords", element:"风",
    keywords:["结束","最低谷","重生","释放","完成"], uprightBrief:"痛苦的结束和最低谷", reversedBrief:"从绝境中恢复",
    imageUrl:"icons/swords-10.png",
    upright:"痛苦的结束和最低谷。虽然看起来绝望，但这是结束也是新开始的可能。接受无法改变的。",
    reversed:"从绝境中恢复。最糟糕的已经过去，慢慢重建。找到从废墟中站起来的力量。"},
  { id:"S11", name:"宝剑侍从", themeName:"猫头鹰邮差", originalName:"Page of Swords", suit:"swords", element:"风",
    keywords:["好奇","信息","沟通","警觉","真相"], uprightBrief:"好奇心和信息的好奇", reversedBrief:"八卦或鲁莽的沟通",
    imageUrl:"icons/swords-11.png",
    upright:"好奇心和信息的好奇。敏锐的观察和直接的沟通。保持警惕，真相即将揭露。",
    reversed:"八卦或鲁莽的沟通。可能说话不经思考，或者过于多疑需要辨别信息。"},
  { id:"S12", name:"宝剑骑士", themeName:"摄魂怪的吻", originalName:"Knight of Swords", suit:"swords", element:"风",
    keywords:["行动","果断","激进","速度","直言"], uprightBrief:"迅速和直接的行动", reversedBrief:"鲁莽或冷酷",
    imageUrl:"icons/swords-12.png",
    upright:"迅速和直接的行动。锐利的思维和果断的决策。但小心不要过于冲动而伤到他人。",
    reversed:"鲁莽或冷酷。可能行动过于激进，需要放慢速度考虑后果。"},
  { id:"S13", name:"宝剑王后", themeName:"赫敏·格兰杰", originalName:"Queen of Swords", suit:"swords", element:"风",
    keywords:["清晰","独立","诚实","智慧","敏锐"], uprightBrief:"清晰的思维和独立的判断", reversedBrief:"冷酷或过于批判",
    imageUrl:"icons/swords-13.png",
    upright:"清晰的思维和独立的判断。用智慧和诚实沟通。不畏惧说出真相即使它很尖锐。",
    reversed:"冷酷或过于批判。可能变得尖酸刻薄，需要平衡真理与同情心。"},
  { id:"S14", name:"宝剑国王", themeName:"魔法部部长", originalName:"King of Swords", suit:"swords", element:"风",
    keywords:["理智","公正","权威","真理","纪律"], uprightBrief:"理智的领导力和公正的裁决", reversedBrief:"专制或滥用权力",
    imageUrl:"icons/swords-14.png",
    upright:"理智的领导力和公正的裁决。用逻辑和真理引导他人。权威而不专制，明智而不冷漠。",
    reversed:"专制或滥用权力。可能变得冷酷无情，需要平衡理性与同理心。"},

  // ============ 小阿卡纳 - 星币 Pentacles (14张) ============
  // 星币组对应：斯莱特林精神 - 物质、财富、实用
  { id:"P1", name:"星币王牌", themeName:"古灵阁金币", originalName:"Ace of Pentacles", suit:"pentacles", element:"土",
    keywords:["机会","繁荣","富足","实际","稳固"], uprightBrief:"新的财务机会和物质繁荣", reversedBrief:"财务延迟机会错失",
    imageUrl:"icons/pentacles-01.png",
    upright:"新的财务机会和物质繁荣。实际的开始和稳固的基础。这是一个播种财富种子的好时机。",
    reversed:"财务延迟或机会错失。可能需要重新评估财务计划，或者机会需要更多努力才能实现。"},
  { id:"P2", name:"星币二", themeName:"平衡收支", originalName:"Two of Pentacles", suit:"pentacles", element:"土",
    keywords:["平衡","适应","波动","多任务","灵活"], uprightBrief:"平衡多重责任和适应变化", reversedBrief:"失衡或过度扩张",
    imageUrl:"icons/pentacles-02.png",
    upright:"平衡多重责任和适应变化。在波动中保持灵活。管理好资源和优先级。",
    reversed:"失衡或过度扩张。可能承担了太多无法管理的事情，需要重新优先排序。"},
  { id:"P3", name:"星币三", themeName:"三人组", originalName:"Three of Pentacles", suit:"pentacles", element:"土",
    keywords:["团队合作","技艺","认可","协作","质量"], uprightBrief:"团队合作和技艺的精进", reversedBrief:"缺乏团队合作质量不佳",
    imageUrl:"icons/pentacles-03.png",
    upright:"团队合作和技艺的精进。共同努力创造价值。认可和奖励即将到来。",
    reversed:"缺乏团队合作或质量不佳。可能工作不协调，需要改善沟通和协作。"},
  { id:"P4", name:"星币四", themeName:"守财奴", originalName:"Four of Pentacles", suit:"pentacles", element:"土",
    keywords:["稳定","保守","控制","安全感","吝啬"], uprightBrief:"财务的稳定和保守管理", reversedBrief:"过度控制财务损失",
    imageUrl:"icons/pentacles-04.png",
    upright:"财务的稳定和保守管理。保护你拥有的，但小心不要变得过于吝啬。安全感是重要的。",
    reversed:"过度控制或财务损失。可能过于执着于物质，需要学会分享和放手。"},
  { id:"P5", name:"星币五", themeName:"贫困", originalName:"Five of Pentacles", suit:"pentacles", element:"土",
    keywords:["困难","孤立","支持","恢复","精神"], uprightBrief:"财务困难和感觉被排斥", reversedBrief:"从困难中恢复",
    imageUrl:"icons/pentacles-05.png",
    upright:"财务困难和感觉被排斥。虽然艰难但你并不孤单。寻求帮助，困难不会永远持续。",
    reversed:"从困难中恢复。财务状况改善，或者精神上的富足取代物质匮乏。"},
  { id:"P6", name:"星币六", themeName:"慈善", originalName:"Six of Pentacles", suit:"pentacles", element:"土",
    keywords:["慷慨","公平","分享","给予","接受"], uprightBrief:"慷慨和公平的交换", reversedBrief:"不平等或自私",
    imageUrl:"icons/pentacles-06.png",
    upright:"慷慨和公平的交换。分享你的财富和知识。接受帮助也是一种智慧。",
    reversed:"不平等或自私。可能给予带有条件，或者需要建立更健康的给予和接受平衡。"},
  { id:"P7", name:"星币七", themeName:"耐心等待", originalName:"Seven of Pentacles", suit:"pentacles", element:"土",
    keywords:["耐心","评估","成长","投资","进展"], uprightBrief:"耐心和评估进展", reversedBrief:"缺乏进展急于求成",
    imageUrl:"icons/pentacles-07.png",
    upright:"耐心和评估进展。投资需要时间成长。审视你的努力是否朝着正确的方向。",
    reversed:"缺乏进展或急于求成。可能付出与回报不成正比，需要重新评估策略。"},
  { id:"P8", name:"星币八", themeName:"勤奋学习", originalName:"Eight of Pentacles", suit:"pentacles", element:"土",
    keywords:["努力","技艺","精通","专注","质量"], uprightBrief:"专注的工作和技艺的磨练", reversedBrief:"缺乏动力质量下降",
    imageUrl:"icons/pentacles-08.png",
    upright:"专注的工作和技艺的磨练。通过持续的努力达成精通。这是产出高质量工作的时期。",
    reversed:"缺乏动力或质量下降。可能对工作失去热情，需要重新找到工作的意义。"},
  { id:"P9", name:"星币九", themeName:"独立的成功", originalName:"Nine of Pentacles", suit:"pentacles", element:"土",
    keywords:["独立","丰裕","优雅","自足","成就"], uprightBrief:"物质上的独立和丰裕", reversedBrief:"过度依赖空虚的富有",
    imageUrl:"icons/pentacles-09.png",
    upright:"物质上的独立和丰裕。享受你努力工作的成果。这是自我满足和优雅生活的时期。",
    reversed:"过度依赖或空虚的富有。可能物质丰富但精神贫乏，需要寻找更深层的满足。"},
  { id:"P10", name:"星币十", themeName:"马尔福庄园", originalName:"Ten of Pentacles", suit:"pentacles", element:"土",
    keywords:["传承","家族","长久","财富","传统"], uprightBrief:"长久的财务安全和家族传承", reversedBrief:"财务损失家庭不和",
    imageUrl:"icons/pentacles-10.png",
    upright:"长久的财务安全和家族传承。物质上的圆满和传统的价值。建立可以传承的财富。",
    reversed:"财务损失或家庭不和。可能传统成为负担，需要重新定义什么是真正的财富。"},
  { id:"P11", name:"星币侍从", themeName:"霍格沃茨新生", originalName:"Page of Pentacles", suit:"pentacles", element:"土",
    keywords:["学习","新开始","踏实","计划","成长"], uprightBrief:"学习新技能和财务上的新开始", reversedBrief:"缺乏承诺或懒惰",
    imageUrl:"icons/pentacles-11.png",
    upright:"学习新技能和财务上的新开始。踏实的态度和实际的计划。专注于长期目标。",
    reversed:"缺乏承诺或懒惰。可能缺乏纪律，需要更有条理地追求目标。"},
  { id:"P12", name:"星币骑士", themeName:"可靠的守护者", originalName:"Knight of Pentacles", suit:"pentacles", element:"土",
    keywords:["可靠","勤奋","稳定","保守","坚持"], uprightBrief:"可靠和勤奋的工作", reversedBrief:"懒惰或过度保守",
    imageUrl:"icons/pentacles-12.png",
    upright:"可靠和勤奋的工作。稳定地朝着目标前进。虽然缓慢但坚定，最终会到达目的地。",
    reversed:"懒惰或过度保守。可能抗拒改变，或者进展过于缓慢需要加快步伐。"},
  { id:"P13", name:"星币王后", themeName:"纳西莎·马尔福", originalName:"Queen of Pentacles", suit:"pentacles", element:"土",
    keywords:["实用","养育","管理","平衡","丰裕"], uprightBrief:"实用和养育的财富", reversedBrief:"忽视自我照顾过度工作",
    imageUrl:"icons/pentacles-13.png",
    upright:"实用和养育的财富。善于管理资源和照顾他人。在物质和精神之间找到平衡。",
    reversed:"忽视自我照顾或过度工作。可能过于关注他人而忽视自己的需求，需要自我滋养。"},
  { id:"P14", name:"星币国王", themeName:"卢修斯·马尔福", originalName:"King of Pentacles", suit:"pentacles", element:"土",
    keywords:["成功","稳定","富有","慷慨","实际"], uprightBrief:"财务上的成功和稳定的领导", reversedBrief:"贪婪或过度控制",
    imageUrl:"icons/pentacles-14.png",
    upright:"财务上的成功和稳定的领导。通过实际和智慧的方式积累财富。你是可靠的提供者。",
    reversed:"贪婪或过度控制。可能过于执着于物质成功，需要记住财富不是一切。"}
];

// 导出 Map 以便 O(1) 查找
const tarotCardsMap = new Map(tarotCards.map(function(c) { return [c.id, c]; }));
